Repository elastic/cloud-on-k8s, pull requests merged in 2019-12, with the labels that each got.

#2181 Refactor 'watching' checks to use test.Watcher
  test/e2e/test/elasticsearch/checks_budget.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >refactoring, >test

#2188 Downgrade to basic if user deletes license secret
  docs/licensing.asciidoc
  go.sum
  pkg/controller/common/license/labels.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/client/license.go
  pkg/controller/elasticsearch/client/license_test.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/client/v7.go
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/elasticsearch/license/apply_test.go
  pkg/controller/elasticsearch/license/reconcile.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/trial/trial_controller.go
  test/e2e/es/license_test.go
  test/e2e/test/elasticsearch/steps_license.go
  test/e2e/test/watcher.go
Labels: >enhancement, v1.0.0

#2202 Add an E2E test to cover Elasticsearch CRD validation
  test/e2e/es/validation_test.go
Labels: >test, v1.0.0

#2205 Support 7.5
  build/ci/e2e/stack_versions.jenkinsfile
  test/e2e/es/version_upgrade_test.go
  test/e2e/kb/version_upgrade_test.go
Labels: >test

#2208 Fix readiness script in case of operator upgrade
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >bug, v1.0.0

#2211 Use a bugfixed version of controllerutil.SetControllerReference
  pkg/controller/common/certificates/http/public_secret_test.go
  pkg/controller/common/certificates/http/reconcile.go
  pkg/controller/common/reconciler/reconciler.go
  pkg/controller/common/reconciler/tmp_controller_ref.go
  pkg/controller/common/watches/handler_test.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/pdb/reconcile.go
  pkg/controller/elasticsearch/pdb/reconcile_test.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >bug, v1.0.0

#2199 Restore v1alpha1 in the list of crds
  config/crds/all-crds.yaml
  config/crds/patches/all-patches.yaml
  config/crds/patches/apm-kibana-patches.yaml
  config/crds/patches/elasticsearch-patches.yaml
  config/crds/patches/kustomization.yaml
Labels: >bug, v1.0.0

#2195 Remove finalizers
  cmd/manager/main.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/association/gc.go
  pkg/controller/common/association/gc_test.go
  pkg/controller/common/certificates/http/dynamic_watches.go
  pkg/controller/common/expectations/per_cluster.go
  pkg/controller/common/finalizer/finalizers.go
  pkg/controller/common/finalizer/finalizers_test.go
  pkg/controller/common/finalizer/handler.go
  pkg/controller/common/finalizer/handler_test.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/common/user/finalizer.go
  pkg/controller/common/user/utils.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/observer/finalizer.go
  pkg/controller/elasticsearch/observer/manager.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/controller/kibanaassociation/watch.go
Labels: >enhancement, v1.0.0

#2210 Update service when labels and annotations are modified
  pkg/controller/common/defaults/service.go
  pkg/controller/common/defaults/service_test.go
  pkg/controller/common/service_control.go
  pkg/controller/common/service_control_test.go
  pkg/controller/kibana/services_test.go
  pkg/utils/compare/objects.go
  pkg/utils/maps/maps.go
  pkg/utils/maps/maps_test.go
Labels: >bug, v1.0.0

#2215 Increase timeout of E2E runner
  test/e2e/cmd/run/run.go
Labels: :ci, >test

#2217 Inherit existing sset.volumeClaimTemplates ownerReferences
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/nodespec/resources_test.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/nodespec/statefulset_test.go
Labels: >bug, v1.0.0

#2206 Upgrade from trial to platinum/enterprise license
  pkg/controller/common/license/match.go
  pkg/controller/common/license/match_test.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/license_controller_test.go
  test/e2e/es/license_test.go
Labels: >enhancement, v1.0.0

#2227 E2E Tests: add GKE local SSD support
  hack/deployer/config/plans.yml
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/gke_ssd_provisioner.go
  hack/deployer/runner/storage.go
Labels: :ci

#2219 Refactor license labels to be more consistent
  docs/licensing.asciidoc
  pkg/controller/common/license/crud.go
  pkg/controller/common/license/crud_test.go
  pkg/controller/common/license/detection.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/labels.go
  pkg/controller/common/license/model.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/license_controller_integration_test.go
  pkg/controller/license/license_controller_test.go
Labels: >refactoring, v1.0.0

#2229 Workaround subresources status update error
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/common/status.go
  pkg/controller/common/status_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/kibana/kibana_controller.go
Labels: >bug, v1.0.0

#2230 CI: Only request 3 SSD per nodes
  hack/deployer/config/plans.yml
Labels: :ci

#2231 e2e: use scope label when creating license secrets
  test/e2e/test/elasticsearch/steps_license.go
Labels: >test

#2224 Do not reconcile APM Server if association is not fully configured
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/common/association/association.go
  pkg/controller/kibana/driver.go
Labels: >enhancement, v1.0.0

#2234 Split Makefile generate target
  Makefile
Labels: :ci, >test

#2238 Don't replace existing provisioner if new one is not provided
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/storage.go
Labels: :ci, >bug, >test

#2232 Bump ctrl-runtime dependency
  NOTICE.txt
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  docs/api-docs.asciidoc
  go.mod
  go.sum
  pkg/controller/common/certificates/http/public_secret_test.go
  pkg/controller/common/comparison/comparison.go
  pkg/controller/common/comparison/comparison_test.go
  pkg/controller/common/deployment/reconcile_test.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/common/reconciler/reconciler_test.go
  pkg/controller/common/service_control_test.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/certificates/transport/reconcile_test.go
  pkg/controller/elasticsearch/driver/bootstrap_test.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/pdb/reconcile_test.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >enhancement

#2246 e2e data check: adjust size of search query
  test/e2e/test/elasticsearch/checks_data.go
Labels: >test

#2245 Ignore licence error during state update
  pkg/controller/elasticsearch/driver/driver.go
Labels: >bug, v1.0.0

#2242 Support 7.6 and new stack level enterprise license type.
  pkg/controller/common/license/match.go
  pkg/controller/common/license/match_test.go
  pkg/controller/common/license/model.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/version.go
  pkg/controller/elasticsearch/driver/version_test.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/label/label_test.go
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/license_controller_integration_test.go
  pkg/controller/license/license_controller_test.go
  test/e2e/es/license_test.go
  test/e2e/test/elasticsearch/steps_license.go
Labels: >enhancement, v1.0.0

#2158 Add some documentation about the webhook
  docs/operator-config.asciidoc
  docs/troubleshooting.asciidoc
  docs/uninstalling-eck.asciidoc
  docs/webhook.asciidoc
Labels: >docs, v1.0.0

#2233 Minimize downtime during pod recycling
  NOTICE.txt
  go.mod
  go.sum
  pkg/controller/common/defaults/pod_template.go
  pkg/controller/common/defaults/pod_template_test.go
  pkg/controller/common/license/trial.go
  pkg/controller/elasticsearch/configmap/configmap.go
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/elasticsearch/nodespec/lifecycle_hook.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
  pkg/controller/elasticsearch/settings/environment.go
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/watcher.go
Labels: >enhancement, v1.0.0

#2264 [DOC] Empty limits are ineffective
  docs/managing-compute-resources.asciidoc
Labels: >docs, v1.0.0

#2260 Allow user to override readiness timeout
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >enhancement

#2250 Change priority order of reconcile results
  pkg/controller/common/reconciler/results.go
  pkg/controller/common/reconciler/results_test.go
Labels: >bug, v1.0.0

#2258 Remove mentions of the global operator in the docs
  docs/operator-config.asciidoc
Labels: >docs

#2273 Clarify location of podTemplate in doc example
  docs/managing-compute-resources.asciidoc
Labels: >docs

#2269 Change readiness timeout var
  docs/elasticsearch-specification.asciidoc
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >docs

#2265 Use the webhook server in e2e tests
  Makefile
  config/e2e/global_operator.yaml
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/es/naming_test.go
  test/e2e/test/context.go
  test/e2e/test/elasticsearch/steps_init.go
Labels: :ci, >test

#2272 Fix readiness probe
  pkg/controller/common/volume/downward_api.go
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/volume/names.go
Labels: >bug, v1.0.0

#2275 Do not fail if annotations file does not exist
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >bug, v1.0.0

#2249 Support enterprise license v4
  pkg/controller/common/license/check_test.go
  pkg/controller/common/license/crud_test.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/verifier.go
  pkg/controller/common/license/verifier_test.go
Labels: >non-issue, v1.0.0

#2281 Remove beta1 references
  VERSION
  docs/eck-attributes.asciidoc
Labels: >docs, v1.0.0

#2282 Reintroduce link to webhook documentation
  docs/operator-config.asciidoc
Labels: >docs, v1.0.0

#2280 Init 1.0.0 release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.0.0.asciidoc
Labels: >docs, v1.0.0

#2257 >=7.6.0: set allowed license upload types
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >non-issue, v1.0.0

#2283 Increase rolling upgrade unavailabilty threshold
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >flaky_test

#2286 Use xpack.license_management.ui.disabled setting in Kibana as of 7.6.0
  pkg/controller/kibana/config/fields.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/version/version6/settings.go
  pkg/controller/kibana/version/version7/settings.go
Labels: >non-issue, v1.0.0

#2289 Improve resource statuses logging
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/kibana/kibana_controller.go
Labels: >non-issue

#2287 Retry mutation update in E2E tests
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >flaky_test

#2290 Enable debug log level on the operator for E2E tests
  config/e2e/global_operator.yaml
  config/e2e/namespace_operator.yaml
Labels: >test

#2297 Declare OPERATOR_IMAGE in the environment
  build/ci/release/Jenkinsfile
Labels: :ci

#2296 Refactor FetchWithAssociation to return only err
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/association/conf.go
  pkg/controller/common/association/conf_test.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
Labels: >refactoring

#2300 Remove double-quotes from build env vars
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/e2e/vanilla_k8s.jenkinsfile
  build/ci/pr/Jenkinsfile
  build/ci/release/Jenkinsfile
Labels: :ci

#2307 Bump k8s version to 1.15.5 for AKS
  hack/deployer/config/plans.yml
Labels: :ci, >test

#2310 Change gke-ci plan to use europe-west2 region
  hack/deployer/config/plans.yml
Labels: :ci

#2292 Update operator config doc
  docs/operator-config.asciidoc
Labels: >docs

#2304 Bump min k8s version
  README.md
  docs/supported-versions.asciidoc
Labels: >docs

#2313 Increase e2e test timeout
  build/ci/e2e/Jenkinsfile-aks
  test/e2e/run.sh
Labels: :ci, >test

#2301 Remove enable-debug-logs flag
  config/operator/all-in-one/operator.template.yaml
  docs/troubleshooting.asciidoc
  pkg/utils/log/log.go
Labels: >breaking, >non-issue, v1.0.0

#2261 Add stack upgrade docs
  docs/index.asciidoc
  docs/upgrading-stack.asciidoc
Labels: >docs

#2317 Lower the unavailability threshold on ES >= 7.2
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#2277 Report total memory under management for licensing
  cmd/licensing-info/main.go
  cmd/manager/main.go
  pkg/controller/apmserver/pod.go
  pkg/controller/common/license/check.go
  pkg/controller/common/license/check_test.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/model.go
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/pod/pod.go
  pkg/controller/license/license_controller.go
  pkg/license/aggregator.go
  pkg/license/aggregator_test.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/reporter.go
  pkg/license/reporter_test.go
Labels: >feature, v1.0.0

#2312 Wait for webhook key to be present in fs
  cmd/manager/main.go
Labels: >bug

#2278 Ensure Kibana encryption key is specified
  docs/kibana.asciidoc
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/kibana/config/fields.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/config/settings_test.go
Labels: >enhancement

#2321 Don't upgrade pods if empty StatefulSet UpdateRevision
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
Labels: >bug
