Repository elastic/cloud-on-k8s, pull requests merged in 2019-08, with the labels that each got.

#1447 Proper removing GKE cluster after e2e test job
  build/ci/e2e/Jenkinsfile
Labels: :ci, >bug, v0.10.0

#1441 Add e2e test for kibana resources changes
  operators/test/e2e/kb/resource_test.go
  operators/test/e2e/test/kibana/builder.go
Labels: >test

#1451 Avoid test runner failure when namespace exists
  operators/Makefile
  operators/config/e2e/local_namespace.yaml
  operators/test/e2e/cmd/run/run.go
Labels: >bug, >test

#1456 Retry cleanup job on CI
  build/ci/support/cleanup.jenkinsfile
Labels: :ci

#1448 Move release job to devops-ci
  .ci/jobs/release.yml
Labels: :ci, v0.10.0

#1446 Drop single namespace assumption from E2E tests
  operators/test/e2e/apm/configuration_test.go
  operators/test/e2e/es/failure_test.go
  operators/test/e2e/kb/association_test.go
  operators/test/e2e/kb/failure_test.go
  operators/test/e2e/kb/keystore_test.go
  operators/test/e2e/kb/resource_test.go
  operators/test/e2e/test/apmserver/checks_k8s.go
  operators/test/e2e/test/apmserver/http_client.go
  operators/test/e2e/test/apmserver/steps_deletion.go
  operators/test/e2e/test/apmserver/steps_init.go
  operators/test/e2e/test/elasticsearch/checks_k8s.go
  operators/test/e2e/test/elasticsearch/checks_keystore.go
  operators/test/e2e/test/elasticsearch/checks_volume.go
  operators/test/e2e/test/elasticsearch/http_client.go
  operators/test/e2e/test/elasticsearch/steps_deletion.go
  operators/test/e2e/test/elasticsearch/steps_init.go
  operators/test/e2e/test/k8s_client.go
  operators/test/e2e/test/kibana/checks_k8s.go
  operators/test/e2e/test/kibana/http_client.go
  operators/test/e2e/test/kibana/steps_deletion.go
  operators/test/e2e/test/kibana/steps_init.go
  operators/test/e2e/test/run_failure.go
Labels: >test

#1464 Remove PVCs at the end of E2E tests
  operators/test/e2e/test/elasticsearch/steps_deletion.go
Labels: >test

#1476 Fix APM association E2E test failure
  operators/config/e2e/rbac.yaml
  operators/test/e2e/test/k8s_client.go
Labels: >test

#1404 Re-use Docker image for CI
  build/ci/Dockerfile
  build/ci/Makefile
  build/ci/pr/Jenkinsfile
Labels: :ci, v0.10.0

#1479 Calculate Docker image tag without paths
  build/ci/Makefile
Labels: :ci, >bug, v0.10.0

#1482 Increase E2E ES cluster size to fix APM test
  operators/test/e2e/apm/association_test.go
Labels: >test

#1486 Fix E2E test cleanup errors
  operators/config/e2e/global_operator.yaml
  operators/config/e2e/managed_namespaces.yaml
  operators/config/e2e/namespace_operator.yaml
  operators/config/e2e/operator_namespaces.yaml
  operators/test/e2e/cmd/run/run.go
  operators/test/e2e/test/context.go
Labels: >test

#1487 Add random prefix to e2e elastic stack name
  operators/test/e2e/apm/association_test.go
  operators/test/e2e/apm/configuration_test.go
  operators/test/e2e/apm/sample_test.go
  operators/test/e2e/apm/standalone_test.go
  operators/test/e2e/kb/association_test.go
  operators/test/e2e/kb/failure_test.go
  operators/test/e2e/kb/keystore_test.go
  operators/test/e2e/kb/resource_test.go
  operators/test/e2e/kb/sample_test.go
  operators/test/e2e/kb/telemetry_test.go
  operators/test/e2e/smoke_test.go
  operators/test/e2e/test/apmserver/builder.go
  operators/test/e2e/test/elasticsearch/builder.go
  operators/test/e2e/test/kibana/builder.go
Labels: >test

#1501 Update kubectl version
  build/build-tools-image/Dockerfile
  build/ci/Dockerfile
Labels: :ci, v0.10.0, v0.9.0

#1503 Trigger e2e tests after building release artifact
  build/ci/release/Jenkinsfile
Labels: :ci, v0.10.0

#1502 Update kubectl version
  build/build-tools-image/Dockerfile
  build/ci/Dockerfile
Labels: :ci, backport

#1504 Re-enable nightly snapshot build of ECK
  .ci/jobs/nightly.yml
Labels: :ci, v0.10.0

#1505 Reuse suffixed name in e2e tests
  operators/test/e2e/apm/configuration_test.go
  operators/test/e2e/es/certs_test.go
  operators/test/e2e/kb/keystore_test.go
  operators/test/e2e/kb/resource_test.go
  operators/test/e2e/test/apmserver/builder.go
  operators/test/e2e/test/kibana/builder.go
Labels: >test

#1471 Remove building docs from PR job
  build/ci/pr/Jenkinsfile
Labels: :ci, >docs

#1489 Clarify quickstart PV name
  docs/k8s-quickstart.asciidoc
Labels: >docs, v0.10.0, v0.9.0

#1492 Update cert example
  docs/accessing-services.asciidoc
Labels: >docs, v0.10.0, v0.9.0

#1511 Decrease ES name size in e2e tests
  operators/test/e2e/es/failure_test.go
  operators/test/e2e/es/mutation_test.go
Labels: >test

#1514 Minor uninstall doc update
  docs/index.asciidoc
  docs/uninstall.asciidoc
Labels: >docs

#1512 Clarify quickstart PV name (#1489)
  docs/k8s-quickstart.asciidoc
Labels: >docs, backport, v0.9.0

#1513 Update cert example (#1492)
  docs/accessing-services.asciidoc
Labels: >docs, backport, v0.9.0

#1509 Snapshots - rename section ID and reorganize index
  docs/elasticsearch-spec.asciidoc
  docs/index.asciidoc
  docs/snapshots.asciidoc
Labels: >docs

#1520 Snapshots section - reorganize index and rename ID (#1509)
  docs/elasticsearch-spec.asciidoc
  docs/index.asciidoc
  docs/snapshots.asciidoc
Labels: >docs, backport

#1516 Minor uninstall doc update (#1514)
  docs/index.asciidoc
  docs/uninstall.asciidoc
Labels: >docs, backport, v0.9.0

#1519 prevent HealthCheckNodePort updates
  operators/pkg/controller/common/service_control.go
  operators/pkg/controller/common/service_control_test.go
Labels: >bug, v0.10.0

#1515 Move e2e tests jobs to deployer
  build/ci/Makefile
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/Jenkinsfile-new
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/pr/Jenkinsfile
  operators/Makefile
  operators/hack/deployer/gke.go
Labels: :ci, >test

#1524 Fix nightly build
  build/ci/nightly/Jenkinsfile
Labels: :ci, >bug

#1530 Simplifying JJBB job descriptions
  .ci/jobs/cleanup.yml
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-custom.yml
  .ci/jobs/e2e-tests-aks.yaml
  .ci/jobs/e2e-tests-new.yaml
  .ci/jobs/e2e-tests.yaml
  .ci/jobs/gke-e2e-versions.yml
  .ci/jobs/nightly.yml
  .ci/jobs/pr.yml
  .ci/jobs/release.yml
Labels: :ci

#1506 Refactor downscales and add unit tests
  operators/pkg/controller/elasticsearch/client/model.go
  operators/pkg/controller/elasticsearch/driver/downscale.go
  operators/pkg/controller/elasticsearch/driver/downscale_test.go
  operators/pkg/controller/elasticsearch/driver/driver.go
  operators/pkg/controller/elasticsearch/driver/log.go
  operators/pkg/controller/elasticsearch/driver/nodes.go
  operators/pkg/controller/elasticsearch/sset/list.go
Labels: >refactoring, >test

#1533 Fix issue with CI jobs where Docker image is provided via parameters
  build/ci/Makefile
Labels: :ci, >bug

#1500 Add job to run e2e tests against different stack versions
  .ci/jobs/e2e-stack-versions.yml
  build/ci/Makefile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/nightly/Jenkinsfile
  operators/Makefile
Labels: :ci, v0.10.0

#1536 Update cleanup.jenkinsfile to use deployer tool
  build/ci/support/cleanup.jenkinsfile
Labels: :ci

#1517 Add webhook check for PVC modification
  operators/pkg/controller/elasticsearch/validation/validation.go
  operators/pkg/controller/elasticsearch/validation/validations.go
  operators/pkg/controller/elasticsearch/validation/validations_test.go
Labels: >breaking, v0.10.0

#1537 Delete cloud-on-k8s-e2e-tests-new job because it's not needed
  .ci/jobs/e2e-tests-new.yaml
  build/ci/e2e/Jenkinsfile-new
Labels: :ci

#1541 Stop re-building operator image in CI
  build/ci/e2e/Jenkinsfile
  build/ci/pr/Jenkinsfile
  operators/Makefile
Labels: >bug, >flaky_test, >test

#1547 Set stack version in Makefile
  operators/Makefile
Labels: :ci, >bug

#1548 Fix fail in job for testing different stack versions
  .ci/jobs/e2e-stack-versions.yml
Labels: :ci, >bug

#1552 E2E fix: Disable APM server ILM
  operators/Makefile
  operators/test/e2e/test/apmserver/builder.go
Labels: >test

#1543 Fix cleanup job
  build/ci/support/cleanup.jenkinsfile
Labels: :ci, >bug

#1561 Fix calling CI job after renaming
  build/ci/nightly/Jenkinsfile
Labels: :ci

#1559 Fix Docker issue in job for test different stack versions
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >bug

#1562 Passing proper ECK image name to downstream CI jobs
  build/ci/nightly/Jenkinsfile
Labels: :ci

#1567 Remove verbose flag from dep-vendor-only target
  operators/Makefile
Labels: >test

#1554 Remove deprecated ES keystore pkg & fs watch utils
  operators/pkg/controller/elasticsearch/initcontainer/keystore.go
  operators/pkg/controller/elasticsearch/keystore/client.go
  operators/pkg/controller/elasticsearch/keystore/config.go
  operators/pkg/controller/elasticsearch/keystore/environment.go
  operators/pkg/controller/elasticsearch/keystore/keystore.go
  operators/pkg/controller/elasticsearch/keystore/keystore_test.go
  operators/pkg/controller/elasticsearch/keystore/status.go
  operators/pkg/controller/elasticsearch/keystore/updater.go
  operators/pkg/controller/elasticsearch/keystore/updater_test.go
  operators/pkg/utils/fs/cache.go
  operators/pkg/utils/fs/cache_test.go
  operators/pkg/utils/fs/periodic.go
  operators/pkg/utils/fs/periodic_test.go
  operators/pkg/utils/fs/watch.go
  operators/pkg/utils/fs/watch_test.go
  operators/test/e2e/test/elasticsearch/checks_keystore.go
Labels: >refactoring

#1553 Remove some debug logs
  operators/pkg/controller/common/annotation/controller_version.go
  operators/pkg/controller/common/certificates/ca_reconcile.go
  operators/pkg/controller/common/reconciler/results.go
  operators/pkg/controller/common/watches/handler.go
  operators/pkg/controller/common/watches/named_watch.go
  operators/pkg/controller/elasticsearch/certificates/transport/reconcile.go
  operators/pkg/controller/license/license_controller.go
  operators/pkg/dev/portforward/pod_forwarder.go
Labels: >enhancement

#1549 Downscale one master at a time & don't remove last running master
  operators/pkg/controller/elasticsearch/driver/downscale.go
  operators/pkg/controller/elasticsearch/driver/downscale_invariants.go
  operators/pkg/controller/elasticsearch/driver/downscale_invariants_test.go
  operators/pkg/controller/elasticsearch/driver/downscale_test.go
  operators/pkg/controller/elasticsearch/driver/downscale_utils.go
  operators/pkg/controller/elasticsearch/driver/downscale_utils_test.go
  operators/pkg/controller/elasticsearch/label/label.go
Labels: justdoit

#1573 Optimize PR job
  build/ci/pr/Jenkinsfile
Labels: :ci, v0.10.0

#1574 Use correct document structure in podtemplate samples
  docs/elasticsearch-spec.asciidoc
Labels: >docs, v0.10.0, v0.9.0

#1576 Use correct document structure in podtemplate samples (#1574)
  docs/elasticsearch-spec.asciidoc
Labels: backport

#1566 Remove ElasticsearchInlineAuth from associations
  operators/config/crds/apm_v1alpha1_apmserver.yaml
  operators/config/crds/kibana_v1alpha1_kibana.yaml
  operators/pkg/apis/common/v1alpha1/authentication.go
  operators/pkg/apis/common/v1alpha1/zz_generated.deepcopy.go
  operators/pkg/apis/kibana/v1alpha1/kibana_types_test.go
  operators/pkg/controller/common/association/association.go
  operators/pkg/controller/common/association/association_test.go
Labels: >enhancement, v0.10.0

#1577 Add registry/repository to aks jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
Labels: :ci, >test

#1575 Replace in-job cluster removal with CI job call
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, v0.10.0

#1580 Preserve labels and annotations on public cert secrets
  operators/pkg/controller/common/certificates/http/certificates_secret_test.go
  operators/pkg/controller/common/certificates/http/public_secret.go
  operators/pkg/controller/common/certificates/http/public_secret_test.go
  operators/pkg/controller/common/certificates/http/reconcile_test.go
  operators/pkg/controller/common/certificates/http/testdata/ca.crt
  operators/pkg/controller/common/certificates/http/testdata/chain.crt
  operators/pkg/controller/common/certificates/http/testdata/corrupted.key
  operators/pkg/controller/common/certificates/http/testdata/tls.crt
  operators/pkg/controller/common/certificates/http/testdata/tls.key
  operators/pkg/controller/elasticsearch/certificates/transport/public_secret.go
  operators/pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  operators/pkg/utils/maps/maps.go
  operators/pkg/utils/maps/maps_test.go
Labels: >enhancement, v0.10.0

#1585 E2E fix: Timing issue in data integrity check
  operators/test/e2e/test/elasticsearch/checks_data.go
Labels: >test, v0.10.0

#1586 Fix issue when nightly build triggering test jobs
  build/ci/nightly/Jenkinsfile
Labels: :ci, >bug, v0.10.0

#1591 Restore notifications for fixed CI jobs
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, v0.10.0

#1551 Handle zen1 minimum_master_nodes special case for 2->1 masters
  operators/pkg/controller/elasticsearch/driver/downscale.go
  operators/pkg/controller/elasticsearch/driver/downscale_test.go
  operators/pkg/controller/elasticsearch/nodespec/fixtures.go
  operators/pkg/controller/elasticsearch/nodespec/resources_test.go
  operators/pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  operators/pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  operators/pkg/controller/elasticsearch/version/zen2/initial_master_nodes_test.go
  operators/pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
  operators/test/e2e/es/mutation_test.go
Labels: justdoit

#1595 Update zen2 settings only if there is no v6 master node
  operators/pkg/controller/elasticsearch/driver/downscale.go
  operators/pkg/controller/elasticsearch/driver/downscale_test.go
  operators/pkg/controller/elasticsearch/nodespec/fixtures.go
  operators/pkg/controller/elasticsearch/sset/pod.go
  operators/pkg/controller/elasticsearch/version/zen1/compatibility.go
  operators/pkg/controller/elasticsearch/version/zen2/compatibility.go
  operators/pkg/controller/elasticsearch/version/zen2/compatibility_test.go
  operators/pkg/controller/elasticsearch/version/zen2/initial_master_nodes_test.go
  operators/pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
  operators/pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
Labels: justdoit, v0.10.0

#1598 Add caching of Docker images for CI
  .ci/packer_cache.sh
  build/ci/Makefile
Labels: :ci, v0.10.0

#1596 Add unit tests for the sset package
  operators/pkg/controller/elasticsearch/driver/downscale.go
  operators/pkg/controller/elasticsearch/driver/nodes.go
  operators/pkg/controller/elasticsearch/driver/upgrade.go
  operators/pkg/controller/elasticsearch/nodespec/resources.go
  operators/pkg/controller/elasticsearch/sset/getter.go
  operators/pkg/controller/elasticsearch/sset/getter_test.go
  operators/pkg/controller/elasticsearch/sset/list.go
  operators/pkg/controller/elasticsearch/sset/list_test.go
  operators/pkg/controller/elasticsearch/sset/pod.go
  operators/pkg/controller/elasticsearch/sset/pod_test.go
  operators/pkg/controller/elasticsearch/sset/reconcile.go
  operators/pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >test

#1606 Add RBAC permission to E2E tests to access statefulsets
  operators/config/e2e/rbac.yaml
Labels: >test

#1600 Extract and unit test StatefulSets upscale
  operators/pkg/controller/elasticsearch/driver/nodes.go
  operators/pkg/controller/elasticsearch/driver/nodes_test.go
  operators/pkg/controller/elasticsearch/driver/upscale.go
  operators/pkg/controller/elasticsearch/driver/upscale_test.go
Labels: >test

#1594 Use deployer in operators/Makefile dev targets
  .gitignore
  operators/Makefile
  operators/hack/deployer/README.md
  operators/hack/deployer/cmd/create.go
  operators/hack/deployer/cmd/execute.go
  operators/hack/deployer/cmd/get.go
  operators/hack/deployer/cmd/root.go
  operators/hack/deployer/config/plans.yml
  operators/hack/deployer/main.go
  operators/hack/deployer/runner/aks.go
  operators/hack/deployer/runner/command.go
  operators/hack/deployer/runner/driver.go
  operators/hack/deployer/runner/gke.go
  operators/hack/deployer/runner/settings.go
  operators/hack/deployer/runner/vault.go
  operators/hack/gke-cluster.sh
Labels: :ci, >refactoring

#1609 Add unit tests for rolling upgrade
  operators/pkg/controller/elasticsearch/driver/downscale_test.go
  operators/pkg/controller/elasticsearch/driver/upgrade.go
  operators/pkg/controller/elasticsearch/driver/upgrade_test.go
  operators/pkg/controller/elasticsearch/nodespec/fixtures.go
Labels: >test

#1618 Fix path in e2e Jenkinsfile after dir change
  build/ci/e2e/Jenkinsfile
Labels: :ci, >test

#1622 Fix Packer cache
  .ci/packer_cache.sh
Labels: :ci, >bug, v0.10.0

#1613 Add tests and comments for lazy ESState implementation
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/esstate.go
  pkg/controller/elasticsearch/driver/esstate_test.go
  pkg/controller/elasticsearch/driver/upgrade.go
Labels: >test

#1593 Add basic support for Kind
  Makefile
  config/e2e/batch_job.yaml
  config/e2e/global_operator.yaml
  config/e2e/namespace_operator.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/kibana/kibana.yaml
  config/samples/kibana/kibana_es.yaml
  docs/accessing-services.asciidoc
  docs/advanced-node-scheduling.asciidoc
  docs/apm.asciidoc
  docs/elasticsearch-spec.asciidoc
  docs/k8s-quickstart.asciidoc
  docs/openshift.asciidoc
  docs/snapshots.asciidoc
  hack/kind/kind.sh
  hack/kind/local-path-storage.yaml
  test/e2e/es/certs_test.go
  test/e2e/smoke_test.go
Labels: >test

#1625 Add an E2E test for ES v6 to v7 rolling upgrade
  test/e2e/es/license_test.go
  test/e2e/es/mutation_test.go
  test/e2e/es/reversal_test.go
  test/e2e/kb/association_test.go
  test/e2e/kb/sample_test.go
  test/e2e/test/apmserver/steps_mutation.go
  test/e2e/test/builder.go
  test/e2e/test/elasticsearch/checks_data.go
  test/e2e/test/elasticsearch/checks_reversal.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/kibana/steps_mutation.go
  test/e2e/test/run_mutation.go
  test/e2e/test/run_reversal.go
Labels: >test

#1620 Create new pods with latest revision
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_test.go
Labels: >bug

#1626 Fix cleanup CI job after moving operators directory
  build/ci/support/cleanup.jenkinsfile
Labels: :ci, v0.10.0

#1627 Allow for multiple user specified secure settings secrets
  config/crds/apm_v1alpha1_apmserver.yaml
  config/crds/elasticsearch_v1alpha1_elasticsearch.yaml
  config/crds/kibana_v1alpha1_kibana.yaml
  pkg/apis/apm/v1alpha1/apmserver_types.go
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/certificates/reconcile.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/certificates/http/dynamic_watches.go
  pkg/controller/common/certificates/http/reconcile.go
  pkg/controller/common/certificates/http/reconcile_test.go
  pkg/controller/common/driver/interface.go
  pkg/controller/common/keystore/resources.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/common/watches/handler_integration_test.go
  pkg/controller/common/watches/handler_test.go
  pkg/controller/common/watches/named_watch.go
  pkg/controller/elasticsearch/certificates/ca_reconcile.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/settings/secure_settings.go
  pkg/controller/elasticsearch/settings/secure_settings_test.go
  pkg/controller/kibana/certificates/reconcile.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibanaassociation/association_controller.go
  test/e2e/apm/configuration_test.go
  test/e2e/es/keystore_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/kibana/builder.go
Labels: >enhancement, v0.10.0

#1636 Update uninstall.asciidoc
  docs/uninstall.asciidoc
Labels: v0.9.0

#1578 Generate events for reconcililation errors
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/events/events.go
  pkg/controller/common/reconciler/reconciler.go
  pkg/controller/common/reconciler/results.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/utils/k8s/k8sutils.go
Labels: >enhancement, v0.10.0

#1637 Remove deprecated TODO about masters removal
  pkg/controller/elasticsearch/driver/downscale.go
Labels: >non-issue

#1639 Fix script path in make check-license-header
  Makefile
Labels: >bug

#1640 Fix nightly build
  Makefile
Labels: :ci, >bug, v0.10.0

#1638 Move TestPod and TestSset into the sset package
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
  pkg/controller/elasticsearch/nodespec/resources_test.go
  pkg/controller/elasticsearch/sset/fixtures.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  pkg/controller/elasticsearch/version/zen2/compatibility_test.go
  pkg/controller/elasticsearch/version/zen2/initial_master_nodes_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
Labels: >non-issue

#1610 Refactor CI jobs and CI makefile
  .gitignore
  .golangci.yml
  Makefile
  build/ci/Dockerfile
  build/ci/Makefile
  build/ci/README.md
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/nightly/Jenkinsfile
  build/ci/pr/Jenkinsfile
  build/ci/release/Jenkinsfile
  build/ci/support/cleanup.jenkinsfile
Labels: :ci, >refactoring, >test

#1641 Delete unused script
  build/ci/delete_unused_disks.py
Labels: :ci, v0.10.0

#1645 kind-e2e should use ECK_IMAGE if provided
  Makefile
Labels: :ci

#1646 Make sure we update sset template hash label before updating the sset
  pkg/controller/common/reconciler/expectations.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/sset/fixtures.go
Labels: >bug

#1648 Add missing suffix to nightly, always login to acr
  build/ci/nightly/Jenkinsfile
  hack/deployer/runner/aks.go
Labels: :ci, >bug

#1623 Allow users to disable TLS for HTTP in the Elasticsearch spec
  pkg/apis/common/v1alpha1/common.go
  pkg/apis/common/v1alpha1/common_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/services/services_test.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/dev/portforward/pod_forwarder.go
  pkg/dev/portforward/pod_forwarder_test.go
  pkg/dev/portforward/service_forwarder.go
  test/e2e/es/http_test.go
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_data.go
  test/e2e/test/elasticsearch/checks_es.go
  test/e2e/test/elasticsearch/checks_reversal.go
  test/e2e/test/elasticsearch/http_client.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >enhancement, v0.10.0

#1649 e2e: only count data nodes in replica calculation algo
  test/e2e/test/elasticsearch/checks_data.go
  test/e2e/test/elasticsearch/settings.go
Labels: >test

#1651 Escape env vars in Jenkinsfile
  build/ci/nightly/Jenkinsfile
Labels: :ci, >bug

#1655 Populate docker credentials during release jobs
  build/ci/Makefile
  build/ci/nightly/Jenkinsfile
  build/ci/release/Jenkinsfile
Labels: :ci, >bug

#1658 Remove FeatureFlags from CRDs
  config/crds/apm_v1alpha1_apmserver.yaml
  config/crds/elasticsearch_v1alpha1_elasticsearch.yaml
  config/crds/kibana_v1alpha1_kibana.yaml
  pkg/apis/apm/v1alpha1/apmserver_types.go
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/common/v1alpha1/feature_flags.go
  pkg/apis/common/v1alpha1/feature_flags_test.go
  pkg/apis/common/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
Labels: >enhancement, >refactoring, v0.10.0

#1656 Remove gke storage class yaml, add patching sc in deployer
  config/dev/gke-default-storage.yaml
  hack/deployer/runner/gke.go
Labels: >test
