Repository elastic/cloud-on-k8s, pull requests merged in 2019-11, with the labels that each got.

#2099 Change rolling upgrades predicate log error to info level
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
Labels: justdoit

#2105 Dump k8s data when e2e test fails
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >test

#2102 Upgrade go.uber.org/zap to 1.12.0
  NOTICE.txt
  go.mod
  go.sum
Labels: >refactoring

#2110 Fix links to custom images documentation page
  docs/elasticsearch-specification.asciidoc
  docs/snapshots.asciidoc
Labels: >docs, v1.0.0-beta1

#2111 Fix links to custom images documentation page (#2110)
  docs/elasticsearch-specification.asciidoc
  docs/snapshots.asciidoc
Labels: backport, v1.0.0-beta1

#2114 Fix E2E tests job definitions
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >bug

#2088 Avoid lossy type conversion when parsing number of available replicas
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  pkg/apis/common/v1beta1/common.go
  pkg/controller/apmserver/state.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/kibana/state.go
Labels: justdoit

#1908 Add all in one comment
  Makefile
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/e2e/vanilla_k8s.jenkinsfile
  build/ci/nightly/Jenkinsfile
  build/ci/release/Jenkinsfile
Labels: >non-issue

#2127 Fix E2E tests job definitions
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci

#2124 Document license management
  docs/index.asciidoc
  docs/licensing.asciidoc
Labels: >docs, v1.0.0

#2125 Run license e2e tests
  Makefile
  build/ci/Makefile
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/e2e/vanilla_k8s.jenkinsfile
  config/e2e/batch_job.yaml
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/es/license_test.go
  test/e2e/test/context.go
Labels: :ci, >test

#2135 Fix nightly build job definition
  Makefile
  build/ci/nightly/Jenkinsfile
Labels: :ci

#2140 Ignore and do not use an empty CA
  pkg/controller/common/association/ca.go
  pkg/controller/common/association/ca_test.go
  pkg/controller/elasticsearch/certificates/ca_reconcile.go
Labels: >bug

#2126 Add webhook Secret and ValidatingWebhookConfiguration certificate management
  cmd/manager/main.go
  config/operator/all-in-one/operator.template.yaml
  config/operator/all-in-one/webhook.template.yaml
  config/operator/global/operator.template.yaml
  config/operator/global/webhook.template.yaml
  config/webhook/manifests.yaml
  pkg/apis/elasticsearch/v1beta1/webhook.go
  pkg/controller/common/certificates/ca_reconcile.go
  pkg/controller/common/certificates/ca_reconcile_test.go
  pkg/controller/webhook/cert.go
  pkg/controller/webhook/reconcile.go
  pkg/controller/webhook/reconcile_test.go
  pkg/controller/webhook/webhook_certificates_controller.go
Labels: >enhancement

#2144 Fix webhook flag in Makefile and docs
  Makefile
  docs/operator-config.asciidoc
Labels: :ci, >docs

#2145 Reconcile all clusters on license change
  pkg/controller/license/license_controller.go
  pkg/controller/license/list.go
  pkg/controller/license/list_test.go
  test/e2e/es/license_test.go
Labels: >enhancement, v1.0.0

#2152 Remove double quotes from docker address
  build/ci/nightly/Jenkinsfile
Labels: :ci, >bug

#2163 Run dump upload in every parallel build stage
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci

#2164 Use release build constraint for nightly build
  build/ci/nightly/Jenkinsfile
Labels: :ci

#2165 Nightly build: export LICENSE_PUBKEY variable
  build/ci/nightly/Jenkinsfile
Labels: :ci

#2166 Nightly: use release build tag only in Docker image build step
  build/ci/nightly/Jenkinsfile
Labels: :ci

#2162 Turn blacklist into warning events and logs statements
  docs/elasticsearch-specification.asciidoc
  pkg/apis/elasticsearch/v1beta1/fields.go
  pkg/apis/elasticsearch/v1beta1/validations.go
  pkg/apis/elasticsearch/v1beta1/validations_test.go
  pkg/apis/elasticsearch/v1beta1/warnings.go
  pkg/apis/elasticsearch/v1beta1/warnings_test.go
  pkg/apis/elasticsearch/v1beta1/webhook.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
Labels: >enhancement, v1.0.0

#2119 Remove v1alpha1 CRD version & generate a single trivial all-in-one flavor
  .gitignore
  Makefile
  build/ci/Makefile
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  config/crds-flavor-default/apm-and-kibana-podtemplate-patch.yaml
  config/crds-flavor-default/elasticsearch-podtemplate-patch.yaml
  config/crds-flavor-default/kustomization.yaml
  config/crds-flavor-trivial-versions/trivalize-versions-patch.yaml
  config/crds/all-crds.yaml
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/bases/kustomization.yaml
  config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/patches/apm-and-kibana-podtemplate-patch.yaml
  config/crds/patches/elasticsearch-podtemplate-patch.yaml
  config/crds/patches/kustomization.yaml
  docs/quickstart.asciidoc
  pkg/apis/apm/v1alpha1/apmserver_types.go
  pkg/apis/apm/v1alpha1/groupversion_info.go
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/common/v1alpha1/association.go
  pkg/apis/common/v1alpha1/association_test.go
  pkg/apis/common/v1alpha1/common.go
  pkg/apis/common/v1alpha1/common_test.go
  pkg/apis/common/v1alpha1/config.go
  pkg/apis/common/v1alpha1/config_test.go
  pkg/apis/common/v1alpha1/groupversion_info.go
  pkg/apis/common/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_config.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_config_test.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types_test.go
  pkg/apis/elasticsearch/v1alpha1/groupversion_info.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/groupversion_info.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/common/watches/handler_integration_test.go
  pkg/controller/license/license_controller_integration_test.go
  pkg/controller/license/trial/trial_controller_integration_test.go
  pkg/utils/test/integration.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
Labels: >breaking, v1.0.0

#2171 Sort seed hosts to avoid unecessary configmap updates
  pkg/controller/elasticsearch/settings/masters.go
  pkg/controller/elasticsearch/settings/masters_test.go
Labels: >enhancement

#2180 Don't use env variables ending in _FILE with Elasticsearch
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
  pkg/controller/elasticsearch/settings/environment.go
Labels: >bug, v1.0.0

#2137 Fix Kibana to terminate all pods before restarting during version change
  docs/kibana.asciidoc
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/common/deployment/reconcile.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/label/labels.go
  pkg/controller/kibana/pod/pod.go
  pkg/controller/kibana/pod/pod_test.go
  test/e2e/es/mutation_test.go
  test/e2e/es/reversal_test.go
  test/e2e/kb/version_upgrade_test.go
  test/e2e/test/builder.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_k8s.go
  test/e2e/test/kibana/steps_mutation.go
  test/e2e/test/run_mutation.go
  test/e2e/test/utils.go
  test/e2e/test/watcher.go
Labels: >bug

#2183 Fix gke k8s versions job definition
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
Labels: :ci

#2160 Autostart trial
  pkg/controller/common/license/labels.go
  pkg/controller/common/license/match.go
  pkg/controller/common/license/trial.go
  pkg/controller/common/license/trial_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/client/v7.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/elasticsearch/license/reconcile.go
  pkg/controller/license/trial/trial_controller.go
  pkg/controller/license/trial/trial_controller_integration_test.go
  test/e2e/es/license_test.go
  test/e2e/test/elasticsearch/steps_license.go
Labels: >enhancement, v1.0.0

#2187 Enable dump upload on cloud-on-k8s-e2e-tests-aks job
  build/ci/e2e/Jenkinsfile-aks
Labels: :ci, >test
