Repository elastic/cloud-on-k8s, pull requests merged in 2019-09, with the labels that each got.

#1676 Update documented command to delete all elastic resources
  docs/uninstall.asciidoc
Labels: >docs, v0.10.0, v0.9.0

#1672 Add relabel bot config for triaging issues
  .github/relabel.yaml
Labels: >non-issue

#1654 Add only one master node at a time
  pkg/controller/elasticsearch/driver/bootstrap.go
  pkg/controller/elasticsearch/driver/bootstrap_test.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/expectations.go
  pkg/controller/elasticsearch/driver/expectations_test.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/nodes_test.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_state.go
  pkg/controller/elasticsearch/driver/upscale_state_test.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/sset/fixtures.go
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/list_test.go
  pkg/controller/elasticsearch/sset/pod.go
  pkg/controller/elasticsearch/sset/pod_test.go
  pkg/controller/elasticsearch/version/zen2/initial_master_nodes.go
  pkg/controller/elasticsearch/version/zen2/initial_master_nodes_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
Labels: >enhancement

#1677 Update documented command to delete all elastic resources #1676
  docs/uninstall.asciidoc
Labels: >docs, backport

#1674 Update job for testing against stack versions from 7.3.0 to 7.3.1
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, v0.10.0

#1647 Validate Elasticsearch resource names
  config/crds/elasticsearch_v1alpha1_elasticsearch.yaml
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/controller/apmserver/name/name.go
  pkg/controller/common/certificates/ca_reconcile_test.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/common/name/name.go
  pkg/controller/common/name/name_test.go
  pkg/controller/elasticsearch/initcontainer/initcontainer_test.go
  pkg/controller/elasticsearch/name/name.go
  pkg/controller/elasticsearch/name/name_test.go
  pkg/controller/elasticsearch/settings/config_volume_test.go
  pkg/controller/elasticsearch/validation/upgrade_checks.go
  pkg/controller/elasticsearch/validation/validation.go
  pkg/controller/elasticsearch/validation/validation_test.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/kibana/name/name.go
  pkg/webhook/elasticsearch/handler_test.go
  test/e2e/es/naming_test.go
  test/e2e/test/apmserver/builder.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/kibana/builder.go
Labels: >enhancement, v0.10.0

#1680 Add more images to Packer cache
  .ci/packer_cache.sh
Labels: :ci, v0.10.0

#1682 Take master change budget into account when adding new stateful sets
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/checks_limiting.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >bug, v0.10.0

#1665 Support more secret volume fields in secure settings
  config/crds/apm_v1alpha1_apmserver.yaml
  config/crds/elasticsearch_v1alpha1_elasticsearch.yaml
  config/crds/kibana_v1alpha1_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/kibana/kibana.yaml
  docs/apm.asciidoc
  docs/elasticsearch-spec.asciidoc
  docs/snapshots.asciidoc
  pkg/apis/apm/v1alpha1/apmserver_types.go
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/common/v1alpha1/common.go
  pkg/apis/common/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/common/keystore/resources.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/keystore/user_secret_test.go
  test/e2e/apm/configuration_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/kibana/builder.go
Labels: >enhancement, v0.10.0

#1684 Fix incorrect data node count in e2e tests
  test/e2e/test/elasticsearch/settings.go
Labels: >test

#1681 Re-bootstrap single master 7.x clusters when upgrading from 6.x
  pkg/controller/elasticsearch/driver/bootstrap.go
  pkg/controller/elasticsearch/driver/bootstrap_test.go
  pkg/controller/elasticsearch/version/zen2/compatibility.go
  pkg/controller/elasticsearch/version/zen2/compatibility_test.go
  test/e2e/es/mutation_test.go
  test/e2e/es/naming_test.go
  test/e2e/es/version_upgrade_test.go
Labels: >bug, v0.10.0

#1685 Remove commas from docker_images array declaration.
  .ci/packer_cache.sh
Labels: :ci, v0.10.0

#1686 Adjust sampling rate in e2e test to be able to observe downscales
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#1688 Fix naming E2E test
  test/e2e/es/naming_test.go
Labels: >test, v0.10.0

#1696 For parameterized CI jobs add parameter to control Slack notifications
  .ci/jobs/e2e-custom.yml
  .ci/jobs/e2e-stack-versions.yml
  .ci/jobs/gke-e2e-versions.yml
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, v0.10.0

#1700 Update Packer cache for Docker images for newer Kind version
  .ci/packer_cache.sh
Labels: :ci, v0.10.0

#1706 Update location of Stack version attributes file
  docs/index.asciidoc
Labels: >docs, v0.10.0

#1699 Refactor logging configuration
  Makefile
  cmd/main.go
  pkg/about/info.go
  pkg/utils/log/log.go
  test/e2e/cmd/main.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/test/context.go
Labels: >enhancement, >refactoring, v0.10.0

#1687 Remove Elasticsearch field from CRDs
  config/crds/apm_v1alpha1_apmserver.yaml
  config/crds/kibana_v1alpha1_kibana.yaml
  pkg/apis/apm/v1alpha1/apmserver_types.go
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/common/v1alpha1/association.go
  pkg/apis/common/v1alpha1/association_test.go
  pkg/apis/common/v1alpha1/authentication.go
  pkg/apis/common/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1alpha1/kibana_types_test.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/certificates/reconcile.go
  pkg/controller/apmserver/config/config.go
  pkg/controller/apmserver/config/reconcile.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller_test.go
  pkg/controller/common/annotation/association.go
  pkg/controller/common/association/association.go
  pkg/controller/common/association/association_test.go
  pkg/controller/common/association/conf.go
  pkg/controller/common/association/conf_test.go
  pkg/controller/common/logging.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/es/secret.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibana/version/version6/settings.go
  pkg/controller/kibana/version/version7/settings.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/controller/kibanaassociation/association_controller_test.go
  pkg/controller/kibanaassociation/labels.go
  pkg/controller/license/license_controller.go
Labels: >enhancement, >refactoring, v0.10.0

#1715 Updating filename and location v0.9
  docs/index.asciidoc
Labels: >docs, backport

#1714 Updating filename and location v0.8
  docs/index.asciidoc
Labels: >docs, backport

#1709 Replace URL in Slack message to show Blue Ocean UI
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, v1.0.0-beta1

#1721 Rename run-config to deployer-config
  .gitignore
  Makefile
  build/ci/Makefile
  build/ci/README.md
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/pr/Jenkinsfile
  build/ci/support/cleanup.jenkinsfile
  hack/deployer/README.md
  hack/deployer/cmd/create.go
  hack/deployer/cmd/root.go
Labels: :ci, >refactoring

#1724 Generate xUnit compatible test results for unit and integration tests
  Makefile
  build/ci/Dockerfile
  build/ci/pr/Jenkinsfile
Labels: :ci, v1.0.0-beta1

#1695 Add API reference documentation
  Makefile
  docs/api-docs.asciidoc
  docs/index.asciidoc
  hack/api-docs/build.sh
  hack/api-docs/config.json
  hack/api-docs/templates/members.tpl
  hack/api-docs/templates/pkg.tpl
  hack/api-docs/templates/spec.tpl
  hack/api-docs/templates/type.tpl
Labels: >docs, v1.0.0-beta1

#1729 Do not support clusters with ES version <6.8
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/license/apply_test.go
  pkg/controller/elasticsearch/observer/observer_test.go
  pkg/controller/elasticsearch/observer/state_test.go
  pkg/controller/elasticsearch/validation/upgrade_checks_test.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/elasticsearch/version/supported_versions.go
  pkg/controller/elasticsearch/version/supported_versions_test.go
Labels: >enhancement

#1730 Remove statefulset config secret and headless service
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/settings/config_volume.go
  pkg/controller/elasticsearch/sset/fixtures.go
Labels: >bug, v1.0.0-beta1

#1726 Enable linter for hack dir and fix all issues
  .golangci.yml
  hack/deployer/cmd/create.go
  hack/deployer/cmd/root.go
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/settings.go
  hack/deployer/runner/vault.go
  hack/release_notes.go
Labels: :ci, >refactoring

#1728 Add list of supported versions to the docs
  docs/overview.asciidoc
Labels: >docs, v1.0.0-beta1

#1732 When using OnDelete strategy don't rely on current/updated revision
  pkg/controller/elasticsearch/driver/upgrade_test.go
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/list_test.go
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/checks_data.go
  test/e2e/test/run_mutation.go
Labels: >bug, v1.0.0-beta1

#1733 Ignore synced flush conflict during rolling upgrades
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/driver/upgrade.go
Labels: >enhancement

#1735 Standardize finalizers with fully qualified names
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/certificates/http/dynamic_watches.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/user/finalizer.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/observer/finalizer.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/controller/kibanaassociation/watch.go
Labels: justdoit, v1.0.0-beta1

#1740 Update k8s versions to run E2E tests on GKE
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
Labels: :ci, >bug, >test

#1741 Increase vault client timeout to 120s
  build/ci/Makefile
  hack/deployer/runner/vault.go
Labels: :ci, >test

#1698 Always enable file based user auth
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/settings/fields.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >bug, v1.0.0-beta1

#1719 Update ES resource phase to operational
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
  pkg/controller/elasticsearch/sset/reconcile.go
Labels: >bug, v1.0.0-beta1

#1747 Use attributes to keep docs up-to-date
  docs/accessing-services.asciidoc
  docs/advanced-node-scheduling.asciidoc
  docs/apm.asciidoc
  docs/eck-attributes.asciidoc
  docs/elasticsearch-spec.asciidoc
  docs/index.asciidoc
  docs/k8s-quickstart.asciidoc
  docs/openshift.asciidoc
  docs/snapshots.asciidoc
  docs/uninstall.asciidoc
  hack/update-samples-stack-version.sh
Labels: >docs, v1.0.0-beta1

#1745 Rolling Upgrade: Support master node type change
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/driver/upgrade_predicates.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/sset/fixtures.go
  pkg/controller/elasticsearch/sset/pod.go
  pkg/controller/elasticsearch/version/zen1/compatibility.go
  pkg/controller/elasticsearch/version/zen1/compatibility_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
Labels: >enhancement, v1.0.0-beta1

#1751 Remove grouping definition from the update strategy
  config/crds/elasticsearch_v1alpha1_elasticsearch.yaml
  docs/api-docs.asciidoc
  docs/elasticsearch-spec.asciidoc
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
Labels: >enhancement, >refactoring, v1.0.0-beta1

#1736 Remove old ES nodes PersistentVolumeClaims
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/pvc.go
  pkg/controller/elasticsearch/driver/pvc_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/sset/list.go
  pkg/utils/stringsutil/strings.go
  pkg/utils/stringsutil/strings_test.go
  test/e2e/test/elasticsearch/steps_deletion.go
Labels: >enhancement, v1.0.0-beta1

#1742 Fix handling of HTTP CA
  docs/accessing-services.asciidoc
  docs/api-docs.asciidoc
  docs/elasticsearch-spec.asciidoc
  pkg/apis/common/v1alpha1/association.go
  pkg/controller/apmserver/config/config.go
  pkg/controller/apmserver/config/config_test.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/association/ca.go
  pkg/controller/common/association/ca_test.go
  pkg/controller/common/certificates/http/certificates_secret.go
  pkg/controller/common/certificates/http/public_secret.go
  pkg/controller/common/certificates/http/public_secret_test.go
  pkg/controller/common/certificates/http/reconcile.go
  pkg/controller/common/certificates/pem.go
  pkg/controller/elasticsearch/certificates/ca_reconcile.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/config/settings_test.go
  pkg/controller/kibanaassociation/association_controller.go
Labels: >bug, v1.0.0-beta1

#1779 Use meta version attribute file in docs
  docs/index.asciidoc
Labels: >docs, v1.0.0-beta1

#1777 Bind ES Pod readiness to a node-local endpoint
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >enhancement

#1775 Set a dynamic MinAvailable value for the default PDB
  pkg/apis/common/v1alpha1/common.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types_test.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/pdb/reconcile.go
  pkg/controller/elasticsearch/pdb/reconcile_test.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
  pkg/controller/elasticsearch/sset/fixtures.go
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/list_test.go
  pkg/controller/elasticsearch/sset/reconcile.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >enhancement, v1.0.0-beta1

#1791 Fix APM e2e test on 6.x stack
  test/e2e/test/apmserver/checks_apm.go
Labels: >test

#1764 Generate notice file from dependency licences
  .golangci.yml
  Makefile
  NOTICE.txt
  hack/licence-detector/.gitignore
  hack/licence-detector/NOTICE.txt.tmpl
  hack/licence-detector/detector/detector.go
  hack/licence-detector/detector/detector_test.go
  hack/licence-detector/detector/testdata/deps.json
  hack/licence-detector/detector/testdata/github.com/davecgh/go-spew@v1.1.0/LICENCE.txt
  hack/licence-detector/detector/testdata/github.com/dgryski/go-minhash@v0.0.0-20170608043002-7fe510aff544/licence
  hack/licence-detector/detector/testdata/github.com/dgryski/go-spooky@v0.0.0-20170606183049-ed3d087f40e2/COPYING
  hack/licence-detector/detector/testdata/github.com/ekzhu/minhash-lsh@v0.0.0-20171225071031-5c06ee8586a1/some_file.txt
  hack/licence-detector/detector/testdata/github.com/russross/blackfriday/v2@v2.0.1/LICENSE.rst
  hack/licence-detector/generate-notice.sh
  hack/licence-detector/go.mod
  hack/licence-detector/go.sum
  hack/licence-detector/main.go
Labels: >docs, v1.0.0-beta1

#1778 Use synchronous calls to get the Shards
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/shard.go
  pkg/controller/elasticsearch/client/test_fixtures/cluster_state.go
  pkg/controller/elasticsearch/client/test_fixtures/shards.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/bootstrap.go
  pkg/controller/elasticsearch/driver/bootstrap_test.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/downscale_utils.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/esstate.go
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/testdata/cluster_state.json
  pkg/controller/elasticsearch/driver/testdata/shards.json
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/driver/upgrade_predicates.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/migration/fixtures.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/migration/migrate_data_test.go
  pkg/controller/elasticsearch/observer/observer_test.go
  pkg/controller/elasticsearch/observer/state.go
  pkg/controller/elasticsearch/observer/state_test.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
Labels: >enhancement, v1.0.0-beta1

#1790 Remove redundant Elasticsearch status attributes
  pkg/apis/elasticsearch/v1alpha1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/pvc.go
  pkg/controller/elasticsearch/driver/pvc_test.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/cluster_uuid.go
Labels: >refactoring, v1.0.0-beta1

#1789 Remove dep
  CONTRIBUTING.md
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Makefile
  NOTICE.txt
  build/ci/Dockerfile
  build/ci/Makefile
  dev-setup.md
  go.mod
  go.sum
  hack/check-requisites.sh
  hack/deployer/README.md
  pkg/utils/tools.go
  test/e2e/Dockerfile
Labels: >refactoring, v1.0.0-beta1

#1795 Add license check to CI
  Makefile
  NOTICE.txt
  go.mod
  go.sum
  hack/licence-detector/detector/detector.go
  hack/licence-detector/detector/detector_test.go
  hack/licence-detector/main.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/elasticsearch/migration/fixtures.go
Labels: :ci, >bug

#1798 Add operator config reference
  docs/index.asciidoc
  docs/operator-config.asciidoc
Labels: >docs

#1809 Reinstate operator role behaviour
  cmd/manager/main.go
  pkg/controller/common/operator/roles.go
  pkg/controller/common/operator/roles_test.go
  pkg/controller/controller.go
Labels: >refactoring, v1.0.0-beta1

#1803 Use more than 1 node on rolling upgrade E2E tests
  test/e2e/es/mutation_test.go
Labels: >flaky_test

#1804 Don't monitor health if single node rolling upgrade in E2E tests
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/step.go
Labels: >flaky_test

#1810 Set a default memory limit of 2Gi for the ES Pod
  pkg/controller/elasticsearch/nodespec/defaults.go
Labels: >enhancement, v1.0.0-beta1

#1815 Set APM Server default memory requests and limits to 512MiB
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/apmserver/pod.go
  pkg/controller/apmserver/pod_test.go
Labels: >enhancement, v1.0.0-beta1

#1813 Set expectations when upscaling a StatefulSet
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/sset/reconcile.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >bug, v1.0.0-beta1

#1818 Set a default 1Gi memory requests and limits for Kibana
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/pod/pod.go
  pkg/controller/kibana/pod/pod_test.go
Labels: >enhancement, v1.0.0-beta1

#1806 CI: Run checks before tests
  Makefile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/nightly/Jenkinsfile
  build/ci/pr/Jenkinsfile
Labels: :ci

#1797 Add docs on custom image
  docs/elasticsearch-spec.asciidoc
  docs/images.asciidoc
  docs/index.asciidoc
  docs/snapshots.asciidoc
Labels: >docs

#1816 Generate xUnit XML with test results in the case of test fail
  build/ci/pr/Jenkinsfile
Labels: :ci, v1.0.0-beta1

#1785 Update heap size and compute resources documentation
  docs/elasticsearch-spec.asciidoc
  docs/managing-compute-resources.asciidoc
Labels: >docs, v1.0.0-beta1
