Repository elastic/cloud-on-k8s, pull requests merged in 2019-10, with the labels that each got.

#1820 Factorize Kibana and APM deployments to use hash comparison
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/apmserver/deployment_control.go
  pkg/controller/common/deployment/reconcile.go
  pkg/controller/common/deployment/reconcile_test.go
  pkg/controller/common/hash/hash.go
  pkg/controller/kibana/deployment_control.go
  pkg/controller/kibana/deployment_control_test.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
Labels: justdoit, v1.0.0-beta1

#1829 Disable Manager metrics port in integration tests
  pkg/utils/test/integration.go
Labels: >flaky_test

#1805 Restore e2e test failures on cluster health retrieval
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/elasticsearch/steps_mutation_test.go
Labels: >test

#1830 Disable metrics following changes in controller-runtime
  cmd/manager/main.go
Labels: >bug

#1826 Fix nightly release job
  .gitignore
Labels: :ci, >bug, v1.0.0-beta1

#1836 Update to 7.4.0
  .ci/packer_cache.sh
  build/ci/e2e/stack_versions.jenkinsfile
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/kibana/kibana.yaml
  config/samples/kibana/kibana_es.yaml
Labels: :ci, >enhancement

#1834 Temporarily remove API docs
  docs/api-docs.asciidoc
  docs/index.asciidoc
Labels: >docs, v1.0.0-beta1

#1832 Memory usage improvements
  NOTICE.txt
  config/operator/all-in-one/operator.template.yaml
  go.mod
  pkg/controller/elasticsearch/sset/pod.go
  pkg/controller/elasticsearch/sset/pod_test.go
Labels: >refactoring

#1827 Force upgrade all Pods if non-ready
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_forced.go
  pkg/controller/elasticsearch/driver/upgrade_forced_test.go
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/driver/upscale_state_test.go
  pkg/controller/elasticsearch/sset/fixtures.go
  test/e2e/es/forced_upgrade_test.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/steps_forced_upgrade.go
Labels: >enhancement, v1.0.0-beta1

#1845 Fix remaining references to v1alpha1
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/sset/fixtures.go
Labels: >bug, v1.0.0-beta1

#1843 Rename nodes to nodeSets, nodeCount to count
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/kibana/kibana.yaml
  config/samples/kibana/kibana_es.yaml
  docs/advanced-node-scheduling.asciidoc
  docs/apm.asciidoc
  docs/elasticsearch-spec.asciidoc
  docs/k8s-quickstart.asciidoc
  docs/openshift.asciidoc
  docs/snapshots.asciidoc
  pkg/apis/apm/v1beta1/apmserver_types.go
  pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/kibana_types.go
  pkg/apis/kibana/v1beta1/kibana_types.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/common/association/conf_test.go
  pkg/controller/elasticsearch/driver/upscale.go
  pkg/controller/elasticsearch/name/name.go
  pkg/controller/elasticsearch/name/name_test.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/validation/validation_test.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/license/license_controller_integration_test.go
  test/e2e/es/forced_upgrade_test.go
  test/e2e/es/naming_test.go
  test/e2e/es/reversal_test.go
  test/e2e/test/apmserver/builder.go
  test/e2e/test/apmserver/checks_k8s.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_data.go
  test/e2e/test/elasticsearch/checks_es.go
  test/e2e/test/elasticsearch/checks_volume.go
  test/e2e/test/elasticsearch/settings.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_k8s.go
  test/e2e/test/kibana/checks_kb.go
Labels: >breaking, v1.0.0-beta1

#1842 Bump version to 1.0.0-beta1
  VERSION
  pkg/controller/common/annotation/controller_version.go
Labels: >non-issue, v1.0.0-beta1

#1848 Don't return keystore errors for rolling upgrade errors in e2e tests
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/checks_keystore.go
Labels: >flaky_test

#1844 Fix job for running e2e test against different ELK stack versions
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >test

#1849 Update the scheduling doc to account for StatefulSets changes
  docs/advanced-node-scheduling.asciidoc
Labels: >docs, v1.0.0-beta1

#1857 Update ELK stack version for e2e tests to 7.4
  Makefile
Labels: :ci, v1.0.0-beta1

#1860 Optimize checks stage for PR job
  build/ci/pr/Jenkinsfile
Labels: :ci, v1.0.0-beta1

#1861 Fix pod count check and downscale bug
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  test/e2e/test/elasticsearch/checks_budget.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >bug, >test, v1.0.0-beta1

#1862 Fix release build
  build/ci/release/Jenkinsfile
Labels: :ci

#1865 Revert scm settings change
  .ci/jobs/release.yml
Labels: :ci

#1868 Update quick-start doc
  docs/elasticsearch-spec.asciidoc
  docs/k8s-quickstart.asciidoc
Labels: >docs

#1879 Don't quote version in .env file
  build/ci/release/Jenkinsfile
Labels: :ci

#1850 Disable mmap in E2E tests
  config/samples/apm/apm_es_kibana.yaml
  config/samples/kibana/kibana_es.yaml
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#1880 Generate an event on sset spec change failure
  Makefile
  pkg/controller/elasticsearch/driver/nodes.go
Labels: >bug

#1852 Use kustomize to generate patched CRDs for specific flavors
  .gitignore
  Makefile
  build/ci/Makefile
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/pr/Jenkinsfile
  config/crds-flavor-default/apm-and-kibana-podtemplate-patch.yaml
  config/crds-flavor-default/elasticsearch-podtemplate-patch.yaml
  config/crds-flavor-default/kustomization.yaml
  config/crds-flavor-trivial-versions/kustomization.yaml
  config/crds-flavor-trivial-versions/trivalize-versions-patch.yaml
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/kustomization.yaml
  hack/patch-crd/go.mod
  hack/patch-crd/go.sum
  hack/patch-crd/main.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
Labels: :ci, >enhancement

#1893 Run ci job definition script with bash interpreter
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
Labels: :ci, >bug, >test

#1886 Trigger ELK stack tests after building release
  build/ci/release/Jenkinsfile
Labels: :ci, >enhancement, v1.0.0-beta1

#1895 Bump default k8s version for E2E tests to 1.13
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  hack/deployer/config/plans.yml
Labels: :ci, >test

#1888 Force upgrade pods of a same StatefulSet
  pkg/controller/elasticsearch/driver/upgrade_forced.go
  pkg/controller/elasticsearch/driver/upgrade_forced_test.go
  test/e2e/es/forced_upgrade_test.go
Labels: >enhancement, v1.0.0-beta1

#1897 Fix nil vault_client, improve deployer docs
  hack/deployer/README.md
  hack/deployer/config/plans.yml
  hack/deployer/runner/aks.go
Labels: >bug

#1901 Manifest generation: prefix objects with YAML document separator
  config/operator/Makefile
Labels: >bug, v1.0.0-beta1

#1903 Update k8s to 1.13 in JJBB
  .ci/jobs/e2e-custom.yml
Labels: :ci, >test

#1896 Update troubleshooting doc with StatefulSet
  docs/troubleshooting.asciidoc
Labels: >docs, v1.0.0-beta1

#1904 Upload all CRDs flavors during the release
  build/ci/Makefile
Labels: >enhancement, v1.0.0-beta1

#1905 Fix naming E2E test
  pkg/controller/elasticsearch/name/name.go
  test/e2e/es/naming_test.go
Labels: >test, v1.0.0-beta1

#1885 Add validation of Jenkins pipelines as part of PR job
  .gitignore
  Makefile
  build/ci/pr/Jenkinsfile
  hack/pipeline-validator/main.go
Labels: :ci, >enhancement, v1.0.0-beta1

#1914 Apply pod security policy to naming test
  test/e2e/es/naming_test.go
Labels: >test, v1.0.0-beta1

#1913 Rename statefulset label name with the "-name" suffix
  docs/troubleshooting.asciidoc
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
Labels: >enhancement, v1.0.0-beta1

#1912 Fix es hash labels
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
Labels: >enhancement, v1.0.0-beta1

#1859 Add NodeSets orchestration docs
  docs/elasticsearch-spec.asciidoc
  docs/orchestration.asciidoc
Labels: >docs, v1.0.0-beta1

#1919 Minor improvements in troubleshooting doc
  docs/troubleshooting.asciidoc
Labels: >docs, v1.0.0-beta1

#1920 Add statefulsets info in eck-dump tool
  hack/eck-dump.sh
Labels: >enhancement, v1.0.0-beta1

#1915 Remove ineffective initialisation of REPOSITORY
  Makefile
Labels: :ci, >test

#1894 Fix GitHub rendering of docs
  docs/accessing-elastic-services.asciidoc
  docs/advanced-node-scheduling.asciidoc
  docs/apm-server.asciidoc
  docs/custom-images.asciidoc
  docs/elasticsearch-specification.asciidoc
  docs/index.asciidoc
  docs/managing-compute-resources.asciidoc
  docs/openshift.asciidoc
  docs/operator-config.asciidoc
  docs/orchestration.asciidoc
  docs/overview.asciidoc
  docs/quickstart.asciidoc
  docs/snapshots.asciidoc
  docs/troubleshooting.asciidoc
  docs/uninstall.asciidoc
Labels: >docs

#1928 Recreate Elasticsearch client in ContinuousHealthCheck
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#1930 Disable serving prometheus metrics by default
  cmd/manager/main.go
  docs/operator-config.asciidoc
Labels: >enhancement, v1.0.0-beta1

#1929 Only delete disk relevant to a cluster
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
  build/ci/pr/Jenkinsfile
  hack/deployer/runner/gke.go
Labels: >test

#1931 Fix quickstart phase
  docs/quickstart.asciidoc
Labels: >docs, v1.0.0-beta1

#1926 Reorder E2E tests checks
  test/e2e/test/elasticsearch/checks_es.go
Labels: >flaky_test, v1.0.0-beta1

#1924 Remove global operator webhook cert secret
  config/operator/all-in-one/operator.template.yaml
  config/operator/global/operator.template.yaml
Labels: justdoit, v1.0.0-beta1

#1933 Use short name for all e2e jobs
  build/ci/e2e/Jenkinsfile
Labels: :ci, >test

#1938 Remove setting of vm.max_map_count in deployer and in GKE
  hack/deployer/config/plans.yml
  hack/deployer/runner/gke.go
  hack/deployer/runner/settings.go
Labels: :ci

#1942 Log validation errors
  pkg/controller/common/validation/validation.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
Labels: >enhancement, v1.0.0-beta1

#1941 Don't set a nil config that doesn't disable mmap in e2e tests
  test/e2e/es/forced_upgrade_test.go
Labels: >flaky_test

#1944 Disable mmap on all e2e tests relying on the Builder functions
  test/e2e/es/naming_test.go
  test/e2e/es/reversal_test.go
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#1946 Release notes script: add support for authenticated HTTP requests
  hack/release_notes.go
Labels: >non-issue

#1945 Add upgrade notes
  docs/index.asciidoc
  docs/quickstart.asciidoc
  docs/uninstalling-eck.asciidoc
  docs/upgrading-eck.asciidoc
Labels: >docs, v1.0.0-beta1

#1935 Clarify node type in docs
  docs/accessing-elastic-services.asciidoc
  docs/advanced-node-scheduling.asciidoc
  docs/elasticsearch-specification.asciidoc
  docs/managing-compute-resources.asciidoc
  docs/openshift.asciidoc
  docs/orchestration.asciidoc
  docs/quickstart.asciidoc
  docs/snapshots.asciidoc
  docs/troubleshooting.asciidoc
Labels: >docs, v1.0.0-beta1

#1936 Test sset list with pods not in sset
  pkg/controller/elasticsearch/sset/list_test.go
Labels: >test, justdoit

#1874 Add Kibana documentation
  docs/index.asciidoc
  docs/kibana.asciidoc
Labels: >docs, v1.0.0-beta1

#1918 Make ECK requirements more explicit
  docs/quickstart.asciidoc
Labels: >docs, v1.0.0-beta1

#1956 Update doc section about disabling TLS to include Elasticsearch
  docs/accessing-elastic-services.asciidoc
  docs/elasticsearch-specification.asciidoc
Labels: >docs

#1958 Improve YAML examples in the docs
  docs/elasticsearch-specification.asciidoc
  docs/snapshots.asciidoc
Labels: >docs, v1.0.0-beta1

#1957 Change documentation banner
  docs/page_header.html
Labels: >docs, v1.0.0-beta1

#1846 Improve readme
  README.md
Labels: >docs, >non-issue

#1959 Warn about all-in-one-no-validation.yaml for k8s prior to 1.13
  docs/quickstart.asciidoc
Labels: >docs, v1.0.0-beta1

#1962 Use xUnit compatible e2e test output for all e2e test jobs
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/Jenkinsfile-aks
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci

#1883 Update update strategy docs
  docs/elasticsearch-specification.asciidoc
  docs/upgrading-eck.asciidoc
  pkg/controller/elasticsearch/driver/upscale_state.go
Labels: >docs, v1.0.0-beta1

#1966 Managing compute resources - editing
  docs/managing-compute-resources.asciidoc
  docs/overview.asciidoc
Labels: >docs, v1.0.0-beta1

#1970 Check for nodeSet name uniqueness
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
Labels: >enhancement

#1971 Link release notes to index
  docs/index.asciidoc
Labels: >docs, v1.0.0-beta1

#1972 [CI]Fix clusterName
  build/ci/pr/Jenkinsfile
Labels: :ci

#1973 Fix spaces in quickstart doc
  docs/quickstart.asciidoc
Labels: >docs, v1.0.0-beta1

#1976 Editing - Creating custom images
  docs/custom-images.asciidoc
Labels: >docs, v1.0.0-beta1

#1980 Editing the Operator configuration section
  docs/operator-config.asciidoc
Labels: >docs, v1.0.0-beta1

#1981 Fix minor doc issues
  docs/custom-images.asciidoc
  docs/elasticsearch-specification.asciidoc
  docs/operator-config.asciidoc
  docs/overview.asciidoc
  docs/troubleshooting.asciidoc
Labels: >docs, v1.0.0-beta1

#1982 Replace "operator" with "ECK"
  docs/operator-config.asciidoc
Labels: >docs, v1.0.0-beta1

#1954 Init release highlights
  docs/index.asciidoc
  docs/release-notes.asciidoc
  docs/release-notes/highlights-1.0.0-beta1.asciidoc
  docs/release-notes/highlights.asciidoc
  docs/upgrading-eck.asciidoc
Labels: >docs, v1.0.0-beta1

#1983 Document secure settings breaking change
  docs/release-notes/1.0.0-beta1.asciidoc
  docs/upgrading-eck.asciidoc
Labels: >docs, v1.0.0-beta1

#1989 Mitigate memory leaks from long RequeueAfter periods
  pkg/controller/common/reconciler/results.go
  pkg/controller/common/reconciler/results_test.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/license_controller_test.go
Labels: >bug

#1949 Check expected Pods in E2E tests
  pkg/controller/elasticsearch/name/name.go
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/pod.go
  pkg/controller/elasticsearch/sset/pod_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/checks_keystore.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/k8s_client.go
Labels: >flaky_test

#1994 Upgrade controller-runtime to v0.3.0
  NOTICE.txt
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  go.mod
  go.sum
  pkg/apis/apm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apm/v1beta1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1beta1/zz_generated.deepcopy.go
Labels: >non-issue

#1974 Use the same, non-default storage class for e2e tests
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/storage.go
  test/e2e/apm/sample_test.go
  test/e2e/kb/sample_test.go
  test/e2e/smoke_test.go
  test/e2e/test/elasticsearch/builder.go
Labels: :ci, >bug, >test

#2003 Discover and test all samples
  config/samples/kibana/kibana.yaml
  test/e2e/apm/sample_test.go
  test/e2e/kb/sample_test.go
  test/e2e/samples.go
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/test/apmserver/builder.go
Labels: >test

#1998 Add failed e2e tests to Slack notifications
  build/ci/common/tests.groovy
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/Jenkinsfile
  build/ci/e2e/custom_operator_image.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >enhancement, >test

#1995 Add multi-namespace cache support
  Makefile
  cmd/manager/main.go
  config/e2e/batch_job.yaml
  config/e2e/managed_namespaces.yaml
  config/e2e/namespace_operator.yaml
  config/e2e/operator_namespaces.yaml
  config/e2e/rbac.yaml
  config/operator/Makefile
  config/operator/README.md
  config/operator/namespace/managed_ns_role_binding.template.yaml
  config/operator/namespace/operator.template.yaml
  config/operator/namespace/operator_ns_role_binding.template.yaml
  docs/operator-config.asciidoc
  test/e2e/apm/association_test.go
  test/e2e/cmd/run/eventlog.go
  test/e2e/cmd/run/run.go
  test/e2e/kb/association_test.go
  test/e2e/test/context.go
Labels: >breaking, >enhancement, v1.0.0

#2004 Add docs on running ES plugins on openshift
  docs/openshift.asciidoc
Labels: >docs

#2007 Add combined rolling update and scale down e2e test
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/checks_k8s.go
Labels: >test

#2016 Fix the default e2e volume claim template to be named elasticsearch-data
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#2025 Minimize Slack messages, show only test name and URL to details
  build/ci/common/tests.groovy
  build/ci/e2e/GKE_k8s_versions.jenkinsfile
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >enhancement, >test

#2029 Use discovery.seed_providers instead of discovery.zen.hosts_provider starting 7.x
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/settings/fields.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >bug, v1.0.0

#2035 Fix nil pointer in upgrade predicates
  pkg/controller/elasticsearch/driver/upgrade.go
  test/e2e/es/mutation_test.go
Labels: >bug, v1.0.0

#2000 Refactor expectations with proper garbage collection
  pkg/controller/common/expectations/deletions.go
  pkg/controller/common/expectations/deletions_test.go
  pkg/controller/common/expectations/expectations.go
  pkg/controller/common/expectations/expectations_test.go
  pkg/controller/common/expectations/generations.go
  pkg/controller/common/expectations/generations_test.go
  pkg/controller/common/expectations/per_cluster.go
  pkg/controller/common/expectations/per_cluster_test.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/expectations.go
  pkg/controller/elasticsearch/driver/expectations_test.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_forced_test.go
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/sset/fixtures.go
  pkg/controller/elasticsearch/sset/reconcile.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >enhancement, v1.0.0

#2021 Make association optional for Kibana
  docs/kibana.asciidoc
  pkg/apis/kibana/v1beta1/kibana_types.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/config/settings_test.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  test/e2e/kb/standalone_test.go
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/samples_test.go
  test/e2e/test/helper/yaml.go
Labels: >bug, v1.0.0

#2038 Always enable native realm
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/settings/fields.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >bug, v1.0.0

#2043 Add a note about errors from previous resources schema errors
  docs/upgrading-eck.asciidoc
Labels: >docs

#2022 Perform forced rolling upgrade even if ES is reachable
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_forced.go
  pkg/controller/elasticsearch/driver/upgrade_forced_test.go
  test/e2e/es/forced_upgrade_test.go
  test/e2e/test/elasticsearch/steps_forced_upgrade.go
Labels: >enhancement, v1.0.0

#2057 Document known issues in beta1
  docs/release-notes/highlights-1.0.0-beta1.asciidoc
Labels: >docs, v1.0.0-beta1

#2053 Add Kind images with K8s versions to Packer cache
  .ci/packer_cache.sh
Labels: :ci

#2060 Document known issues in beta1 (#2057)
  docs/release-notes/highlights-1.0.0-beta1.asciidoc
Labels: backport

#2055 Fix pod deletions expectations
  pkg/controller/common/expectations/deletions.go
Labels: >flaky_test

#2066 Check resource version when deleting a Pod during force-upgrades
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
Labels: >enhancement, v1.0.0

#2040 Re-enable API reference generation
  Makefile
  config/crds/apm.k8s.elastic.co_apmservers.yaml
  config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/kibana.k8s.elastic.co_kibanas.yaml
  docs/api-docs.asciidoc
  docs/index.asciidoc
  hack/api-docs/build.sh
  hack/api-docs/config.json
  hack/api-docs/templates/link_template.tpl
  hack/api-docs/templates/members.tpl
  hack/api-docs/templates/pkg.tpl
  hack/api-docs/templates/spec.tpl
  hack/api-docs/templates/type.tpl
  pkg/apis/apm/v1alpha1/groupversion_info.go
  pkg/apis/apm/v1beta1/apmserver_types.go
  pkg/apis/apm/v1beta1/doc.go
  pkg/apis/apm/v1beta1/groupversion_info.go
  pkg/apis/common/v1alpha1/groupversion_info.go
  pkg/apis/common/v1beta1/common.go
  pkg/apis/common/v1beta1/config.go
  pkg/apis/common/v1beta1/doc.go
  pkg/apis/common/v1beta1/groupversion_info.go
  pkg/apis/elasticsearch/v1alpha1/groupversion_info.go
  pkg/apis/elasticsearch/v1beta1/doc.go
  pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1beta1/groupversion_info.go
  pkg/apis/kibana/v1alpha1/groupversion_info.go
  pkg/apis/kibana/v1beta1/doc.go
  pkg/apis/kibana/v1beta1/groupversion_info.go
  pkg/apis/kibana/v1beta1/kibana_types.go
Labels: >docs, v1.0.0

#2062 Perform StatefulSets deletions before replicas downscale
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_invariants.go
  pkg/controller/elasticsearch/driver/downscale_invariants_test.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/downscale_utils.go
Labels: >bug

#2058 Add stack traces to version parsing
  pkg/controller/common/version/version.go
Labels: >refactoring

#2071 Move beats samples to recipes to avoid e2e breakage
  config/recipes/beats/0_ns.yaml
  config/recipes/beats/1_monitor.yaml
  config/recipes/beats/2_filebeat-kubernetes.yaml
  config/recipes/beats/3_metricbeat-kubernetes.yaml
Labels: >non-issue

#2073 Simplify license installation
  pkg/controller/common/license/parser.go
  pkg/controller/common/license/parser_test.go
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/elasticsearch/license/apply_test.go
  pkg/controller/license/license_controller.go
  pkg/controller/license/validation/validations_test.go
Labels: >enhancement

#2084 Update tests for stack versions to use latest Elastic stack
  build/ci/e2e/stack_versions.jenkinsfile
Labels: :ci, >enhancement, >test

#2083 Name service ports based on protocol
  pkg/apis/common/v1beta1/common.go
  pkg/apis/common/v1beta1/common_test.go
  pkg/controller/apmserver/services.go
  pkg/controller/apmserver/services_test.go
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/services/services_test.go
  pkg/controller/kibana/services.go
  pkg/controller/kibana/services_test.go
  pkg/utils/compare/json.go
Labels: justdoit

#2085 Remove default PVCs when setting emptyDirs in E2E tests
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#2076 remove rbac permissions related to batch/cronjobs as they are no longer used by the operator
  config/e2e/global_operator.yaml
  config/e2e/namespace_operator.yaml
  config/operator/all-in-one/cluster_role.template.yaml
  config/operator/global/cluster_role.template.yaml
  config/operator/namespace/cluster_role.template.yaml
  pkg/apis/elasticsearch/v1alpha1/groupversion_info.go
Labels: >refactoring

#2095 Filter non-JSON lines from E2E log file
  test/e2e/cmd/run/jsonlog.go
  test/e2e/cmd/run/jsonlog_test.go
  test/e2e/cmd/run/run.go
Labels: :ci, >bug

#2097 Fix KibanaAssociationWithNonExistentES E2E test
  test/e2e/kb/association_test.go
Labels: >test

#2094 Update OpenShift doc with info about mmap
  docs/openshift.asciidoc
Labels: >docs
