Repository elastic/cloud-on-k8s, pull requests merged in 2020-04, with the labels that each got.

#2793 Incorrect description of a node affinity example
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
Labels: >docs

#2739 Invoke common CI targets from a single target
  .ci/Makefile
  .ci/README.md
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-master-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
Labels: :ci

#2802 Add traffic splitting documentation
  docs/advanced-topics/advanced-topics.asciidoc
  docs/advanced-topics/traffic-splitting.asciidoc
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
Labels: >docs

#2757 Toggle read-only mode on Enterprise Search version upgrade
  pkg/controller/common/events/events.go
  pkg/controller/common/http_client.go
  pkg/controller/common/version/version.go
  pkg/controller/common/version/version_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/deployment.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  pkg/controller/enterprisesearch/labels.go
  pkg/controller/enterprisesearch/version_upgrade.go
  pkg/controller/enterprisesearch/version_upgrade_test.go
  pkg/controller/entsearchassociation/association_controller.go
Labels: >feature, v1.2.0

#2777 Restrict APM Server user role
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
Labels: >enhancement, v1.2.0

#2800 1.1.0 release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/highlights-1.1.0.asciidoc
  docs/release-notes/highlights.asciidoc
  hack/release-notes/README.md
Labels: >docs, v1.1.0

#2799 Remove enterprise search CRDs
  Makefile
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/bases/kustomization.yaml
  config/crds/patches/entsearch-patches.yaml
  config/crds/patches/kustomization.yaml
  config/operator/all-in-one/webhook.template.yaml
Labels: >refactoring, v1.1.0

#2803 Compatibility check: add Service ownership test
  pkg/controller/common/annotation/controller_version.go
  pkg/controller/common/annotation/controller_version_test.go
Labels: >bug, v1.2.0

#2798 Perform a normal flush instead of a sync flush when targeting Elasticsearch 8.0
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/client/v8.go
  pkg/controller/elasticsearch/driver/esstate_test.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_pods_deletion.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
Labels: justdoit, v1.2.0

#2810 Add disk resize troubleshooting doc
  docs/operating-eck/troubleshooting.asciidoc
Labels: >docs

#2811 Fix affinity docs typo
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
Labels: >docs

#2814 Remove leftover Enterprise Search references
  config/operator/all-in-one/cluster_role.template.yaml
  config/operator/all-in-one/rbac.yaml
  config/operator/global/rbac.yaml
  config/operator/namespace/cluster_role.template.yaml
  config/operator/namespace/rbac.yaml
Labels: >non-issue, v1.1.0

#2818 Update CI jobs to reflect 7.6.2 release
  .ci/jobs/e2e-tests-snapshot-versions-gke.yml
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
Labels: :ci

#2816 Clarify deployer make-switch-* vs. default config
  hack/deployer/README.md
Labels: >non-issue

#2786 Refactor association controllers to use more common code
  cmd/manager/main.go
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/common/v1/association.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/config/config.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller_test.go
  pkg/controller/apmserverelasticsearchassociation/labels.go
  pkg/controller/association/ca.go
  pkg/controller/association/ca_test.go
  pkg/controller/association/conf.go
  pkg/controller/association/conf_test.go
  pkg/controller/association/controller.go
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/ents_es.go
  pkg/controller/association/controller/kibana_es.go
  pkg/controller/association/dynamic_watches.go
  pkg/controller/association/gc.go
  pkg/controller/association/gc_test.go
  pkg/controller/association/rbac.go
  pkg/controller/association/rbac_test.go
  pkg/controller/association/reconciler.go
  pkg/controller/association/reconciler_test.go
  pkg/controller/association/resources.go
  pkg/controller/association/resources_test.go
  pkg/controller/association/user.go
  pkg/controller/association/user_test.go
  pkg/controller/common/association/association.go
  pkg/controller/common/association/association_test.go
  pkg/controller/common/unmanaged.go
  pkg/controller/common/unmanaged_test.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/version_upgrade.go
  pkg/controller/entsearchassociation/association_controller.go
  pkg/controller/entsearchassociation/labels.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/controller/kibanaassociation/labels.go
  pkg/controller/kibanaassociation/watch.go
  pkg/controller/remoteca/controller.go
  pkg/controller/remoteca/controller_test.go
  pkg/controller/remoteca/labels.go
  pkg/controller/remoteca/rbac.go
  pkg/controller/remoteca/remoteca_controller.go
  pkg/controller/remoteca/secret.go
  pkg/controller/remoteca/watches.go
Labels: >refactoring

#2805 Fix Filebeat in OCP for E2E tests monitoring
  .ci/setenvconfig
  config/e2e/filebeat.yaml
Labels: :ci, >test

#2820 Backport docs and bugfixes to 1.1
  .ci/Makefile
  .ci/README.md
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-master-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  docs/advanced-topics/advanced-topics.asciidoc
  docs/advanced-topics/traffic-splitting.asciidoc
  docs/operating-eck/troubleshooting.asciidoc
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
  docs/release-notes.asciidoc
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/highlights-1.1.0.asciidoc
  docs/release-notes/highlights.asciidoc
  hack/diagnostics/eck-dump.sh
  hack/release-notes/README.md
  pkg/controller/common/annotation/controller_version.go
  pkg/controller/common/annotation/controller_version_test.go
Labels: backport

#2831 Revert transport TLS certs verification from "full" to "certificate"
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/settings/merged_config.go
Labels: >bug, v1.1.0

#2834 Backport- revert transport TLS certs verification from "full" to "certificate" (#2831)
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/settings/merged_config.go
Labels: backport

#2648 Add EKS support to deployer
  .ci/Dockerfile
  .ci/jobs/e2e-tests-eks.yml
  .ci/pipelines/e2e-tests-eks.Jenkinsfile
  .ci/setenvconfig
  Makefile
  hack/deployer/cmd/create.go
  hack/deployer/config/local-disks/gke-ssd-patch.yaml
  hack/deployer/config/local-disks/kustomization.yaml
  hack/deployer/config/local-disks/ssd-provisioner.yaml
  hack/deployer/config/plans.yml
  hack/deployer/runner/command.go
  hack/deployer/runner/driver.go
  hack/deployer/runner/eks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/settings.go
  hack/deployer/runner/storage.go
Labels: :ci

#2835 Set correct credentials for release job
  .ci/jobs/build-release.yml
Labels: :ci

#2837 Silence the absence of controller-gen
  Makefile
Labels: :ci, justdoit

#2839 Set Jenkins kind job agent label
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
Labels: :ci

#2841 Increase total E2E job timeout and log when it is reached
  test/e2e/cmd/run/run.go
Labels: :ci

#2826 fix typo in README
  README.md
Labels: >docs

#2842 Backport - Increase total E2E job timeout and log when it is reached (#2841)
  test/e2e/cmd/run/run.go
Labels: backport

#2829 Add name in the webhook service port
  config/e2e/operator.yaml
  config/operator/all-in-one/webhook.template.yaml
  docs/operating-eck/webhook.asciidoc
Labels: >enhancement, v1.2.0

#2845 Clarify data migration function and unit tests
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/migration/migrate_data_test.go
Labels: >refactoring

#2844 Enable EKS e2e tests
  .ci/pipelines/build.Jenkinsfile
Labels: :ci

#2848 Add some temporary debugging to diagnose e2e test failures
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_es.go
  test/e2e/test/elasticsearch/debug.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/step.go
Labels: :ci

#2849 Dedicated job to debug TestMutationSecondMasterSetDown
  .ci/jobs/e2e-tests-testmutationsecondmastersetdown.yml
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
  Makefile
Labels: :ci, >test

#2851 Disable E2E tests report generation
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2855 Use 'ent' as Enterprise Search short name
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/patches/ent-patches.yaml
  config/crds/patches/kustomization.yaml
  config/operator/all-in-one/webhook.template.yaml
  config/samples/enterprisesearch/ent_es.yml
  config/webhook/manifests.yaml
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/webhook.go
  pkg/apis/enterprisesearch/v1beta1/webhook_test.go
  pkg/controller/association/controller/ent_es.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/deployment.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/fixtures.go
  pkg/controller/enterprisesearch/labels.go
  pkg/controller/enterprisesearch/name/name.go
  pkg/controller/enterprisesearch/pod.go
  pkg/controller/enterprisesearch/state.go
  pkg/controller/enterprisesearch/version_upgrade.go
  pkg/controller/enterprisesearch/version_upgrade_test.go
Labels: >enhancement, v1.2.0

#2857 Don't reject PVC update when a different unit is used
  pkg/apis/elasticsearch/v1/validations.go
  pkg/apis/elasticsearch/v1/validations_test.go
Labels: >bug, v1.1.0

#2859 Set Enterprise Search sample version to 7.7.0
  config/samples/enterprisesearch/ent_es.yml
Labels: justdoit, v1.2.0

#2858 Backport - Don't reject PVC update when different unit is used (#2857)
  pkg/apis/elasticsearch/v1/validations.go
  pkg/apis/elasticsearch/v1/validations_test.go
Labels: backport

#2865 Disable debug e2e job
  .ci/jobs/e2e-tests-testmutationsecondmastersetdown.yml
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2847 Document how to rotate credentials
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/orchestrating-elastic-stack-applications/rotate-credentials.asciidoc
Labels: >docs

#2797 Expand upgrading ECK doc + add annotator script
  docs/operating-eck/upgrading-eck.asciidoc
  hack/annotator/README.md
  hack/annotator/annotator.sh
Labels: >docs

#2861 Add unit test for Enterprise Search config reconciliation
  pkg/controller/enterprisesearch/config_test.go
Labels: >test, v1.2.0

#2872 Update docs to include annotation required by new versions of Istio.
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs

#2873 Adjust eksctl verbosity
  hack/deployer/runner/eks.go
Labels: :ci

#2863 Only setup scheme once
  .ci/setenvconfig
  Makefile
  cmd/licensing-info/main.go
  cmd/manager/main.go
  pkg/controller/common/deployment/reconcile_test.go
  pkg/controller/common/expectations/deletions_test.go
  pkg/controller/common/expectations/generations_test.go
  pkg/controller/common/license/model_test.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/nodespec/statefulset_test.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
  pkg/controller/elasticsearch/user/user_provided_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  pkg/utils/k8s/fake.go
  pkg/utils/test/integration.go
  pkg/utils/test/webhook.go
Labels: >non-issue, v1.1.0

#2880 Do not use annotations to cache Elasticsearch API calls
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/migration/migrate_data_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
Labels: >bug, v1.1.0

#2881 Retry k8s api calls in the test init phase
  test/e2e/test/apmserver/steps_init.go
  test/e2e/test/elasticsearch/steps_init.go
  test/e2e/test/kibana/steps_init.go
Labels: >flaky_test

#2882 Sort StatefulSets retrieved for a given ES cluster
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/list_test.go
Labels: >enhancement, v1.1.0

#2874 Backport credential rotation and upgrade docs
  docs/advanced-topics/service-meshes.asciidoc
  docs/operating-eck/upgrading-eck.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/orchestrating-elastic-stack-applications/rotate-credentials.asciidoc
  hack/annotator/README.md
  hack/annotator/annotator.sh
Labels: >docs, backport, v1.1.0

#2883 Do not use annotations to cache Elasticsearch API calls
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/migration/migrate_data_test.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters.go
  pkg/controller/elasticsearch/version/zen1/minimum_masters_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
Labels: backport, v1.1.0

#2884 Backport - Retry k8s api calls in the test init phase (#2881)
  test/e2e/test/apmserver/steps_init.go
  test/e2e/test/elasticsearch/steps_init.go
  test/e2e/test/kibana/steps_init.go
Labels: backport

#2886 Sort StatefulSets retrieved for ES clusters (#2882)
  pkg/controller/elasticsearch/sset/list.go
  pkg/controller/elasticsearch/sset/list_test.go
Labels: >enhancement, backport, v1.1.0

#2885 Revert "Disable debug e2e job (#2865)"
  .ci/jobs/e2e-tests-testmutationsecondmastersetdown.yml
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2888 Bump version in docs to 1.1.0
  docs/eck-attributes.asciidoc
Labels: >docs

#2890 Bump version in docs to 1.1.0 (#2888)
  docs/eck-attributes.asciidoc
Labels: >docs, backport, v1.1.0

#2876 Refactor calculatePerformableDownscale test
  pkg/controller/elasticsearch/driver/downscale_test.go
Labels: >refactoring

#2891 Use annotation to track created remote clusters
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/remotecluster/annotations.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch_test.go
Labels: >bug, v1.1.0

#2892 Use annotation to track created remote clusters (#2891)
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/remotecluster/annotations.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch_test.go
Labels: >bug, backport, v1.1.0

#2894 Add build number to debug cleanup job
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2893 Authenticate to GCP using an env var in the ocp deployer
  hack/deployer/runner/ocp.go
Labels: >enhancement

#2899 Increase AKS E2E tests job timeout
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
Labels: :ci, >test

#2896 Validate unknown fields in ES v1beta1
  pkg/apis/elasticsearch/v1beta1/validations.go
  pkg/apis/elasticsearch/v1beta1/validations_test.go
Labels: >enhancement, v1.1.0

#2902 Update go to 1.14.2
  .ci/Dockerfile
  Dockerfile
  hack/check/check-license-header.sh
  test/e2e/Dockerfile
Labels: justdoit

#2904 Validate unknown fields in ES v1beta1 (#2896)
  pkg/apis/elasticsearch/v1beta1/validations.go
  pkg/apis/elasticsearch/v1beta1/validations_test.go
Labels: backport

#2906 Make it clearer that reattach-pv should be compiled from source
  hack/reattach-pv/README.md
Labels: justdoit

#2889 Fix trial license validation issues
  pkg/controller/common/license/trial.go
  pkg/controller/common/license/trial_test.go
  pkg/controller/license/trial/trial_controller.go
  pkg/controller/license/trial/trial_controller_test.go
Labels: >bug, v1.1.0

#2905 Setup a temporary CI job to run TestDeleteServices again and again
  .ci/jobs/e2e-tests-testdeleteservices.yml
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
Labels: >flaky_test

#2907 Fix trial license validation issues (#2889)
  pkg/controller/common/license/trial.go
  pkg/controller/common/license/trial_test.go
  pkg/controller/license/trial/trial_controller.go
  pkg/controller/license/trial/trial_controller_test.go
Labels: >bug, backport

#2908 Disable xml reporting until we figure out what's wrong with it
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
Labels: :ci

#2887 Clarify upgrade instructions
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs

#2909 Clarify upgrade instructions (#2887)
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs, backport, v1.1.0

#2912 Run debug E2E tests unconditionally
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2914 Remove missing reference to notOnlyDocs() in E2E tests
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2916 Close client after noop observer comparisons
  pkg/controller/elasticsearch/observer/manager.go
Labels: >bug, v1.1.0

#2918 Close client after noop observer comparisons
  pkg/controller/elasticsearch/observer/manager.go
Labels: backport

#2921 Upgrade apm agent to latest master commit
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >bug, v1.1.0

#2923 Upgrade apm agent to latest master commit (#2921)
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: backport

#2924 Cleanup e2e debug clusters if successful only
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
  .ci/pipelines/e2e-tests-testmutationsecondmastersetdown.Jenkinsfile
Labels: :ci

#2926 Removed unused dependency on godog
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >refactoring

#2927 Avoid unnecessary bcrypt computation
  cmd/manager/main.go
  pkg/controller/association/user.go
  pkg/controller/enterprisesearch/config_test.go
Labels: >refactoring

#2929 Freeze tern to version 2.0.0
  hack/licence-detector/generate-image-deps.sh
Labels: :ci, justdoit

#2747 Clarify documentation about ECK support and licensing
  docs/operating-eck/licensing.asciidoc
Labels: >docs

#2903 Update base operator image to CentOS 8
  Dockerfile
  docs/reference/container-image-dependencies.csv
Labels: >enhancement, justdoit, v1.2.0

#2925 Regenerate 1.1.0 release notes
  docs/release-notes/1.1.0.asciidoc
  hack/licence-detector/README.md
Labels: >docs, v1.1.0

#2928 Remove unused dependency on godog
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: backport

#2935 Set kubernetes version for kind e2e test results reporting
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/setenvconfig
Labels: :ci, >test

#2931 Clarify documentation about ECK support and licensing (#2747)
  docs/operating-eck/licensing.asciidoc
Labels: >docs, backport, v1.1.0

#2934 Use enterprise_trial as the trial license type
  cmd/licensing-info/main.go
  cmd/manager/main.go
  docs/operating-eck/licensing.asciidoc
  pkg/controller/common/license/check.go
  pkg/controller/common/license/check_test.go
  pkg/controller/common/license/crud.go
  pkg/controller/common/license/detection.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/model_test.go
  pkg/controller/common/license/testdata/test-license-v4.json
  pkg/controller/common/license/trial.go
  pkg/controller/common/license/trial_test.go
  pkg/controller/common/license/verifier_test.go
  pkg/controller/license/trial/trial_controller.go
  pkg/controller/license/trial/trial_controller_integration_test.go
  pkg/controller/license/trial/trial_controller_test.go
  pkg/license/license.go
  pkg/license/reporter.go
  pkg/license/reporter_test.go
Labels: >bug, v1.1.0

#2938 Use enterprise_trial as the trial license type (#2934)
  cmd/licensing-info/main.go
  cmd/manager/main.go
  docs/operating-eck/licensing.asciidoc
  pkg/controller/common/license/check.go
  pkg/controller/common/license/check_test.go
  pkg/controller/common/license/crud.go
  pkg/controller/common/license/detection.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/model_test.go
  pkg/controller/common/license/testdata/test-license-v4.json
  pkg/controller/common/license/trial.go
  pkg/controller/common/license/trial_test.go
  pkg/controller/common/license/verifier_test.go
  pkg/controller/license/trial/trial_controller.go
  pkg/controller/license/trial/trial_controller_integration_test.go
  pkg/controller/license/trial/trial_controller_test.go
  pkg/license/license.go
  pkg/license/reporter.go
  pkg/license/reporter_test.go
Labels: backport

#2941 Stop setting up local disks by default
  hack/deployer/config/plans.yml
Labels: >non-issue

#2942 Check for ECK managed trials when matching licenses to clusters
  pkg/controller/common/license/match.go
  pkg/controller/common/license/match_test.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/model_test.go
Labels: >bug, v1.1.0

#2945 Check for ECK managed trials when matching licenses to clusters (#2942)
  pkg/controller/common/license/match.go
  pkg/controller/common/license/match_test.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/model_test.go
Labels: backport

#2944 Upgrade local volume provisioner to v2.3.4
  hack/deployer/config/local-disks/ssd-provisioner.yaml
Labels: justdoit

#2933 Fix Enterprise Search config unit test
  pkg/controller/enterprisesearch/config_test.go
Labels: >test

#2943 Add retries for Vault in CI
  .ci/Makefile
  .ci/common/retry.sh
Labels: :ci, >bug

#2950 Bump default Kubernetes version for AKS to latest non-preview version
  hack/deployer/config/plans.yml
Labels: :ci, >test

#2932 Use the new health endpoint for Enterprise Search readiness probe
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/pod.go
Labels: >enhancement, v1.2.0

#2952 Fix rendering of ES version in the filerealm doc example
  docs/orchestrating-elastic-stack-applications/elasticsearch/users-and-roles.asciidoc
Labels: >docs, v1.1.0

#2954 Backport - Fix rendering of ES version in the filerealm doc example (#2952)
  docs/orchestrating-elastic-stack-applications/elasticsearch/users-and-roles.asciidoc
Labels: backport

#2946 Flatten the Kibana controller package
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/kibana/config/defaults.go
  pkg/controller/kibana/config/defaults_test.go
  pkg/controller/kibana/config/fields.go
  pkg/controller/kibana/config/secret_volume.go
  pkg/controller/kibana/config/telemetry.go
  pkg/controller/kibana/config_reconcile.go
  pkg/controller/kibana/config_reconcile_test.go
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/es/secret.go
  pkg/controller/kibana/labels.go
  pkg/controller/kibana/name.go
  pkg/controller/kibana/name_test.go
  pkg/controller/kibana/pod.go
  pkg/controller/kibana/pod_test.go
  pkg/controller/kibana/services.go
  pkg/controller/kibana/services_test.go
  pkg/controller/kibana/state.go
  pkg/controller/kibana/volume/volumes.go
  pkg/license/aggregator.go
  pkg/license/reporter_test.go
  test/e2e/kb/failure_test.go
  test/e2e/kb/version_upgrade_test.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/checks_k8s.go
  test/e2e/test/kibana/http_client.go
Labels: >refactoring, v1.2.0

#2955 Make EKS deployer consistent with GKE one
  hack/deployer/runner/eks.go
Labels: :ci, >refactoring

#2956 Update licence detector version
  hack/licence-detector/generate-notice.sh
Labels: :ci, >non-issue

#2953 1.1.0 release highlights
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: >docs, v1.1.0

#2958 Backport 1.1.0 release highlights
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: >docs, backport, v1.1.0

#2871 Unit test Enterprise Search reconciliation
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  pkg/controller/enterprisesearch/name/name.go
Labels: >test, v1.2.0

#2966 Update release notes
  docs/release-notes/1.1.0.asciidoc
Labels: >docs, v1.1.0

#2972 Update Makefile
  .ci/Makefile
Labels: :ci

#2971 Wrap Kibana telemetry E2E API call in a retry block
  test/e2e/kb/telemetry_test.go
Labels: >flaky_test

#2975 Fix user http tls certificate watch leak
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  pkg/controller/kibana/controller.go
Labels: >bug, v1.2.0

#2968 Run yum update
  Dockerfile
Labels: :ci

#2978 Update 1.1.0 release highlights
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: >docs, v1.1.0

#2984 Remove docs link for CRD comment
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1beta1/apmserver_types.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1beta1/kibana_types.go
Labels: >docs

#2986 Remove docs link for CRD comment (#2984)
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1beta1/apmserver_types.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1beta1/kibana_types.go
Labels: backport

#2987 Remove docs link
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  docs/api-docs.asciidoc
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1beta1/apmserver_types.go
Labels: >docs

#2991 Remove dead link
  config/crds/all-crds.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  docs/api-docs.asciidoc
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1beta1/kibana_types.go
Labels: >docs

#3010 Fix APM Server user role
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/apm_es_test.go
  pkg/controller/association/controller/ent_es.go
  pkg/controller/association/controller/kibana_es.go
  pkg/controller/association/reconciler.go
  pkg/controller/association/reconciler_test.go
Labels: >bug, v1.2.0

#2979 Update 1.1.0 release highlights (#2978)
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: backport

#2877 Reconcile Enterprise Search status
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/controller/enterprisesearch/deployment.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
Labels: >enhancement, v1.2.0

#2964 Remove portforward logs from the `make go-run` output
  Makefile
  pkg/dev/portforward/doc.go
Labels: >non-issue

#3015 Backport - Simpler wording in licensing.asciidoc (#3012)
  docs/operating-eck/licensing.asciidoc
Labels: backport

#3014 Exclude EnterpriseSearch from 1.1 API docs
  docs/reference/api-docs.asciidoc
  hack/api-docs/build.sh
  hack/api-docs/config.yaml
Labels: >docs, v1.1.0

#3016 Update crd-ref-docs version
  hack/api-docs/build.sh
Labels: :ci, >non-issue

#2957 Reorganize files in the apmserver controller pkg
  pkg/controller/apmserver/config.go
  pkg/controller/apmserver/config/reconcile.go
  pkg/controller/apmserver/config_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/controller_test.go
  pkg/controller/apmserver/deployment.go
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/apmserver/labels.go
  pkg/controller/apmserver/name.go
  pkg/controller/apmserver/pod.go
  pkg/controller/apmserver/services.go
  pkg/controller/apmserver/services_test.go
  pkg/controller/kibana/driver.go
  test/e2e/test/apmserver/http_client.go
  test/e2e/test/k8s_client.go
Labels: >refactoring, v1.2.0

#3018 Disable the monitoring addon in AKS
  hack/deployer/runner/aks.go
Labels: :ci
