Repository elastic/cloud-on-k8s, pull requests merged in 2020-03, with the labels that each got.

#2543 Add local K8S remote cluster support
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/common/v1/common.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/name.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/controller/elasticsearch/certificates/ca_reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/model_test.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/remotecluster/annotations.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch_test.go
  pkg/controller/elasticsearch/remotecluster/remoteca/controller.go
  pkg/controller/elasticsearch/remotecluster/remoteca/controller_test.go
  pkg/controller/elasticsearch/remotecluster/remoteca/labels.go
  pkg/controller/elasticsearch/remotecluster/remoteca/rbac.go
  pkg/controller/elasticsearch/remotecluster/remoteca/secret.go
  pkg/controller/elasticsearch/remotecluster/remoteca/watches.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/volume/names.go
  pkg/controller/remoteca/remoteca_controller.go
Labels: >feature, v1.1.0

#2649 Backport service mesh doc correction
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs, backport

#2642 Don't call the voting config exclusions API at every single reconciliation
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions.go
  pkg/controller/elasticsearch/version/zen2/voting_exclusions_test.go
Labels: >enhancement, v1.1.0

#2497 Bump controller-tools
  Makefile
  NOTICE.txt
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/patches/apm-kibana-patches.yaml
  config/crds/patches/elasticsearch-patches.yaml
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  pkg/controller/elasticsearch/driver/upgrade_test.go
Labels: >enhancement, v1.1.0

#2643 Fix header levels of documentation
  docs/advanced-topics/custom-images.asciidoc
  docs/advanced-topics/openshift.asciidoc
  docs/help.asciidoc
  docs/operating-eck/licensing.asciidoc
  docs/operating-eck/troubleshooting.asciidoc
  docs/operating-eck/upgrading-eck.asciidoc
  docs/operating-eck/webhook.asciidoc
  docs/orchestrating-elastic-stack-applications/kibana.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  docs/overview.asciidoc
Labels: >docs, >refactoring

#2650 Bump controller-runtime
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  pkg/controller/common/certificates/http/public_secret_test.go
  pkg/controller/common/certificates/http/reconcile.go
  pkg/controller/common/reconciler/reconciler.go
  pkg/controller/common/reconciler/tmp_controller_ref.go
  pkg/controller/common/watches/handler_test.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/elasticsearch/pdb/reconcile.go
  pkg/controller/elasticsearch/pdb/reconcile_test.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >refactoring, v1.1.0

#2636 User-provided config take precedence over operator config
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >enhancement, v1.1.0

#2662 Remove the snapshot tests from the stack versions job
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
Labels: :ci

#2664 Move pod template document
  docs/orchestrating-elastic-stack-applications/customize-pods.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/orchestration.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/pod-template.asciidoc
  docs/orchestrating-elastic-stack-applications/kibana.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/reference/glossary.asciidoc
Labels: >docs

#2665 Add yaml manifest to code samples
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
Labels: >docs

#2669 Add a JJBB job for snapshot e2e tests
  .ci/Makefile
  .ci/jobs/e2e-cleanup-gke.yml
  .ci/jobs/e2e-tests-snapshot-versions-gke.yml
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/setenvconfig
Labels: :ci, >test

#2659 Update transport cert verification to full
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/settings/merged_config.go
Labels: >enhancement, v1.1.0

#2668 Remove needs-version re-label rule
  .github/relabel.yml
Labels: >non-issue

#2676 Fix snapshot test pipeline and include 7.6.2
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: :ci, >test

#2678 Clarify statement regarding k8s Ingress
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
Labels: >docs

#2683 Set the mininum character length for the abbreviated Git SHA
  Makefile
Labels: :ci

#2635 Add documentation on how to restrict cross namespace associations
  docs/operating-eck/operating-eck.asciidoc
  docs/operating-eck/operator-config.asciidoc
  docs/operating-eck/restrict-cross-namespace-associations.asciidoc
Labels: >docs, v1.1.0

#2677 Add ContainsKeys utility function
  pkg/controller/elasticsearch/remotecluster/remoteca/watches.go
  pkg/controller/kibanaassociation/labels.go
  pkg/utils/maps/maps.go
  pkg/utils/maps/maps_test.go
Labels: >refactoring

#2688 Add the EnterpriseSearch CRD and controller
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/bases/kustomization.yaml
  config/crds/patches/entsearch-patches.yaml
  config/crds/patches/kustomization.yaml
  config/e2e/operator.yaml
  config/e2e/rbac.yaml
  config/operator/all-in-one/cluster_role.template.yaml
  config/operator/all-in-one/rbac.yaml
  config/operator/global/rbac.yaml
  config/operator/namespace/cluster_role.template.yaml
  config/operator/namespace/rbac.yaml
  config/samples/enterprisesearch/entsearch_es.yml
  docs/reference/api-docs.asciidoc
  pkg/apis/enterprisesearch/v1beta1/doc.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/groupversion_info.go
  pkg/apis/enterprisesearch/v1beta1/zz_generated.deepcopy.go
  pkg/controller/common/container/container.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/enterprisesearch/certs.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/default_user.go
  pkg/controller/enterprisesearch/deployment.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/labels.go
  pkg/controller/enterprisesearch/name/name.go
  pkg/controller/enterprisesearch/pod.go
  pkg/controller/enterprisesearch/state.go
  pkg/controller/entsearchassociation/association_controller.go
  pkg/controller/entsearchassociation/labels.go
Labels: >feature, v1.1.0

#2699 Remove deprecated associations apiGroups RBAC permissions
  config/e2e/operator.yaml
  config/e2e/rbac.yaml
Labels: >non-issue

#2700 Don't create the default Enterprise Search user
  pkg/controller/enterprisesearch/default_user.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/pod.go
Labels: >enhancement, v1.1.0

#2671 Add support matrix link
  docs/supported-versions.asciidoc
Labels: >docs

#2691 Make transport service customizable
  config/crds/all-crds.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/patches/elasticsearch-patches.yaml
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/http-settings-tls-sans.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/controller/common/reconciler/reconciler.go
  pkg/controller/common/service_control.go
  pkg/controller/common/service_control_test.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/services/services_test.go
Labels: >enhancement, v1.1.0

#2705 Correct GKE subnet size
  hack/deployer/config/plans.yml
  hack/deployer/runner/gke.go
Labels: :ci, >bug

#2709 Update transport doc
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
Labels: >docs

#2679 Association controller bug fixes
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller_test.go
  pkg/controller/apmserverelasticsearchassociation/labels.go
  pkg/controller/common/association/ca.go
  pkg/controller/common/association/resources.go
  pkg/controller/elasticsearch/initcontainer/prepare_fs.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/controller/kibanaassociation/association_controller_test.go
  pkg/controller/kibanaassociation/labels.go
Labels: >bug, v1.1.0

#2703 Document file realm and roles in the ES spec
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/users-and-roles.asciidoc
  docs/quickstart.asciidoc
Labels: >docs, v1.1.0

#2715 Prevent pod deletion while ES node still contains shards
  docs/orchestrating-elastic-stack-applications/elasticsearch/orchestration.asciidoc
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/migration/migrate_data_test.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
Labels: >bug, v1.1.0

#2727 Remove GKE 1.13 and switch to 1.14
  .ci/jobs/e2e-tests-custom-operator-image-gke.yml
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  hack/deployer/config/plans.yml
Labels: :ci

#2718 Document remote cluster setup within the same k8s cluster
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
Labels: >docs

#2707 Homogenize secrets reconciliation with a helper function
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/apmserver/config/reconcile.go
  pkg/controller/apmserver/pod.go
  pkg/controller/apmserver/pod_test.go
  pkg/controller/common/association/ca.go
  pkg/controller/common/association/user.go
  pkg/controller/common/certificates/ca_reconcile.go
  pkg/controller/common/certificates/http/public_secret.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/reconciler/secret.go
  pkg/controller/common/reconciler/secret_test.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
  pkg/controller/elasticsearch/certificates/transport/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/reconcile_test.go
  pkg/controller/elasticsearch/remotecluster/remoteca/secret.go
  pkg/controller/elasticsearch/settings/config_volume.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/kibana/config/reconciler.go
  pkg/controller/license/license_controller.go
Labels: >refactoring, v1.1.0

#2728 Get monitoring secrets in all pipelines
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  .ci/pipelines/pr-gke.Jenkinsfile
  .ci/setenvconfig
Labels: :ci, >test

#2731 Add API doc exclusions for Enterprise Search
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs

#2735 Retry entire cleanup pipeline on failure
  .ci/pipelines/cleanup-gke.Jenkinsfile
Labels: :ci

#2740 Fix transport certificates reconciliation
  pkg/controller/elasticsearch/certificates/transport/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/reconcile_test.go
Labels: >bug, v1.1.0

#2702 Add Istio gateway recipe
  config/recipes/README.asciidoc
  config/recipes/istio-gateway/00-prereq-mtls.yaml
  config/recipes/istio-gateway/01-prereq-namespace.yaml
  config/recipes/istio-gateway/02-prereq-selfsigning-issuer.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/istio-gateway/04-certificates.yaml
  config/recipes/istio-gateway/05-gateway.yaml
  config/recipes/istio-gateway/06-es-traffic-split.yaml
  config/recipes/istio-gateway/07-kibana.yaml
  config/recipes/istio-gateway/README.asciidoc
  config/recipes/istio-gateway/kiali.png
Labels: >docs

#2719 Add Traefik recipe
  config/recipes/traefik/00-prereq-cluster-issuer.yaml
  config/recipes/traefik/01-certificate.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/recipes/traefik/03-node-type-svc.yaml
  config/recipes/traefik/04-middleware.yaml
  config/recipes/traefik/05-ingress-route.yaml
  config/recipes/traefik/README.asciidoc
Labels: >docs

#2749 Fix red cluster healh reported on tls toggle e2e test
  test/e2e/test/elasticsearch/builder.go
Labels: >test, v1.1.0

#2748 Fix TestMutationHTTPToHTTPS and TestMutationHTTPSToHTTP test builders
  test/e2e/es/mutation_test.go
Labels: >test, v1.1.0

#2721 Check licence compatibility
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/licence-detector/detector/detector.go
  hack/licence-detector/detector/detector_test.go
  hack/licence-detector/overrides/overrides.json
Labels: :ci

#2725 Update linter
  .ci/Dockerfile
  .golangci.yml
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/validations.go
  pkg/apis/elasticsearch/v1/warnings.go
  pkg/apis/elasticsearch/v1/webhook.go
  pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1beta1/validations.go
  pkg/apis/elasticsearch/v1beta1/warnings.go
  pkg/apis/elasticsearch/v1beta1/webhook.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/association/gc_test.go
  pkg/controller/elasticsearch/driver/upscale_state_test.go
  pkg/controller/elasticsearch/observer/state.go
  pkg/controller/elasticsearch/pdb/reconcile.go
  pkg/controller/elasticsearch/remotecluster/remoteca/secret.go
  pkg/controller/elasticsearch/sset/pod_test.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
  pkg/controller/elasticsearch/user/associated.go
  pkg/controller/elasticsearch/user/associated_test.go
  pkg/controller/elasticsearch/user/reconcile.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  pkg/utils/k8s/k8sutils.go
  pkg/utils/k8s/k8sutils_test.go
  test/e2e/test/kibana/http_client.go
Labels: :ci

#2724 Add automaxprocs
  .golangci.yml
  NOTICE.txt
  cmd/manager/main.go
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >enhancement, v1.1.0

#2737 Rename registry field as it clashes with ECS
  cmd/manager/main.go
Labels: >bug, v1.1.0

#2734 Ensure secret keys exist in Enterprise Search configuration
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/fixtures.go
  pkg/controller/enterprisesearch/name/name.go
Labels: >feature, v1.1.0

#2751 Set default namespace on Kibana e2e test requests
  test/e2e/test/kibana/http_client.go
Labels: >test

#2758 Add log adapter for automaxprocs
  cmd/manager/main.go
Labels: >non-issue

#2755 Close idle connections on the http client directly
  pkg/controller/elasticsearch/client/base.go
  pkg/controller/elasticsearch/client/client.go
Labels: >refactoring, v1.1.0

#2756 Make standalone Kibana e2e test compatible with api/status check
  test/e2e/kb/standalone_test.go
  test/e2e/kb/telemetry_test.go
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/http_client.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_kb.go
  test/e2e/test/kibana/http_client.go
Labels: :ci, >test

#2711 Add Google Cloud Load Balancer recipe
  config/recipes/gclb/00-prereq-cluster-issuer.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/02-ingress.yaml
  config/recipes/gclb/README.asciidoc
Labels: >docs

#2736 Label e2e runner, operator and stack pods for log correlation
  .ci/Makefile
  .ci/setenvconfig
  Makefile
  config/e2e/filebeat.yaml
  config/e2e/operator.yaml
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/test/apmserver/builder.go
  test/e2e/test/apmserver/steps_init.go
  test/e2e/test/context.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/steps_init.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/steps_init.go
  test/e2e/test/utils.go
Labels: :ci, >test

#2764 Fix remote cluster e2e test with 6.x
  test/e2e/es/remote_cluster_test.go
  test/e2e/test/elasticsearch/checks_data.go
Labels: >test

#2765 Update AKS version to current default
  hack/deployer/config/plans.yml
Labels: :ci, >test

#2769 Fix TestCustomConfiguration e2e test
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#2773 Fix labels on ES CA secret for Kibana association
  pkg/controller/kibanaassociation/association_controller.go
Labels: >bug, v1.1.0

#2774 Use ReconcileSecret for predefined users
  pkg/controller/elasticsearch/user/predefined.go
Labels: >refactoring, v1.1.0

#2772 Ensure that HTTP CA cert is always set
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: v1.1.0

#2750 Add retry library
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/cleanup-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-master-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  .ci/pipelines/pr-gke.Jenkinsfile
Labels: :ci

#2752 Add shellcheck to CI
  .ci/Dockerfile
  .ci/packer_cache.sh
  Makefile
  hack/api-docs/build.sh
  hack/check/check-license-header.sh
  hack/check/check-requisites.sh
  hack/dev/registry.sh
  hack/diagnostics/eck-dump.sh
  hack/kind/kind.sh
  hack/licence-detector/generate-image-deps.sh
  hack/licence-detector/generate-notice.sh
  hack/reattach-pv/integ-test-gke/run.sh
  test/e2e/run.sh
Labels: :ci

#2778 Improve e2e runner logs
  config/e2e/batch_job.yaml
  config/e2e/filebeat.yaml
Labels: :ci, >test

#2782 Remove unused int pointer utility
  pkg/utils/pointer/numeric.go
Labels: >refactoring

#2780 Run telemetry e2e tests and adjust for telemetry v2
  test/e2e/kb/telemetry_test.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#2729 Allow referencing K8s Secrets holding Enterprise Search configuration
  config/crds/all-crds.yaml
  config/crds/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/samples/enterprisesearch/entsearch_es.yml
  docs/reference/api-docs.asciidoc
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/zz_generated.deepcopy.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
Labels: >feature, v1.1.0

#2776 Add note about Minikube to Istio docs
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs

#2783 Rename pause annotation
  docs/operating-eck/troubleshooting.asciidoc
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserverelasticsearchassociation/apmserverelasticsearchassociation_controller.go
  pkg/controller/common/pause.go
  pkg/controller/common/pause_test.go
  pkg/controller/common/unmanaged.go
  pkg/controller/common/unmanaged_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/remotecluster/remoteca/controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/entsearchassociation/association_controller.go
  pkg/controller/kibana/kibana_controller.go
  pkg/controller/kibanaassociation/association_controller.go
  test/e2e/test/elasticsearch/pause.go
Labels: >enhancement

#2794 Improve secure string generation
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/common/association/user.go
  pkg/controller/common/labels.go
  pkg/controller/common/password.go
  pkg/controller/common/random.go
  pkg/controller/elasticsearch/user/predefined.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/kibana/config/reconciler.go
  pkg/controller/kibana/config/settings.go
  pkg/controller/kibana/config/settings_test.go
Labels: >enhancement, v1.1.0

#2784 Fix kind script
  hack/kind/kind.sh
Labels: :ci, >bug

#2781 Add validation webhook configurations for all resource types
  cmd/manager/main.go
  config/operator/all-in-one/webhook.template.yaml
  config/webhook/manifests.yaml
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/apis/apm/v1/zz_generated.deepcopy.go
  pkg/apis/apm/v1beta1/webhook.go
  pkg/apis/apm/v1beta1/webhook_test.go
  pkg/apis/apm/v1beta1/zz_generated.deepcopy.go
  pkg/apis/common/v1/validations.go
  pkg/apis/enterprisesearch/v1beta1/webhook.go
  pkg/apis/enterprisesearch/v1beta1/webhook_test.go
  pkg/apis/enterprisesearch/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1/webhook.go
  pkg/apis/kibana/v1/webhook_test.go
  pkg/apis/kibana/v1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1beta1/webhook.go
  pkg/apis/kibana/v1beta1/webhook_test.go
  pkg/apis/kibana/v1beta1/zz_generated.deepcopy.go
  pkg/controller/apmserver/apmserver_controller.go
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/common/version/version.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/kibana/kibana_controller.go
  pkg/utils/test/webhook.go
Labels: >enhancement, v1.1.0

#2790 Improve filebeat configuration to prevent losing last logs
  config/e2e/filebeat.yaml
  test/e2e/run.sh
Labels: :ci, >test
