Repository elastic/cloud-on-k8s, pull requests merged in 2020-06, with the labels that each got.

#3164 Add common problems section to documentation
  docs/operating-eck/troubleshooting.asciidoc
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  docs/operating-eck/troubleshooting/troubleshooting-methods.asciidoc
  docs/operating-eck/webhook.asciidoc
Labels: >docs

#3145 Add licence usage metrics
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/reporter.go
  pkg/license/reporter_test.go
  pkg/utils/metrics/metrics.go
Labels: >enhancement, v1.2.0

#3155 Introduce a restricted role for agent configuration
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/controller/association/controller/apm_kibana.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
Labels: >enhancement, v1.2.0

#3174 Add temporary logs to debug test failure
  pkg/controller/license/list.go
Labels: >test

#3169 [Backport] Add common problems section to troubleshooting doc (#3164)
  docs/operating-eck/troubleshooting.asciidoc
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  docs/operating-eck/troubleshooting/troubleshooting-methods.asciidoc
  docs/operating-eck/webhook.asciidoc
Labels: >docs, backport, v1.1.2

#3158 Add an info log on dev builds of ECK
  pkg/controller/common/license/check.go
  pkg/controller/common/license/check_test.go
Labels: >refactoring, justdoit

#3161 Switch to distroless
  Dockerfile
  docs/reference/container-image-dependencies.csv
  docs/reference/dependencies.asciidoc
  hack/licence-detector/templates/dependencies.asciidoc.tmpl
Labels: >enhancement, v1.2.0

#3121 Group renovate PRs
  .github/renovate.json
Labels: >renovate

#3179 Bump AKS k8s version
  hack/deployer/config/plans.yml
Labels: :ci, >test

#3184 Add APM/Kibana association e2e test
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  test/e2e/apm/association_test.go
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/apmserver/http_client.go
Labels: >test, v1.2.0

#3183 Improve trial extension e2e test
  pkg/controller/common/license/match.go
  test/e2e/es/license_test.go
  test/e2e/test/elasticsearch/license_fixture.go
Labels: >test

#3189 Reorder Kibana/APM declarations in sample
  config/samples/apm/apm_es_kibana.yaml
Labels: >test, v1.2.0

#3193 Set some resources for the keystore init container
  pkg/controller/apmserver/controller.go
  pkg/controller/common/keystore/initcontainer.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/elasticsearch/initcontainer/keystore.go
  pkg/controller/kibana/driver.go
Labels: >enhancement, v1.2.0

#3198 Add custom mappings for kubernetes_version and build_number
  config/e2e/filebeat.yaml
Labels: :ci, >test

#3206 Using host instead of node in the config
  pkg/controller/beat/filebeat/config.go
Labels: :beats, >bug

#3207 Skip Beat test if StackVersion is not supported
  test/e2e/beat/config_test.go
Labels: :beats, >bug

#3204 Add E2E tests for Enterprise Search
  config/samples/enterprisesearch/ent_es.yaml
  test/e2e/ent/association_test.go
  test/e2e/ent/configuration_test.go
  test/e2e/kb/keystore_test.go
  test/e2e/samples_test.go
  test/e2e/test/apmserver/builder.go
  test/e2e/test/beat/builder.go
  test/e2e/test/beat/pod_builder.go
  test/e2e/test/builder.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/enterprisesearch/builder.go
  test/e2e/test/enterprisesearch/checks_ent.go
  test/e2e/test/enterprisesearch/checks_k8s.go
  test/e2e/test/enterprisesearch/http_client.go
  test/e2e/test/enterprisesearch/steps_creation.go
  test/e2e/test/enterprisesearch/steps_deletion.go
  test/e2e/test/enterprisesearch/steps_init.go
  test/e2e/test/enterprisesearch/steps_mutation.go
  test/e2e/test/helper/yaml.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_k8s.go
  test/e2e/test/run.go
Labels: >test, v1.2.0

#3218 Update Elastic Stack to 7.7.1 and 6.8.10
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  Makefile
  config/e2e/filebeat.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/beats/1_monitor.yaml
  config/recipes/beats/2_filebeat-kubernetes.yaml
  config/recipes/beats/3_metricbeat-kubernetes.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/beat/filebeat_es_kibana_apm.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/test/version.go
Labels: :ci, >non-issue, justdoit

#3224 Add setting a builder
  test/e2e/test/helper/yaml.go
Labels: >bug, >test

#3222 Update Kubernetes version in API docs
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs

#3226 [Backport] Update Kubernetes version in API docs (#3222)
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs, backport, v1.1.2

#3195 Use _cluster/health API during rolling upgrades
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/esstate.go
  pkg/controller/elasticsearch/driver/esstate_test.go
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/driver/upgrade_predicates.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/license/apply.go
Labels: >enhancement, v1.2.0

#3167 Allow single-node clusters disruption in the default PDB
  pkg/controller/elasticsearch/pdb/reconcile.go
  pkg/controller/elasticsearch/pdb/reconcile_test.go
Labels: >enhancement, v1.2.0

#3211 Add KibanaRef to Beats and support setup.kibana
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/apis/common/v1/association.go
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/apm_es_test.go
  pkg/controller/association/controller/apm_kibana.go
  pkg/controller/association/controller/beat_es.go
  pkg/controller/association/controller/beat_kibana.go
  pkg/controller/beat/common/config.go
  pkg/controller/beat/common/config_test.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/health.go
  pkg/controller/beat/common/health_test.go
  pkg/controller/beat/common/pod.go
  pkg/controller/beat/common/reconcile.go
  pkg/controller/beat/controller.go
  pkg/controller/beat/filebeat/config.go
  pkg/controller/beat/filebeat/filebeat.go
  pkg/controller/beat/metricbeat/config.go
  pkg/controller/beat/metricbeat/metricbeat.go
  pkg/controller/beat/otherbeat/otherbeat.go
  pkg/controller/common/association/association.go
  pkg/controller/common/association/association_test.go
  pkg/controller/kibana/driver.go
Labels: :beats, >enhancement, v1.2.0

#3208 Add docs on copying objects with ownerrefs
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
Labels: >docs

#3235 Fix race condition when getting trial-status secret
  pkg/controller/common/license/check.go
Labels: >test, v1.2.0

#3233 Name transport service port
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/services/services_test.go
Labels: >enhancement, v1.2.0

#3229 Mention single-node clusters PDB exception in the docs
  docs/orchestrating-elastic-stack-applications/elasticsearch/pod-disruption-budget.asciidoc
Labels: >docs, v1.2.0

#3238 Fix typo in operator config doc
  docs/operating-eck/operator-config.asciidoc
Labels: >docs, v1.2.0

#3214 Remove config defaults and Beat RBAC management
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  config/e2e/beat-roles.yaml
  config/e2e/rbac.yaml
  config/operator/all-in-one/beat-roles.yaml
  config/operator/namespace/beat-roles.yaml
  config/samples/beat/filebeat_es_kibana_apm.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/controller/beat/common/autodiscover.go
  pkg/controller/beat/common/config.go
  pkg/controller/beat/common/config_test.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/health_test.go
  pkg/controller/beat/common/pod.go
  pkg/controller/beat/controller.go
  pkg/controller/beat/filebeat/config.go
  pkg/controller/beat/filebeat/filebeat.go
  pkg/controller/beat/metricbeat/config.go
  pkg/controller/beat/metricbeat/metricbeat.go
  pkg/controller/beat/otherbeat/otherbeat.go
  pkg/controller/common/operator/flags.go
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/cmd/run/run.go
  test/e2e/smoke_test.go
  test/e2e/test/beat/builder.go
  test/e2e/test/helper/yaml.go
Labels: :beats, >enhancement, v1.2.0

#3240 Do not rely on Go evaluation order quirks
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/client/v7.go
Labels: >refactoring, v1.2.0

#3246 Fix Beat TestSamples and otherbeat E2E tests
  pkg/controller/beat/otherbeat/otherbeat.go
  test/e2e/samples_test.go
Labels: :beats, >bug, >test

#3251 Adjust Beat builder to compensate for overwriting Beat struct
  test/e2e/smoke_test.go
  test/e2e/test/helper/yaml.go
Labels: :beats, >bug, >test

#3252 Fix comment spelling
  test/e2e/test/helper/yaml.go
Labels: triage

#3253 Remove overriding pod security context
  test/e2e/samples_test.go
Labels: triage

#3242 Add note about API keys requiring TLS
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs

#3220 Use a user with minimal set of permissions for Beat
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/validations.go
  pkg/apis/beat/v1beta1/validations_test.go
  pkg/apis/beat/v1beta1/webhook.go
  pkg/controller/association/controller/beat_es.go
  pkg/controller/association/controller/beat_es_test.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
Labels: :beats, >enhancement, v1.2.0

#3209 Add SecureSettings to Beat CRD
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/pod.go
  pkg/controller/beat/controller.go
  test/e2e/beat/config_test.go
  test/e2e/test/beat/builder.go
  test/e2e/test/helper/yaml.go
Labels: :beats, >feature, v1.2.0

#3258 Remove the install-roles make target
  Makefile
Labels: >bug

#3263 Add docs on copying objects with ownerrefs (#3208)
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
Labels: >docs, backport

#3210 Add ConfigRef to Beat CRD
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/validations.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/apis/common/v1/common.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
  pkg/controller/beat/common/config.go
  pkg/controller/beat/common/config_test.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/controller.go
  test/e2e/beat/config_test.go
  test/e2e/test/beat/builder.go
Labels: :beats, >feature

#3264 Add heartbeat driver
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/validations.go
  pkg/controller/beat/controller.go
  pkg/controller/beat/heartbeat/heartbeat.go
  pkg/controller/common/container/container.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
  test/e2e/beat/config_test.go
Labels: :beats, >enhancement

#3266 Remove whitelist references
  docs/advanced-topics/service-meshes.asciidoc
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  hack/licence-detector/README.md
Labels: >docs

#3256 Remove data dir from metricbeat recipe
  config/recipes/beats/3_metricbeat-kubernetes.yaml
Labels: >non-issue

#3270 Fix snapshot version in cleanup job
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: :ci, >bug

#3271 Wrap E2E tests http calls to stack APIs in test.Eventually
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/enterprisesearch/checks_ent.go
Labels: >flaky_test

#3260 Fix Ent Search hash computation when TLS is disabled
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
Labels: >bug, v1.2.0

#3185 Add docs for Enterprise Search in ECK
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
  docs/orchestrating-elastic-stack-applications/enterprise-search.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/quickstart.asciidoc
Labels: >docs, v1.2.0

#3212 Deploy metricbeat on e2e clusters
  config/e2e/batch_job.yaml
  config/e2e/filebeat.yaml
  config/e2e/metricbeat.yaml
  config/e2e/operator.yaml
  config/e2e/secret.yaml
  test/e2e/cmd/run/run.go
Labels: :ci, >test

#3115 Reduce number of git checkouts using stash/unstash
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  .ci/pipelines/pr-gke.Jenkinsfile
Labels: :ci, >test, justdoit

#3268 Move ValidateBeatSpec
  pkg/apis/beat/v1beta1/validations.go
  pkg/apis/beat/v1beta1/validations_test.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/driver_test.go
  pkg/controller/beat/common/reconcile.go
Labels: :beats, >refactoring, v1.2.0

#3275 Fix case of nodeset name in troubleshooting doc
  docs/operating-eck/troubleshooting/troubleshooting-methods.asciidoc
Labels: >docs, v1.2.0

#3281 Fix case of nodeset name in troubleshooting doc (#3275)
  docs/operating-eck/troubleshooting/troubleshooting-methods.asciidoc
Labels: >docs, backport

#3282 Suggest starting an ECK trial license in Enterprise Search docs
  docs/orchestrating-elastic-stack-applications/enterprise-search.asciidoc
Labels: >docs, v1.2.0

#3247 Consolidate the security-related sections
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/orchestrating-elastic-stack-applications/securing-stack.asciidoc
  docs/orchestrating-elastic-stack-applications/security/custom-http-certificate.asciidoc
  docs/orchestrating-elastic-stack-applications/security/rotate-credentials.asciidoc
  docs/orchestrating-elastic-stack-applications/security/users-and-roles.asciidoc
Labels: >docs

#3262 Minor edits on HTTP settings and TLS SANs
  docs/orchestrating-elastic-stack-applications/elasticsearch/http-settings-tls-sans.asciidoc
Labels: >docs

#3276 Add missing tests for the kibanaRef feature in Beats
  pkg/controller/association/controller/beat_kibana_test.go
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/beat/setup_test.go
  test/e2e/test/beat/builder.go
  test/e2e/test/kibana/http_client.go
Labels: >test, v1.2.0

#3279 Allow a single configRef to be specified in Enterprise Search
  config/crds/all-crds.yaml
  config/crds/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  docs/orchestrating-elastic-stack-applications/enterprise-search.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/common/v1/common.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/zz_generated.deepcopy.go
  pkg/controller/beat/common/config.go
  pkg/controller/beat/common/config_test.go
  pkg/controller/beat/controller.go
  pkg/controller/common/configref.go
  pkg/controller/common/configref_test.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  test/e2e/ent/configuration_test.go
  test/e2e/test/enterprisesearch/builder.go
Labels: >enhancement, v1.2.0

#3277 Fix Enterprise Search mounted volumes for restricted environments
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/pod.go
  test/e2e/ent/configuration_test.go
Labels: >bug, v1.2.0

#3300 Always change Beat health to red if none of pods are ready
  pkg/controller/beat/common/health.go
  pkg/controller/beat/common/health_test.go
Labels: :beats, >enhancement, v1.2.0

#3273 Only provision Enterprise licenses as of 7.8.1
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/common/license/match_test.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >bug, v1.2.0

#3301 Bump Elastic Stack version to 7.8.0
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  Makefile
  config/e2e/filebeat.yaml
  config/e2e/metricbeat.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/beats/1_monitor.yaml
  config/recipes/beats/2_filebeat-kubernetes.yaml
  config/recipes/beats/3_metricbeat-kubernetes.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/beat/filebeat_es_kibana_apm.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/test/version.go
Labels: >non-issue, v1.2.0

#3296 Bump CI deps
  .ci/Dockerfile
Labels: :ci, >non-issue

#3124 Add manifest generator
  Makefile
  config/operator/Makefile
  config/operator/README.md
  config/operator/all-in-one/cluster_role.template.yaml
  config/operator/all-in-one/cluster_role_bindings.template.yaml
  config/operator/all-in-one/namespace.template.yaml
  config/operator/all-in-one/operator.template.yaml
  config/operator/all-in-one/service_account.template.yaml
  config/operator/global/rbac.yaml
  config/operator/namespace/managed_ns_role_binding.template.yaml
  config/operator/namespace/namespace.template.yaml
  config/operator/namespace/operator.template.yaml
  config/operator/namespace/operator_ns_role_binding.template.yaml
  config/operator/namespace/rbac.yaml
  config/operator/namespace/service_account.template.yaml
  hack/manifest-gen/Dockerfile
  hack/manifest-gen/Makefile
  hack/manifest-gen/assets/charts/eck/.helmignore
  hack/manifest-gen/assets/charts/eck/Chart.yaml
  hack/manifest-gen/assets/charts/eck/crds/all-crds.yaml
  hack/manifest-gen/assets/charts/eck/profile-global.yaml
  hack/manifest-gen/assets/charts/eck/profile-restricted.yaml
  hack/manifest-gen/assets/charts/eck/templates/_helpers.tpl
  hack/manifest-gen/assets/charts/eck/templates/cluster-role.yaml
  hack/manifest-gen/assets/charts/eck/templates/managed-ns-role-bindings.yaml
  hack/manifest-gen/assets/charts/eck/templates/namespace.yaml
  hack/manifest-gen/assets/charts/eck/templates/operator-role-binding.yaml
  hack/manifest-gen/assets/charts/eck/templates/service-account.yaml
  hack/manifest-gen/assets/charts/eck/templates/statefulset.yaml
  hack/manifest-gen/assets/charts/eck/templates/webhook.yaml
  hack/manifest-gen/assets/charts/eck/values.yaml
  hack/manifest-gen/go.mod
  hack/manifest-gen/go.sum
  hack/manifest-gen/internal/manifest.go
  hack/manifest-gen/main.go
  hack/manifest-gen/manifest-gen.sh
Labels: >feature, release-highlight, v1.2.0

#3302 Ignore digest updates for golang.org/x/crypto
  .github/renovate.json
Labels: >renovate

#3295 Do not manage keystore if already initialized
  pkg/controller/apmserver/controller.go
  pkg/controller/beat/common/pod.go
  pkg/controller/common/keystore/initcontainer.go
  pkg/controller/common/keystore/resources.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/elasticsearch/initcontainer/keystore.go
  pkg/controller/kibana/driver.go
Labels: >bug, v1.2.0

#3304 Missing dots in doc annotations
  docs/advanced-topics/service-meshes.asciidoc
  docs/operating-eck/licensing.asciidoc
  docs/operating-eck/upgrading-eck.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/bundles-plugins.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
Labels: >docs

#3285 Add additional Kibana encryption keys
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
Labels: >enhancement, release-highlight, v1.2.0

#3267 Update licence detector allowlist name
  hack/licence-detector/generate-notice.sh
  hack/licence-detector/rules.json
Labels: >non-issue, v1.2.0

#3310 Add retries for docker build of the CI image
  .ci/Makefile
Labels: :ci, >flaky_test

#3314 Use the NodeAMI variable when creating an EKS cluster
  hack/deployer/runner/eks.go
Labels: :ci, >bug

#3315 Fix kibana saved object encryption keys pre-7.6.0
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
Labels: >bug, v1.2.0

#3313 Remove auditbeat config bit that is only supported on 7.7+
  test/e2e/beat/config.go
Labels: >bug, >test

#3316 Use eksctl AMIs auto resolver
  hack/deployer/config/plans.yml
Labels: :ci, >test

#3317 [1.2] Fix kibana saved object encryption keys pre-7.6.0 (#3315)
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
Labels: >bug, backport

#3320 Remove OPERATOR_IMAGE from ECK manifest
  hack/manifest-gen/assets/charts/eck/templates/statefulset.yaml
Labels: >non-issue

#3327 Fix beat webhook setup
  cmd/manager/main.go
  test/e2e/beat/webhook_test.go
Labels: :beats, >bug, exclude-from-release-notes, v1.2.0

#3331 Add Beat webhook to E2E yaml
  config/e2e/operator.yaml
Labels: :beats, >bug, >test

#3330 Disable Auditbeat E2E test on kind
  test/e2e/beat/config_test.go
Labels: :beats, >bug, >test, exclude-from-release-notes

#3323 Switch release notes tool to GitHub API v4
  hack/release-notes/README.md
  hack/release-notes/github/pr_loader.go
  hack/release-notes/github/pr_loader_test.go
  hack/release-notes/github/pr_processor.go
  hack/release-notes/github/pr_processor_test.go
  hack/release-notes/github/testdata/issue_body.txt
  hack/release-notes/github/testdata/payload1.json
  hack/release-notes/github/testdata/payload2.json
  hack/release-notes/go.mod
  hack/release-notes/go.sum
  hack/release-notes/main.go
  hack/release-notes/main_test.go
Labels: >docs, >enhancement

#3329 [1.2] Fix beat webhook setup #3327
  cmd/manager/main.go
  config/e2e/operator.yaml
  test/e2e/beat/webhook_test.go
Labels: >bug, backport

#3333 [1.2] Remove auditbeat config bit that is only supported on 7.7+ (#3313)
  test/e2e/beat/config.go
Labels: >bug, backport

#3334 [1.2] Disable Auditbeat E2E test on kind (#3330)
  test/e2e/beat/config_test.go
Labels: >bug, backport

#3335 Remove duplicated link to Transport settings
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
Labels: >docs

#3341 Add getting Beat/Ent resources and logs to eck-dump.sh
  hack/diagnostics/eck-dump.sh
Labels: :beats, >enhancement, backport

#3346 Fix operator memory limit regression
  hack/manifest-gen/assets/charts/eck/values.yaml
Labels: >non-issue, v1.2.0

#3345 [1.2] Add getting Beat resources and logs to eck-dump.sh (#3341)
  hack/diagnostics/eck-dump.sh
Labels: :beats, >enhancement, backport

#3347 [Backport] Fix operator memory limit regression (#3346)
  hack/manifest-gen/assets/charts/eck/values.yaml
Labels: >non-issue, backport, v1.2.0

#3311 Add upgrade test harness
  Makefile
  hack/upgrade-test-harness/.gitignore
  hack/upgrade-test-harness/README.md
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/config/config.go
  hack/upgrade-test-harness/fixture/alpha.go
  hack/upgrade-test-harness/fixture/eck.go
  hack/upgrade-test-harness/fixture/fixture.go
  hack/upgrade-test-harness/go.mod
  hack/upgrade-test-harness/go.sum
  hack/upgrade-test-harness/k8s/kubectl.go
  hack/upgrade-test-harness/main.go
  hack/upgrade-test-harness/run.sh
  hack/upgrade-test-harness/testdata/alpha/install.yaml
  hack/upgrade-test-harness/testdata/alpha/stack.yaml
  hack/upgrade-test-harness/testdata/beta/install.yaml
  hack/upgrade-test-harness/testdata/beta/stack.yaml
  hack/upgrade-test-harness/testdata/upcoming/stack.yaml
  hack/upgrade-test-harness/testdata/v101/install.yaml
  hack/upgrade-test-harness/testdata/v101/stack.yaml
  hack/upgrade-test-harness/testdata/v112/install.yaml
  hack/upgrade-test-harness/testdata/v112/stack.yaml
Labels: :ci, >test

#3325 Fix Beat E2E tests issues
  config/e2e/filebeat.yaml
  pkg/controller/association/controller/beat_es.go
  pkg/controller/association/controller/beat_es_test.go
  pkg/controller/association/controller/beat_kibana.go
  pkg/controller/association/controller/beat_kibana_test.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
  test/e2e/beat/config.go
Labels: :beats, >test

#3352 Fix Kibana version upgrade E2E tests
  test/e2e/kb/version_upgrade_test.go
Labels: >test

#3337 Disable checking http events in Packetbeat for kind 1.12
  test/e2e/beat/config_test.go
Labels: >bug, >test, backport

#3359 Update doc building command in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: >docs
