Repository elastic/cloud-on-k8s, pull requests merged in 2020-12, with the labels that each got.

#3897 Add support for multi-arch container images
  .ci/Dockerfile
  .ci/Makefile
  Dockerfile
  Makefile
  dev-setup.md
  hack/check/check-requisites.sh
  hack/docker.sh
  hack/manifest-gen/Makefile
  test/e2e/Dockerfile
Labels: :ci, >feature, v1.4.0

#3988 Fix broken link on beat.asciidoc
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
Labels: >docs

#3994 Fix broken link on beat.asciidoc (#3988)
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
Labels: >docs, backport

#4003 [Helm] Honour serviceAccount.create value
  deploy/eck-operator/templates/service-account.yaml
Labels: >bug, v1.3.1

#3993 Use the public transport CA as remote CA if the remote CA list is empty
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile_test.go
Labels: >bug, v1.3.1

#4007 [1.3.1] Use the public transport CA as remote CA if the remote CA list is empty (#3993)
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile.go
  pkg/controller/elasticsearch/certificates/remoteca/reconcile_test.go
Labels: >bug, backport, v1.3.1

#3992 Don't set an ownerRef on secrets users are susceptible to copy around
  cmd/manager/main.go
  cmd/manager/main_test.go
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/webhook.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/webhook.go
  pkg/apis/enterprisesearch/v1beta1/webhook_test.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1/webhook.go
  pkg/apis/kibana/v1/webhook_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/apmserver/pod_test.go
  pkg/controller/beat/controller.go
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/common/certificates/reconcile.go
  pkg/controller/common/certificates/reconcile_test.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/reconciler/secret.go
  pkg/controller/common/reconciler/secret_test.go
  pkg/controller/common/watches/secrets.go
  pkg/controller/common/watches/secrets_test.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/driver/pvc_expansion_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/user/predefined.go
  pkg/controller/elasticsearch/validation/webhook.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/utils/rbac/access_review_test.go
  test/e2e/test/apmserver/steps_deletion.go
  test/e2e/test/elasticsearch/steps_deletion.go
  test/e2e/test/enterprisesearch/steps_deletion.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/steps_deletion.go
Labels: >bug, v1.3.1

#4008 [1.3.1 Backport] Don't set an ownerRef on secrets users are susceptible to copy around…
  cmd/manager/main.go
  cmd/manager/main_test.go
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/webhook.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/webhook.go
  pkg/apis/enterprisesearch/v1beta1/webhook_test.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1/webhook.go
  pkg/apis/kibana/v1/webhook_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/apmserver/pod_test.go
  pkg/controller/beat/controller.go
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/common/certificates/reconcile.go
  pkg/controller/common/certificates/reconcile_test.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/common/reconciler/secret.go
  pkg/controller/common/reconciler/secret_test.go
  pkg/controller/common/watches/secrets.go
  pkg/controller/common/watches/secrets_test.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/driver/pvc_expansion_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/user/predefined.go
  pkg/controller/elasticsearch/validation/webhook.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/utils/rbac/access_review_test.go
  test/e2e/test/apmserver/steps_deletion.go
  test/e2e/test/elasticsearch/steps_deletion.go
  test/e2e/test/enterprisesearch/steps_deletion.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/steps_deletion.go
Labels: >bug, backport, v1.3.1

#4009 [1.3.1] [Helm] Honour serviceAccount.create value (#4003)
  deploy/eck-operator/templates/service-account.yaml
Labels: >bug, backport

#4019 Add 1.3.1 release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.3.1.asciidoc
  docs/release-notes/highlights-1.3.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v1.3.1

#4020 [1.3.1] Add 1.3.1 release notes (#4019)
  docs/release-notes.asciidoc
  docs/release-notes/1.3.1.asciidoc
  docs/release-notes/highlights-1.3.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: backport, triage

#3876 Add support for webhook constraints
  deploy/eck-operator/profile-soft-multi-tenancy.yaml
  deploy/eck-operator/templates/_helpers.tpl
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/templates/webhook.yaml
  deploy/eck-operator/values.yaml
  hack/manifest-gen/testdata/values.yaml
  pkg/controller/webhook/cert.go
  pkg/controller/webhook/reconcile.go
  pkg/controller/webhook/reconcile_test.go
  test/e2e/test/elasticsearch/steps_init.go
Labels: >enhancement, v1.4.0

#3964 [docs] Add pods not updating to common problems
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  docs/quickstart.asciidoc
Labels: >docs

#4010 Add Elastic Agent CRD (standalone mode)
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/bases/kustomization.yaml
  config/crds/patches/agent-patches.yaml
  config/crds/patches/kustomization.yaml
  config/dev/elastic-psp.yaml
  config/e2e/monitoring.yaml
  config/e2e/operator.yaml
  config/e2e/rbac.yaml
  config/e2e/roles.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  deploy/eck-operator/templates/_helpers.tpl
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/doc.go
  pkg/apis/agent/v1alpha1/groupversion_info.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/agent/config.go
  pkg/controller/agent/controller.go
  pkg/controller/agent/driver.go
  pkg/controller/agent/health.go
  pkg/controller/agent/labels.go
  pkg/controller/agent/name.go
  pkg/controller/agent/pod.go
  pkg/controller/agent/reconcile.go
  pkg/controller/association/controller/agent_es.go
  pkg/controller/common/container/container.go
  pkg/controller/common/controller.go
  pkg/controller/common/daemonset/reconcile.go
  pkg/controller/common/logging.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/common/tracing/error.go
  pkg/controller/common/tracing/spans.go
  pkg/controller/common/tracing/transaction.go
  pkg/controller/common/version/version.go
  pkg/utils/log/log.go
  test/e2e/agent/config.go
  test/e2e/agent/config_test.go
  test/e2e/cmd/run/run.go
  test/e2e/test/agent/builder.go
  test/e2e/test/agent/checks.go
  test/e2e/test/agent/steps.go
  test/e2e/test/k8s_client.go
Labels: >feature, elastic-agent, release-highlight, v1.4.0

#4031 Fix echo in CI Makefile
  .ci/Makefile
Labels: :ci, >non-issue

#4033 Disable full PR job
  .ci/jobs/pr-gke-full.yml
Labels: :ci, triage

#4032 [1.3] Fix echo in CI Makefile (#4031)
  .ci/Makefile
Labels: backport, triage

#4034 Bump minimal supported version of Elastic Agent to 7.10.0
  pkg/controller/common/version/version.go
Labels: >bug, >test, exclude-from-release-notes

#3965 Allow operatorhub tool to generate multiple packages
  hack/operatorhub/.gitignore
  hack/operatorhub/config.yaml
  hack/operatorhub/main.go
  hack/operatorhub/templates/csv.tpl
  hack/operatorhub/templates/package.tpl
Labels: >enhancement, exclude-from-release-notes

#4035 Add webhook for Agent controller
  cmd/manager/main.go
  config/webhook/manifests.yaml
  deploy/eck-operator/templates/webhook.yaml
  hack/docker.sh
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/validations.go
  pkg/apis/agent/v1alpha1/validations_test.go
  pkg/apis/agent/v1alpha1/webhook.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/agent/controller.go
  test/e2e/agent/webhook_test.go
Labels: >enhancement, >feature, exclude-from-release-notes, v1.4.0

#3952 OpenShift beats monitoring recipe
  config/recipes/beats/README.asciidoc
  config/recipes/beats/openshift_monitoring.yaml
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
Labels: >docs

#4044 Add agent webhook to e2e tests
  config/e2e/operator.yaml
Labels: :ci, >test, exclude-from-release-notes

#4030 Add Elastic Agent configuration examples
  config/recipes/elastic-agent/README.asciidoc
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/system-integration.yaml
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/samples_test.go
  test/e2e/test/agent/builder.go
  test/e2e/test/agent/checks.go
  test/e2e/test/agent/steps.go
  test/e2e/test/helper/yaml.go
Labels: >feature, elastic-agent, exclude-from-release-notes, v1.4.0

#4045 Add Agent usage reporting
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: >enhancement, elastic-agent, exclude-from-release-notes, v1.4.0

#4048 Fetch k8s version from cluster under E2E test
  .ci/setenvconfig
  Makefile
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
Labels: :ci, >non-issue, >test

#4046 Add Elastic Agent configRef E2E test
  test/e2e/agent/config_test.go
Labels: >test, elastic-agent, exclude-from-release-notes, v1.4.0

#4047 [1.3] OpenShift beats monitoring recipe (#3952)
  config/recipes/beats/README.asciidoc
  config/recipes/beats/openshift_monitoring.yaml
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
Labels: >docs, backport

#4049 Add support for DaemonSetUpdateStrategy
  config/crds/all-crds.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/patches/beat-patches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/controller/beat/common/reconcile.go
  pkg/controller/beat/common/reconcile_test.go
Labels: >enhancement, v1.4.0

#3864 Disable telemetry in E2E tests
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/stack_test.go
  test/e2e/test/kibana/builder.go
Labels: >non-issue

#4052 Don't duplicate user-provided Enterprise Search encryption keys when reusing them
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
  pkg/controller/enterprisesearch/fixtures.go
Labels: >bug, v1.4.0

#4041 Add a replacement mechanism to work around nil handling in ucfg
  pkg/apis/elasticsearch/v1/elasticsearch_config.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/common/settings/replace.go
  pkg/controller/common/settings/replace_test.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/label/label_test.go
  pkg/controller/elasticsearch/settings/canonical_config.go
  pkg/controller/elasticsearch/settings/config_volume.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  test/e2e/es/topology_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_es.go
Labels: >bug, v1.4.0

#4023 Avoid touching root filesystem in Kibana init script
  pkg/controller/kibana/init_configuration.go
Labels: >bug, v1.4.0

#4057 Add admissionReviewVersions for Agent webhook if k8s > 1.16
  deploy/eck-operator/templates/webhook.yaml
Labels: >bug, exclude-from-release-notes

#4056 Add missing permissions to E2E runner role for Elastic Agent tests
  config/e2e/rbac.yaml
Labels: >bug, >test

#4058 Support Elastic Agent in eck-dump.sh
  hack/diagnostics/eck-dump.sh
Labels: >enhancement, elastic-agent, exclude-from-release-notes, v1.4.0

#4059 Re-enable Kibana telemetry for telemetry test
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
  test/e2e/kb/telemetry_test.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_kb.go
  test/e2e/test/kibana/checks_telemetry.go
  test/e2e/test/kibana/http_client.go
Labels: :ci, >test

#4053 Add support for a user-defined transport CA certificate and key
  config/crds/all-crds.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/controller/common/certificates/ca_secret.go
  pkg/controller/common/certificates/ca_secret_test.go
  pkg/controller/common/certificates/dynamic_watches.go
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/secret.go
  pkg/controller/common/certificates/secret_test.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/ca.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  test/e2e/es/certs_test.go
  test/e2e/test/builder.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_es.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/checks_transport.go
Labels: >enhancement, v1.4.0

#4063 Allow handshake erros during transport TLS cert check
  test/e2e/es/certs_test.go
  test/e2e/test/elasticsearch/checks_transport.go
Labels: >test

#4064 E2E test validate peer certificate chain during TLS handshake
  test/e2e/es/certs_test.go
  test/e2e/test/elasticsearch/checks_transport.go
Labels: :ci, >test

#4066 Do not touch telemetry settings in e2e tests
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
  test/e2e/kb/telemetry_test.go
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/stack_test.go
  test/e2e/test/kibana/builder.go
  test/e2e/test/kibana/checks_kb.go
Labels: >test
