Repository elastic/cloud-on-k8s, pull requests merged in 2020-05, with the labels that each got.

#3022 Fix trial extension e2e
  .ci/setenvconfig
  test/e2e/es/license_test.go
Labels: :ci

#3020 Add PodTemplate semantic validation for Elasticsearch
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  pkg/controller/common/reconciler/reconciler.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/settings/masters.go
  pkg/controller/elasticsearch/sset/reconcile.go
  pkg/controller/elasticsearch/sset/validation.go
  pkg/controller/elasticsearch/sset/validation_test.go
  test/e2e/es/podtemplate_test.go
Labels: >enhancement, v1.2.0

#3030 Cleanup license after e2e trial extension test
  test/e2e/es/license_test.go
  test/e2e/es/remote_cluster_test.go
Labels: >test

#3035 Restore transport certs public secret naming scheme from 1.0
  pkg/controller/common/certificates/secret.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
Labels: >bug, v1.1.1

#3039 Backport - Restore transport certs public secret name (#3035)
  pkg/controller/common/certificates/secret.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
Labels: backport, v1.1.1

#3045 Bump version to 1.1.1
  VERSION
Labels: >non-issue, v1.1.1

#3046 Increase the operator default memory requirements
  config/e2e/operator.yaml
  config/operator/all-in-one/operator.template.yaml
Labels: >enhancement, v1.1.1

#3047 Add release notes and release highlights for 1.1.1
  docs/release-notes/1.1.1.asciidoc
  docs/release-notes/highlights-1.1.1.asciidoc
Labels: >docs, v1.1.1

#3053 Fix incorrectly rendered update strategy doc
  docs/orchestrating-elastic-stack-applications/elasticsearch/update-strategy.asciidoc
Labels: >docs

#3048 Bump dependencies
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/licence-detector/overrides/licences/github.com/miekg/dns/LICENSE
  hack/licence-detector/overrides/overrides.json
Labels: >refactoring, v1.2.0

#2901 Use a single Docker registry
  .ci/Makefile
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/e2e-tests-eks.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/setenvconfig
  .gitignore
  Makefile
  dev-setup.md
  hack/deployer/README.md
  hack/deployer/cmd/create.go
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/settings.go
  hack/docker-push.sh
Labels: :ci, justdoit

#3060 Revert "Make readiness probes independent of the host/container... (#2528)
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/apmserver/pod.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/pod.go
Labels: >breaking, v1.1.1

#3063 Bump version to 1.2.0
  VERSION
Labels: >non-issue, v1.2.0

#3062 Revert "Make readiness probes independent of the host/container... (#2528) #3060
  pkg/controller/apmserver/apmserver_controller_test.go
  pkg/controller/apmserver/pod.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/pod/pod.go
Labels: >breaking, backport, v1.1.1

#2985 Whitelist renovate
  .ci/jobs/pr-gke.yml
  .github/renovate.json
  renovate.json
Labels: :ci

#3068 Run go mod tidy before generating notice
  Makefile
Labels: :ci, >enhancement

#3057 Add doc section about Istio CNI
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs

#3069 Bump Elastic Stack versions
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  Makefile
  config/e2e/filebeat.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/beats/1_monitor.yaml
  config/recipes/beats/2_filebeat-kubernetes.yaml
  config/recipes/beats/3_metricbeat-kubernetes.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yml
  config/samples/kibana/kibana_es.yaml
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/test/version.go
Labels: >test

#3061 Update breaking changes in 1.1.0
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: >docs, v1.1.0

#3071 Update breaking changes in 1.1.0 (#3061)
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/highlights-1.1.0.asciidoc
Labels: >docs, backport, v1.1.0

#3072 Add doc section about Istio CNI (#3057)
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs, backport, v1.1.0

#3067 Regenerate release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.1.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v1.1.1

#3075 Backport regenerate release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.1.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport, v1.1.1

#3076 Clarify 1.1.1 release highlights
  docs/release-notes/highlights-1.1.1.asciidoc
Labels: >bug, v1.1.1

#3077 Bump docs ECK version
  docs/eck-attributes.asciidoc
Labels: >docs, v1.1.1

#3079 Bump docs ECK version (#3077)
  docs/eck-attributes.asciidoc
Labels: >docs, backport

#3078 Clarify 1.1.1 release highlights (#3076)
  docs/release-notes/highlights-1.1.1.asciidoc
Labels: >docs, backport

#3080 Fix 1.1.1 highlights
  docs/release-notes/highlights-1.1.1.asciidoc
Labels: >docs, v1.1.1

#3081 Fix 1.1.1 highlights (#3080)
  docs/release-notes/highlights-1.1.1.asciidoc
Labels: >docs, backport

#3073 Delete deprecated e2e-tests-custom-operator-image job
  .ci/jobs/e2e-tests-custom-operator-image-gke.yml
  .ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
Labels: :ci, >non-issue, justdoit

#3085 Remove the tmp testdeleteservices Jenkins job
  .ci/jobs/e2e-tests-testdeleteservices.yml
  .ci/pipelines/e2e-tests-testdeleteservices.Jenkinsfile
Labels: >flaky_test

#3087 Workaround TestDeleteServices flakiness by not checking the endpoints
  test/e2e/es/failure_test.go
Labels: >flaky_test

#3083 Do not propagate Elasticsearch CA if none is provided
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
Labels: >bug, v1.2.0

#3089 Update kind and kind nodes versions
  .ci/Dockerfile
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
Labels: :ci, >non-issue

#3084 Avoid overwriting default IPFamily of services
  pkg/controller/common/service_control.go
  pkg/controller/common/service_control_test.go
Labels: >bug, v1.2.0

#3011 Add port to STS headless service
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
Labels: >enhancement, v1.2.0

#3091 Sort Kinds in API docs
  hack/api-docs/build.sh
  hack/api-docs/templates/gv_details.tpl
Labels: :ci, >docs

#3098 Fix Kibana certs secret labels
  pkg/controller/kibana/driver.go
Labels: >bug, v1.1.2

#3100 Backport - Fix Kibana certs secret labels
  pkg/controller/kibana/driver.go
Labels: >bug, backport, v1.1.2

#3099 Do not propagate Elasticsearch CA if none is provided (#3083)
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
Labels: >bug, backport, v1.1.2

#3102 Avoid overwriting default IPFamily of services (#3084)
  pkg/controller/common/service_control.go
  pkg/controller/common/service_control_test.go
Labels: >bug, backport, v1.1.2

#3092 Bump CI deps
  .ci/Dockerfile
  .golangci.yml
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  hack/check/check-requisites.sh
  hack/deployer/cmd/create.go
  hack/deployer/runner/eks.go
  hack/deployer/runner/ocp.go
  hack/deployer/runner/vault.go
  hack/kind/kind.sh
  pkg/controller/apmserver/config.go
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/association/resources_test.go
  pkg/controller/association/user_test.go
  pkg/controller/common/certificates/secret.go
  pkg/controller/common/http_client.go
  pkg/controller/common/license/trial.go
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/sset/pod.go
  pkg/dev/portforward/service_forwarder.go
  pkg/license/license.go
  test/e2e/es/remote_cluster_test.go
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/command/command.go
  test/e2e/test/elasticsearch/checks_data.go
Labels: >refactoring

#3103 Add renovate label to PRs
  .github/renovate.json
Labels: >renovate

#3105 Use docker.elastic.co rather than push.docker.elastic.co
  .ci/Makefile
  dev-setup.md
  hack/docker-push.sh
Labels: :ci, >non-issue

#3107 Remove warning about running APMServer and ES in different namespaces
  docs/orchestrating-elastic-stack-applications/apm-server.asciidoc
Labels: >docs, v1.0.0

#3109 Backport 1.1 - Remove warning about APMServer and ES in different namespaces (#3107)
  docs/orchestrating-elastic-stack-applications/apm-server.asciidoc
Labels: >docs, backport, v1.1.0

#3108 Backport 1.0 - Remove warning about APMServer and ES in different namespaces (#3107)
  docs/apm-server.asciidoc
Labels: >docs, backport, v1.0.0

#3093 Add E2E tests to cover breaking changes on secrets and services
  test/e2e/test/apmserver/checks_k8s.go
  test/e2e/test/apmserver/steps_deletion.go
  test/e2e/test/checks.go
  test/e2e/test/elasticsearch/checks_k8s.go
  test/e2e/test/elasticsearch/steps_deletion.go
  test/e2e/test/k8s_client.go
  test/e2e/test/kibana/checks_k8s.go
  test/e2e/test/kibana/steps_deletion.go
Labels: >test

#3101 Fix remote cluster annotation handling
  pkg/controller/elasticsearch/remotecluster/annotations.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch_test.go
Labels: >bug, v1.1.2

#3111 [Backport] Fix remote cluster annotation handling (#3101)
  pkg/controller/elasticsearch/remotecluster/annotations.go
  pkg/controller/elasticsearch/remotecluster/elasticsearch_test.go
Labels: >bug, backport, v1.1.2

#3114 Remove duplicate checkout
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-eks.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
Labels: :ci, >refactoring

#3113 Dynamic branch specifier for E2E tests jobs
  .ci/jobs/e2e-tests-aks.yml
  .ci/jobs/e2e-tests-eks.yml
  .ci/jobs/e2e-tests-gke-k8s-versions.yml
  .ci/jobs/e2e-tests-kind-k8s-versions.yml
  .ci/jobs/e2e-tests-ocp.yaml
  .ci/jobs/e2e-tests-stack-versions-gke.yml
  .ci/pipelines/build.Jenkinsfile
Labels: :ci, >test

#3116 Increase the days to keep builds in history
  .ci/jobs/defaults.yml
Labels: :ci, >test, justdoit

#3117 Add retries for docker push
  .ci/Makefile
  hack/docker-push.sh
  hack/retry.sh
Labels: :ci, >flaky_test

#3123 Make E2E tests bootstrap more resilient
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
Labels: >flaky_test

#3135 Remove the OPERATOR_IMAGE env var from ECK manifest
  config/e2e/operator.yaml
  config/operator/all-in-one/operator.template.yaml
  config/operator/namespace/operator.template.yaml
Labels: >refactoring

#2900 Fix GCloud auth to work on CI
  hack/deployer/config/plans.yml
  hack/deployer/runner/ocp.go
  hack/deployer/runner/settings.go
Labels: :ci

#3136 Use Enterprise Search default Docker image
  config/samples/enterprisesearch/ent_es.yml
  pkg/controller/common/container/container.go
Labels: >enhancement, v1.2.0

#3137 Temporarily disable Slack notifications for 7.8.0-SNAPSHOT failures
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: :ci, >flaky_test

#3142 Add a command to enable ECK APM tracing in dev-setup.md
  dev-setup.md
Labels: >docs

#3138 Docs: use node.remote_cluster_client in examples
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/node-configuration.asciidoc
Labels: >docs

#3125 Add 1.1.2 release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/1.1.2.asciidoc
  docs/release-notes/highlights-1.1.2.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v1.1.2

#3146 Add 1.1.2 release notes (#3125)
  docs/release-notes.asciidoc
  docs/release-notes/1.1.0.asciidoc
  docs/release-notes/1.1.2.asciidoc
  docs/release-notes/highlights-1.1.2.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport

#3149 Preserve extra annotations and labels on StatefulSet updates
  pkg/controller/elasticsearch/sset/reconcile.go
  pkg/controller/elasticsearch/sset/reconcile_test.go
Labels: >bug, v1.2.0

#3043 Add support for the APM Agent Config Management
  cmd/manager/main.go
  config/crds/all-crds.yaml
  config/crds/bases/apm.k8s.elastic.co_apmservers.yaml
  config/samples/apm/apm_es_kibana.yaml
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/apis/apm/v1/zz_generated.deepcopy.go
  pkg/apis/common/v1/association.go
  pkg/apis/common/v1/validations.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/controller/apmserver/config.go
  pkg/controller/apmserver/config_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/deployment.go
  pkg/controller/apmserver/deployment_test.go
  pkg/controller/association/ca.go
  pkg/controller/association/ca_test.go
  pkg/controller/association/conf.go
  pkg/controller/association/conf_test.go
  pkg/controller/association/controller.go
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/apm_kibana.go
  pkg/controller/association/controller/ent_es.go
  pkg/controller/association/controller/kibana_es.go
  pkg/controller/association/dynamic_watches.go
  pkg/controller/association/fixtures.go
  pkg/controller/association/rbac.go
  pkg/controller/association/rbac_test.go
  pkg/controller/association/reconciler.go
  pkg/controller/association/reconciler_test.go
  pkg/controller/association/resources.go
  pkg/controller/association/resources_test.go
  pkg/controller/association/user.go
  pkg/controller/common/annotation/association.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  pkg/controller/kibana/controller.go
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/test/apmserver/builder.go
  test/e2e/test/kibana/builder.go
Labels: >enhancement, v1.2.0

#3151 Revert "Temporarily disable Slack notifications for 7.8.0-SNAPSHOT failures (#3137)"
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: >flaky_test

#3150 Do not stop running trial even when ECK not in trial mode
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/elasticsearch/license/apply_test.go
Labels: >enhancement, v1.2.0

#3126 Switch default docs version to 1.1.2
  VERSION
  docs/eck-attributes.asciidoc
  docs/release-notes/highlights-1.1.2.asciidoc
Labels: >docs, v1.1.2

#3157 Do not assume docker-push.sh is always run from repo root
  hack/docker-push.sh
Labels: :ci, >bug

#3165 Replace the license observer by a sync call in the reconciliation
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/license/apply.go
  pkg/controller/elasticsearch/license/apply_test.go
  pkg/controller/elasticsearch/license/reconcile.go
  pkg/controller/elasticsearch/observer/state.go
  pkg/controller/elasticsearch/observer/state_test.go
Labels: >bug, v1.2.0
