Repository elastic/cloud-on-k8s, pull requests merged in 2021-12, with the labels that each got.

#5076 Bump Stack version to 7.15.2
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/journalbeat_hosts.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems-es.yaml
  config/recipes/maps/02-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  hack/operatorhub/config.yaml
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/stack_test.go
  test/e2e/test/version.go
Labels: >non-issue, v2.0.0

#5085 Stop using Enterprise Search deprecated setting in 7.17
  pkg/controller/enterprisesearch/config.go
Labels: >enhancement, v1.9.0

#5104 [1.9] Stop using deprecated setting earlier (#5085)
  pkg/controller/enterprisesearch/config.go
Labels: >enhancement, backport

#5068 Add note to plugin documentation about using Istio and init containers.
  docs/orchestrating-elastic-stack-applications/elasticsearch/bundles-plugins.asciidoc
Labels: >docs

#5106 Main go routine does not exit if there's no error
  cmd/manager/main.go
Labels: >bug, v2.0.0

#5110 [1.9] Fix broken link affecting MS-64 (#4974)
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs, backport

#5108 Update fleet custom logs integration recipe in 7.15.1
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
Labels: >bug, >test

#5101 Add downward node labels api to telemetry
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  pkg/telemetry/fixtures.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: >enhancement, exclude-from-release-notes, v2.0.0

#5109 Set enterprise search config kibana.host defaults in advance of 8.0
  docs/orchestrating-elastic-stack-applications/enterprise-search.asciidoc
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
Labels: >enhancement, v2.0.0

#5118 Stop using deprecated xpack.monitoring.* settings from 8.0.0
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/stackmon/es_config.go
Labels: >refactoring, v1.9.0

#5119 [1.9] Stop using deprecated xpack.monitoring.* settings from 8.0 (#5118)
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/stackmon/es_config.go
Labels: backport, triage

#5120 [DOCS] Hardcoded broken cross-doc links for 7.16 release.
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, v1.5.0, v1.4.1, v1.6.0, v1.8.0, v1.7.1, v1.9.0, v2.0.0

#5103 Release documentation improvements
  docs/operating-eck/operator-config.asciidoc
  docs/operating-eck/upgrading-eck.asciidoc
  docs/release-notes/1.9.0.asciidoc
Labels: >docs, v1.9.0

#5123 [DOCS] Hardcoded broken cross-doc links for 7.16 release. (#5120)
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5128 [DOCS] Hardcoded broken cross-doc links for 7.16 release
  docs/orchestrating-elastic-stack-applications/agent.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5127 [DOCS] Hardcoded broken cross-doc links for 7.16 release
  docs/orchestrating-elastic-stack-applications/agent.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5126 [DOCS] Hardcoded broken cross-doc links for 7.16 release
  docs/orchestrating-elastic-stack-applications/agent.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5125 [DOCS] Hardcoded broken cross-doc links for 7.16 release. (#5120)
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5124 [DOCS] Hardcoded broken cross-doc links for 7.16 release. (#5120)
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5122 Add kibana.host setting only to Enterprise Search 7.15
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
Labels: >bug, v1.9.0

#5130 [1.9] Release documentation improvements (#5103)
  docs/operating-eck/operator-config.asciidoc
  docs/operating-eck/upgrading-eck.asciidoc
  docs/release-notes/1.9.0.asciidoc
Labels: >docs, backport

#5132 [1.9] Add kibana.host setting only to Enterprise Search 7.15 (#5122)
  pkg/controller/enterprisesearch/config.go
Labels: >bug, backport

#5131 [DOCS] Fixed cross doc link.
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, v1.4.0, v1.5.0

#5133 [DOCS] Fixed cross doc link. (#5131)
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5134 [DOCS] Fixed cross doc link. (#5131)
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs, backport

#5136 Stop using deprecated xpack.monitoring.* settings
  config/recipes/beats/stack_monitoring.yaml
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
  pkg/controller/elasticsearch/stackmon/es_config.go
Labels: >refactoring, v1.9.0

#5135 Revert "Add kibana.host setting only to Enterprise Search 7.15 (#5122)
  pkg/controller/enterprisesearch/config.go
Labels: >bug

#5137 [1.9] Stop using deprecated xpack.monitoring.* settings (#5136)
  config/recipes/beats/stack_monitoring.yaml
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/resources.go
  pkg/controller/elasticsearch/settings/merged_config.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
  pkg/controller/elasticsearch/stackmon/es_config.go
Labels: backport, >refactoring

#5139 Bump docs ECK version and branch to 1.9.0 and 1.9 respectively
  docs/eck-attributes.asciidoc
Labels: >non-issue

#5121 [DOCS] Switched hardcoded 7.16 links to current
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/release-notes/highlights-1.4.0.asciidoc
Labels: >docs

#5142 Bump OLM/upgrade-test configs to 1.9.0
  hack/operatorhub/config.yaml
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v190/crds.yaml
  hack/upgrade-test-harness/testdata/v190/install.yaml
  hack/upgrade-test-harness/testdata/v190/stack.yaml
Labels: >non-issue

#5153 [1.8] Undo accidentally committed file config/all-in-one.yml
  config/all-in-one.yaml
Labels: >non-issue, v1.8.0

#5152 [1.7] Undo accidentally committed file config/all-in-one.yml
  config/all-in-one.yaml
Labels: >non-issue, v1.7.0

#5154 [1.9] Undo accidentally committed file config/all-in-one.yml
  config/all-in-one.yaml
Labels: >non-issue, v1.9.0

#5157 Add log4j2.formatMsgNoLookups logging property to ES < 7.12
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
Labels: >enhancement

#5072 Introduce orchestration hints as a way to gate orchestration features
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/node_shutdown.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/hints/hints.go
  pkg/controller/elasticsearch/hints/hints_test.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/reconcile/state.go
  pkg/controller/elasticsearch/reconcile/state_test.go
Labels: >enhancement

#5129 Add internal product header to requests
  pkg/controller/common/http.go
  pkg/controller/elasticsearch/client/base.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >enhancement, v2.0.0

#5160 E2E: Include nodeSet name in topology comparison
  test/e2e/test/elasticsearch/checks_es.go
Labels: :ci, >test

#5158 Resource aggregator should handle missing memory settings
  pkg/license/aggregator.go
  pkg/license/aggregator_test.go
Labels: >bug

#5097 Support trial licenses inside enterprise_trial orchestration licenses
  pkg/controller/common/license/match_test.go
  pkg/controller/elasticsearch/license/apply.go
  test/e2e/es/license_test.go
  test/e2e/test/elasticsearch/license_fixture.go
  test/e2e/test/elasticsearch/steps_license.go
Labels: >enhancement, v2.0.0

#5162 [DOCS] Remove unneeded backtick from code snippet
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs

#5167 [1.9.1-wip] Update golang Docker tag to v1.17.5 (#5149)
  .ci/Dockerfile
  Dockerfile
  hack/manifest-gen/Dockerfile
  test/e2e/Dockerfile
Labels: backport, >renovate

#5164 [1.9.1-wip] Configure JVM logging for ES < 7.12 to mitigate Log4Shell vulnerability CVE-2021-44228 (#5157)
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
Labels: >enhancement, backport

#5165 [1.9.1-wip] Add internal product header to requests (#5129)
  pkg/controller/common/http.go
  pkg/controller/elasticsearch/client/base.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/nodespec/readiness_probe.go
Labels: >enhancement, backport

#5166 [1.9.1-wip] Resource aggregator should handle missing memory settings (#5158)
  pkg/license/aggregator.go
  pkg/license/aggregator_test.go
Labels: >bug, backport

#5174 Add 1.9.1 release notes
  docs/release-notes.asciidoc
  docs/release-notes/1.9.0.asciidoc
  docs/release-notes/1.9.1.asciidoc
  docs/release-notes/highlights-1.9.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs

#5179 [1.9.1-wip] Add 1.9.1 release notes (#5174)
  docs/release-notes.asciidoc
  docs/release-notes/1.9.0.asciidoc
  docs/release-notes/1.9.1.asciidoc
  docs/release-notes/highlights-1.9.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport

#5176 Include documentation improvements in the release notes
  hack/release-notes/main.go
Labels: >non-issue

#5178 Add missing nodes resource RBAC permission in recipes
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/openshift_monitoring.yaml
Labels: >bug, >docs

#5180 Bump ECK version in docs to 1.9.1
  docs/eck-attributes.asciidoc
Labels: >non-issue

#5183 Update upgrade harness testdata after 1.9.1 release
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v191/crds.yaml
  hack/upgrade-test-harness/testdata/v191/install.yaml
  hack/upgrade-test-harness/testdata/v191/stack.yaml
Labels: >non-issue

#5113 Stop using deprecated host field in Beat configs
  config/e2e/monitoring.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/common/v1/common.go
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
Labels: >enhancement, v2.0.0

#5192 Update 1.9.x release highlights concerning Webhook issues in Openshift <= 4.6
  docs/release-notes/highlights-1.9.0.asciidoc
  docs/release-notes/highlights-1.9.1.asciidoc
Labels: >docs

#5193 [1.9] Update 1.9.x release highlights concerning Webhook issues in Openshift <= 4.6 (#5192)
  docs/release-notes/highlights-1.9.0.asciidoc
  docs/release-notes/highlights-1.9.1.asciidoc
Labels: triage

#5194 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >bug, >docs, v0.9.0, v1.1.2, v1.5.0, v1.3.2, v1.2.2, v1.4.1, v1.6.0, v1.8.0, v1.7.1, v1.9.0

#5197 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5198 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5199 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5200 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5201 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5202 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5204 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5206 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5207 [DOCS] Fix cross-doc links
  docs/advanced-topics/custom-images.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, backport

#5195 [DOCS] Fix cross-doc links
  docs/custom-images.asciidoc
  docs/snapshots.asciidoc
Labels: >docs, backport

#5196 [DOCS] Fix cross-doc links
  docs/custom-images.asciidoc
  docs/snapshots.asciidoc
Labels: >docs, backport

#5203 [DOCS] Fix cross doc link
  docs/snapshots.asciidoc
Labels: >docs, backport
