Repository elastic/cloud-on-k8s, pull requests merged in 2021-01, with the labels that each got.

#4073 Update copyright notice for 2021
  NOTICE.txt
Labels: >non-issue

#4026 Update Kubernetes API version used in docs
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs, v1.4.0

#4075 Update Kubernetes version for EKS to 1.17
  hack/deployer/config/plans.yml
Labels: :ci, >test

#4081 Fix Dockerfile to build the right executable for ARM
  Dockerfile
Labels: >bug, v1.4.0

#4079 Update versions for 1.4 release
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  docs/eck-attributes.asciidoc
Labels: >non-issue, v1.4.0

#4082 [Backport] Fix Dockerfile to build the right executable for ARM (#4081)
  Dockerfile
Labels: >bug, backport, v1.4.0

#4080 Update VERSION to 1.5.0-SNAPSHOT
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
Labels: >non-issue

#4086 Make Association status serialization backward compatible
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/common/v1/association.go
  pkg/apis/common/v1/association_test.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/controller/association/reconciler.go
  test/e2e/apm/association_test.go
  test/e2e/kb/association_test.go
Labels: >bug, elastic-agent

#4088 [1.4] Make Association status serialization backward compatible (#4086)
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/common/v1/association.go
  pkg/apis/common/v1/association_test.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/controller/association/reconciler.go
  test/e2e/apm/association_test.go
  test/e2e/kb/association_test.go
Labels: >bug, backport, elastic-agent, exclude-from-release-notes

#4091 Increase integration/unit test timeout to 10 seconds
  pkg/utils/test/retry.go
Labels: :ci, >test

#4090 Update kind tests to close gaps in test matrix
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
Labels: :ci, >test

#4078 Add a doc section about stuck master scale down in ES <= 7.8
  docs/operating-eck/troubleshooting/common-problems.asciidoc
Labels: >docs

#4094 [1.4] Add a doc section about stuck master scale down in ES <= 7.8 (#4078)
  docs/operating-eck/troubleshooting/common-problems.asciidoc
Labels: backport, triage

#4097 Update client-go to 0.18.14
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >bug, v1.4.0

#4100 Disable k8s apiserver and event data stream checks for Agent e2e tests
  test/e2e/agent/recipes_test.go
Labels: :ci, >test

#4101 [1.4] Update client-go to 0.18.14 (#4097)
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >bug, backport

#4102 [1.4] Disable k8s apiserver and event data stream checks for Agent e2e tests (#4100)
  test/e2e/agent/recipes_test.go
Labels: :ci, >test, backport

#4103 Update crd-ref-docs version
  docs/reference/api-docs.asciidoc
  hack/api-docs/build.sh
Labels: 1.5.0, >docs

#4105 [Backport] Update crd-ref-docs version (#4103)
  docs/reference/api-docs.asciidoc
  hack/api-docs/build.sh
Labels: >docs, backport, v1.4.0

#4095 Update maxSurge setting description
  docs/orchestrating-elastic-stack-applications/elasticsearch/update-strategy.asciidoc
Labels: >docs

#4110 Add finalizer RBAC for Elastic Agent
  config/e2e/monitoring.yaml
  config/e2e/operator.yaml
  deploy/eck-operator/templates/_helpers.tpl
Labels: >bug, exclude-from-release-notes, v1.4.0

#4111 [1.4] Add finalizer RBAC for Elastic Agent (#4110)
  config/e2e/monitoring.yaml
  config/e2e/operator.yaml
  deploy/eck-operator/templates/_helpers.tpl
Labels: backport, triage

#4113 Allow non-root user to run Elastic Agent process
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/system-integration.yaml
  pkg/controller/agent/pod.go
  test/e2e/agent/config.go
Labels: >bug, exclude-from-release-notes, v1.4.0

#4115 Rename DaemonSetSpec strategy to updateStrategy
  config/crds/all-crds.yaml
  config/crds/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/patches/agent-patches.yaml
  config/crds/patches/beat-patches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/controller/agent/reconcile.go
  pkg/controller/beat/common/reconcile.go
  pkg/controller/beat/common/reconcile_test.go
Labels: >enhancement, exclude-from-release-notes, v1.4.0

#4096 Update JVM Heap Size section
  docs/orchestrating-elastic-stack-applications/elasticsearch/jvm-heap-size.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
Labels: >docs

#4120 [1.4] Rename DaemonSetSpec strategy to updateStrategy (#4115)
  config/crds/all-crds.yaml
  config/crds/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/patches/agent-patches.yaml
  config/crds/patches/beat-patches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/controller/agent/reconcile.go
  pkg/controller/beat/common/reconcile.go
  pkg/controller/beat/common/reconcile_test.go
Labels: >enhancement, backport

#4114 [1.4] Allow non-root user to run Elastic Agent process (#4113)
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/system-integration.yaml
  pkg/controller/agent/pod.go
  test/e2e/agent/config.go
Labels: >bug, backport

#3996 Bring license signer in line with external tooling
  pkg/controller/common/license/crypto.go
  pkg/controller/common/license/fixtures_test.go
  pkg/controller/common/license/verifier.go
  pkg/controller/common/license/verifier_test.go
Labels: >bug, exclude-from-release-notes

#4121 Introduce E2E test tags and exclude Agent recipe from Kind IPv6 tests
  .ci/setenvconfig
  Makefile
  test/e2e/agent/recipes_test.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/test/context.go
Labels: :ci, >flaky_test, >test

#4129 [Backport] Introduce E2E test tags (#4121)
  .ci/setenvconfig
  Makefile
  test/e2e/agent/recipes_test.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/test/context.go
Labels: :ci, >test, backport, v1.4.0

#4131 Upgrading AKS cluster version in CI/dev environments to 1.19.6
  hack/deployer/config/plans.yml
Labels: :ci, >test

#4126 [1.4] Add EKS ARM e2e job (#4000)
  .ci/Dockerfile
  .ci/jobs/e2e-tests-eks-arm.yml
  .ci/pipelines/e2e-tests-eks-arm.Jenkinsfile
  .ci/setenvconfig
  Makefile
  hack/deployer/config/plans.yml
Labels: backport, triage

#4109 Document Elastic Agent
  docs/advanced-topics/openshift.asciidoc
  docs/orchestrating-elastic-stack-applications/agent.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
Labels: >docs, v1.4.0

#4139 [1.4] Document Elastic Agent (#4109)
  docs/advanced-topics/openshift.asciidoc
  docs/orchestrating-elastic-stack-applications/agent.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
Labels: backport, triage

#4138 [1.4] Upgrading AKS cluster version in CI/dev environments to 1.19.6 (#4131)
  hack/deployer/config/plans.yml
Labels: backport, triage

#4134 Add go build constraints to e2e tests
  .ci/setenvconfig
  Makefile
  test/e2e/Dockerfile
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/agent/webhook_test.go
  test/e2e/apm/association_test.go
  test/e2e/apm/configuration_test.go
  test/e2e/apm/standalone_test.go
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/beat/recipes_test.go
  test/e2e/beat/setup_test.go
  test/e2e/beat/upgrade_test.go
  test/e2e/beat/webhook_test.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/ent/configuration_test.go
  test/e2e/ent/ent_test.go
  test/e2e/es/auth_test.go
  test/e2e/es/certs_test.go
  test/e2e/es/failure_test.go
  test/e2e/es/forced_upgrade_test.go
  test/e2e/es/http_test.go
  test/e2e/es/keystore_test.go
  test/e2e/es/license_test.go
  test/e2e/es/mutation_test.go
  test/e2e/es/naming_test.go
  test/e2e/es/podtemplate_test.go
  test/e2e/es/remote_cluster_test.go
  test/e2e/es/reversal_test.go
  test/e2e/es/topology_test.go
  test/e2e/es/validation_test.go
  test/e2e/es/version_upgrade_test.go
  test/e2e/es/volume_test.go
  test/e2e/kb/association_test.go
  test/e2e/kb/failure_test.go
  test/e2e/kb/keystore_test.go
  test/e2e/kb/resource_test.go
  test/e2e/kb/standalone_test.go
  test/e2e/kb/telemetry_test.go
  test/e2e/kb/version_upgrade_test.go
  test/e2e/run.sh
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/stack_test.go
  test/e2e/test/context.go
Labels: >test

#4122 Support both kind 0.8 and 0.9
  .ci/Dockerfile
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/setenvconfig
  Makefile
  hack/kind/go.mod
  hack/kind/kind.sh
  hack/kind/local-path-storage.yaml
  hack/kind/main.go
  hack/kind/storageclass.yaml
Labels: :ci, >test

#4143 E2E: pass kind version on test make target
  Makefile
Labels: :ci, >test

#4099 Do not delete StatefulSets associated to empty nodeSets
  config/crds/all-crds.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/sset/list.go
Labels: >enhancement, autoscaling, exclude-from-release-notes, v1.5.0

#4133 E2E: separate SCC from monitoring configuration
  config/e2e/monitoring.yaml
  config/e2e/scc.yaml
  test/e2e/cmd/run/run.go
Labels: >test

#4146 [1.4] Update golang Docker tag to v1.15.7 (#4140)
  .ci/Dockerfile
  Dockerfile
  hack/manifest-gen/Dockerfile
  test/e2e/Dockerfile
Labels: >non-issue, backport

#4149 [1.4] Add go build constraints to e2e tests (#4134)
  .ci/setenvconfig
  Makefile
  test/e2e/Dockerfile
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/agent/webhook_test.go
  test/e2e/apm/association_test.go
  test/e2e/apm/configuration_test.go
  test/e2e/apm/standalone_test.go
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/beat/recipes_test.go
  test/e2e/beat/setup_test.go
  test/e2e/beat/upgrade_test.go
  test/e2e/beat/webhook_test.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/ent/configuration_test.go
  test/e2e/ent/ent_test.go
  test/e2e/es/auth_test.go
  test/e2e/es/certs_test.go
  test/e2e/es/failure_test.go
  test/e2e/es/forced_upgrade_test.go
  test/e2e/es/http_test.go
  test/e2e/es/keystore_test.go
  test/e2e/es/license_test.go
  test/e2e/es/mutation_test.go
  test/e2e/es/naming_test.go
  test/e2e/es/podtemplate_test.go
  test/e2e/es/remote_cluster_test.go
  test/e2e/es/reversal_test.go
  test/e2e/es/topology_test.go
  test/e2e/es/validation_test.go
  test/e2e/es/version_upgrade_test.go
  test/e2e/es/volume_test.go
  test/e2e/kb/association_test.go
  test/e2e/kb/failure_test.go
  test/e2e/kb/keystore_test.go
  test/e2e/kb/resource_test.go
  test/e2e/kb/standalone_test.go
  test/e2e/kb/telemetry_test.go
  test/e2e/kb/version_upgrade_test.go
  test/e2e/run.sh
  test/e2e/samples_test.go
  test/e2e/smoke_test.go
  test/e2e/stack_test.go
  test/e2e/test/context.go
Labels: >test, backport

#4145 Add a note about the new kind setup
  dev-setup.md
Labels: >docs

#4151 Enable EKS ARM e2e tests
  .ci/pipelines/build.Jenkinsfile
  .ci/setenvconfig
Labels: :ci, >test

#4156 Fix Dockerfile platform argument for e2e image
  test/e2e/Dockerfile
Labels: :ci, >test

#4153 Fix typo in manifest example
  docs/advanced-topics/openshift.asciidoc
Labels: >docs

#4160 [1.4] Fix typo in manifest example (#4153)
  docs/advanced-topics/openshift.asciidoc
Labels: >docs, backport

#4162 E2E: Temporarily disable license tests and monitoring for ARM tests
  .ci/setenvconfig
Labels: :ci, >test

#4163 Add README files to Helm charts
  deploy/README.md
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/README.md
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/README.md
Labels: >docs

#4148 [Autoscaling] Add autoscaling resource definition
  config/crds/all-crds.yaml
  config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
  pkg/apis/elasticsearch/v1/autoscaling.go
  pkg/apis/elasticsearch/v1/autoscaling_test.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/elasticsearch/validation/autoscaling_validation.go
  pkg/controller/elasticsearch/validation/autoscaling_validation_test.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/elasticsearch/validation/volume_validation.go
Labels: >feature, autoscaling, v1.5.0

#4167 [Backport] Update JVM Heap Size section (#4096)
  docs/orchestrating-elastic-stack-applications/elasticsearch/jvm-heap-size.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
Labels: >docs, backport, v1.4.0

#4166 [Backport] Update maxSurge setting description (#4095)
  docs/orchestrating-elastic-stack-applications/elasticsearch/update-strategy.asciidoc
Labels: >docs, backport, v1.4.0

#4165 [Backport] Add README files to Helm charts (#4163)
  deploy/README.md
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/README.md
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/README.md
Labels: >docs, backport, v1.4.0

#4169 Move naming test out of es package as it also tests Kibana and APM
  test/e2e/naming_test.go
Labels: :ci, >test

#4170 E2E: Update Ansible image tag in ocp3 deployer
  hack/deployer/runner/ocp3.go
Labels: :ci, >test

#4172 Skip Elasticsearch 6.8.x upgrade tests on ARM
  .ci/setenvconfig
  test/e2e/es/version_upgrade_test.go
  test/e2e/test/context.go
Labels: :ci, >test
