Repository elastic/cloud-on-k8s, pull requests merged in 2021-06, with the labels that each got.

#4542 OCP4: Use smaller cluster name
  .ci/setenvconfig
Labels: :ci, >test

#4541 ECK docs - Fix wording and product name
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs

#4543 E2E: Elastic Maps Server revert to explicit snapshot check
  .ci/setenvconfig
  test/e2e/test/maps/builder.go
  test/e2e/test/version.go
  test/e2e/test/version_test.go
Labels: :ci, >test

#4544 [1.6] ECK docs - Fix wording and product name (#4541)
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport

#4545 [Backport] Docs: Add note about different license expiry dates (#4517)
  docs/operating-eck/licensing.asciidoc
Labels: >docs, backport

#4548 Fix typo in OperatorHub CSV template
  hack/operatorhub/templates/csv.tpl
Labels: >docs

#4552 Remove 7.4.x and 7.5.x in CI + upgrade versions to 7.13.1
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/journalbeat_hosts.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems-es.yaml
  config/recipes/maps/02-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  hack/operatorhub/config.yaml
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/stack_test.go
  test/e2e/test/version.go
Labels: >test

#4551 Docs: add sections on JVM heap dumps
  docs/operating-eck/troubleshooting/troubleshooting-methods.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/jvm-heap-dumps.asciidoc
  docs/orchestrating-elastic-stack-applications/enterprise-search.asciidoc
Labels: >docs

#4571 Fix heap memory parsing with trailing white spaces
  pkg/license/aggregator.go
  pkg/license/aggregator_test.go
Labels: >bug, v1.7.0

#4563 Move PSP to recipe section to improve visibility
  Makefile
  config/dev/elastic-psp.yaml
  config/e2e/chaos_job.yaml
  config/e2e/e2e_job.yaml
  config/recipes/psp/README.asciidoc
  config/recipes/psp/beats-agent-psp.yaml
  config/recipes/psp/elastic-psp.yaml
  test/e2e/Dockerfile
Labels: >docs

#4572 Beats: allow unprivileged Pods to read configuration file
  pkg/controller/beat/common/pod.go
  pkg/controller/beat/common/pod_test.go
Labels: >bug, v1.7.0

#4521 Update docs eck attributes eck version to 1.6
  docs/eck-attributes.asciidoc
Labels: >docs

#4569 Detect admission registration API version
  cmd/manager/main.go
  pkg/controller/webhook/admission_registration.go
  pkg/controller/webhook/cert.go
  pkg/controller/webhook/reconcile.go
  pkg/controller/webhook/reconcile_test.go
  pkg/controller/webhook/webhook_certificates_controller.go
Labels: >bug, v1.7.0

#4584 Add poddisruptionbudgets to eck-dump.sh diagnostics tool
  support/diagnostics/eck-dump.sh
Labels: >non-issue

#4583 Bump Agent resources to 350Mi
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  pkg/controller/agent/pod.go
  test/e2e/test/beat/pod_builder.go
Labels: :ci, >enhancement, v1.7.0

#4586 Fix links in CSV description
  hack/operatorhub/templates/csv.tpl
Labels: >docs

#4582 Doc edits: upgrade order and typos
  docs/operating-eck/upgrading-eck.asciidoc
  docs/orchestrating-elastic-stack-applications/upgrading-stack.asciidoc
  docs/quickstart.asciidoc
Labels: >docs

#4589 [1.6] Fix links in CSV description (#4586)
  hack/operatorhub/templates/csv.tpl
Labels: >non-issue, backport

#4593 OCP deployer: Remove context, user and cluster from kube config after delete
  hack/deployer/runner/ocp.go
Labels: :ci, >test

#4601 Update supported-versions.asciidoc
  docs/supported-versions.asciidoc
Labels: >docs

#4575 Support custom CA on HTTP layer
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1beta1/all-crds.yaml
  config/crds/v1beta1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds-legacy.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/orchestrating-elastic-stack-applications/accessing-elastic-services.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/http-settings-tls-sans.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
  docs/orchestrating-elastic-stack-applications/security/custom-http-certificate.asciidoc
  docs/reference/api-docs.asciidoc
  hack/upgrade-test-harness/testdata/v160/install.yaml
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/common/certificates/ca_secret.go
  pkg/controller/common/certificates/ca_secret_test.go
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/common/certificates/reconcile.go
  pkg/controller/common/certificates/secret.go
  pkg/controller/common/certificates/secret_test.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/kibana/driver.go
  test/e2e/es/certs_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/checks_http.go
  test/e2e/test/elasticsearch/checks_k8s.go
Labels: >feature, v1.7.0
