Repository elastic/cloud-on-k8s, pull requests merged in 2022-09, with the labels that each got.

#5984 [DOC] Update github.com/elastic/crd-ref-docs to v0.0.8
  docs/reference/api-docs.asciidoc
  hack/api-docs/build.sh
Labels: >docs, exclude-from-release-notes, v2.5.0

#6007 Surface Kubernetes client rate limiter metrics
  pkg/utils/metrics/k8s_client.go
  pkg/utils/metrics/operator.go
Labels: >enhancement, v2.5.0

#6004 Fix helm chart rendering issues associated with indentation
  .gitignore
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-elasticsearch/templates/_helpers.tpl
  deploy/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/templates/_helpers.tpl
  deploy/eck-kibana/templates/kibana.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/Chart.lock
  deploy/eck-stack/Chart.yaml
Labels: >bug

#5989 Add Elasticsearch observation interval as configurable value to Helm Chart
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, v2.5.0

#6010 Upgrade vegeta to v12.8.4 - Attempt fix panic in e2e load testing
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  test/e2e/es/mutation_test.go
Labels: >bug, :ci, v2.5.0

#5965 Restructure secure settings docs and minor additions
  docs/orchestrating-elastic-stack-applications/elasticsearch/es-secure-settings.asciidoc
Labels: >docs, v2.5.0

#5966 Report incorrect license type in logs and events
  pkg/controller/common/events/events.go
  pkg/controller/common/license/crud.go
  pkg/controller/common/license/model.go
  pkg/controller/common/license/parser.go
  pkg/controller/common/license/parser_test.go
  pkg/controller/common/license/testdata/wrong-type.json
  pkg/controller/license/license_controller.go
  pkg/controller/license/license_controller_test.go
Labels: >enhancement, v2.5.0

#5971 Don't log non-standard ES JSON error responses as errors
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/client/error.go
  pkg/controller/elasticsearch/client/test_fixtures/errors.go
Labels: >enhancement, v2.5.0

#6013 Ignore unmanaged namespaces in webhook validation for all resources.
  pkg/controller/common/webhook/webhook.go
  pkg/controller/common/webhook/webhook_test.go
Labels: >bug, >enhancement

#6023 Update GKE versions after September 13 GKE release
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  hack/deployer/config/plans.yml
Labels: :ci, >test, v2.5.0

#6025 Remove unnecessary trailing space in CI Dockerfile
  .ci/Dockerfile
Labels: :ci, >refactoring, v2.5.0

#6026 Fix cancel function leak
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test, >refactoring, v2.5.0

#5987 Update e2e tests stack versions
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
Labels: :ci, >test, v2.5.0

#5969 Rewrite snapshot documentation and add CSP specific setups
  docs/orchestrating-elastic-stack-applications/elasticsearch/snapshots.asciidoc
Labels: >docs, v2.5.0

#5986 Update Stack version to 8.4.2
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-kibana/values.yaml
  hack/update-stack-version.sh
  test/e2e/test/version.go
Labels: >non-issue, v2.4.0, v2.5.0

#6036 Update controller-gen.kubebuilder.io/version to v0.10.0
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/autoscaling.k8s.elastic.co_elasticsearchautoscalers.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
Labels: >non-issue, v2.4.0

#6034 [2.4] Update Stack version to 8.4.2 (#5986)
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-kibana/values.yaml
  hack/update-stack-version.sh
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v240/crds.yaml
  hack/upgrade-test-harness/testdata/v240/install.yaml
  hack/upgrade-test-harness/testdata/v240/stack.yaml
  test/e2e/test/version.go
Labels: backport, >non-issue, v2.4.0

#6029 Update OpenShift versions
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp-all-but-latest.Jenkinsfile
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: :ci, >test, v2.5.0

#6028 Update k8s supported versions
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  README.md
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/values.yaml
  deploy/eck-operator/values.yaml
  deploy/eck-stack/Chart.yaml
  docs/supported-versions.asciidoc
  hack/deployer/config/plans.yml
  hack/manifest-gen/internal/manifest.go
  hack/manifest-gen/test.sh
  hack/operatorhub/templates/csv.tpl
Labels: >test, v2.5.0

#5889 ECK resources Helm chart - Elastic Agent & Elastic Fleet Server Agent
  deploy/eck-agent/.helmignore
  deploy/eck-agent/Chart.yaml
  deploy/eck-agent/LICENSE
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/NOTES.txt
  deploy/eck-agent/templates/_helpers.tpl
  deploy/eck-agent/templates/cluster-role-binding.yaml
  deploy/eck-agent/templates/cluster-role.yaml
  deploy/eck-agent/templates/elastic-agent.yaml
  deploy/eck-agent/templates/service-account.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-elasticsearch/templates/NOTES.txt
  deploy/eck-fleet-server/.helmignore
  deploy/eck-fleet-server/Chart.yaml
  deploy/eck-fleet-server/LICENSE
  deploy/eck-fleet-server/templates/NOTES.txt
  deploy/eck-fleet-server/templates/_helpers.tpl
  deploy/eck-fleet-server/templates/cluster-role-binding.yaml
  deploy/eck-fleet-server/templates/cluster-role.yaml
  deploy/eck-fleet-server/templates/fleet-server.yaml
  deploy/eck-fleet-server/templates/service-account.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/templates/NOTES.txt
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/README.md
  deploy/eck-stack/examples/fleet-agents.yaml
  deploy/eck-stack/templates/NOTES.txt
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/values.yaml
Labels: >enhancement, v2.5.0

#6037 Increment desired nodes version on each call
  pkg/controller/elasticsearch/driver/desired_nodes.go
  pkg/controller/elasticsearch/driver/desired_nodes_test.go
  pkg/controller/elasticsearch/hints/hints.go
Labels: >bug, v2.5.0

#6042 Adjust e2e test for changed desired nodes behaviour
  test/e2e/test/elasticsearch/checks_es.go
Labels: >test, v2.5.0

#6043 Fix Beats Stack Monitoring e2e tests
  test/e2e/beat/config_test.go
  test/e2e/test/beat/builder.go
Labels: >bug, >test

#6049 OCP4: use UBI as base image instead of scratch
  hack/deployer/clients/ocp/Dockerfile
Labels: :ci, >test

#6021 Add note for air-gapped environments for pulling the Support diag image
  docs/operating-eck/troubleshooting/take-eck-dump.asciidoc
Labels: >docs

#6051 [2.5] Add note for air-gapped environments for pulling the Support diag image (#6021)
  docs/operating-eck/troubleshooting/take-eck-dump.asciidoc
Labels: >docs, backport

#6052 Add note for air-gapped environments for pulling the Support diag image (#6021)
  docs/operating-eck/troubleshooting/take-eck-dump.asciidoc
Labels: >docs, backport

#6050 OCP4: use UBI as base image instead of scratch (#6049)
  hack/deployer/clients/ocp/Dockerfile
Labels: :ci, >test, backport

#6047 Add default securityContext to the manager container
  deploy/eck-operator/values.yaml
Labels: >enhancement, v2.6.0

#6054 Use snapshot EPR for snapshot tests
  test/e2e/test/kibana/builder.go
Labels: >test

#6056 Bump Agent chart kubeVersion for consistency
  deploy/eck-agent/Chart.yaml
  deploy/eck-fleet-server/Chart.yaml
Labels: >non-issue

#6055 Bump versions to 2.6.0-SNAPSHOT
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  hack/operatorhub/config.yaml
Labels: >non-issue

#6058 [E2E] Disable TestJournalbeatHostsRecipe on Kind
  test/e2e/beat/recipes_test.go
Labels: :ci, >test

#6059 [E2E] Disable TestJournalbeatHostsRecipe on Kind (#6058)
  test/e2e/beat/recipes_test.go
Labels: >test, backport
