Repository elastic/cloud-on-k8s, pull requests merged in 2022-06, with the labels that each got.

#5721 Bump e2e tests stack versions
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  test/e2e/stack_test.go
  test/e2e/test/version.go
Labels: :ci, >test

#5719 Remove extra white space in Dockerfile
  .ci/Dockerfile
Labels: >non-issue

#5724 [E2E] Revert #5670 - Enable TestAuditbeatConfig for 8.3.0-SNAPSHOT
  test/e2e/beat/config_test.go
Labels: >flaky_test, v2.3.0

#5723 Change loop into copy
  pkg/controller/elasticsearch/driver/fixtures.go
Labels: >refactoring, v2.3.0

#5728 E2E: update Tanzu to 1.5.4
  hack/deployer/config/plans.yml
  hack/deployer/runner/azure/azure.go
  hack/deployer/runner/tanzu.go
Labels: :ci, >test

#5729 E2E: EKS wait for deletion
  hack/deployer/runner/eks.go
Labels: :ci, >test

#5731 Undo accidentally committed file
  index.yaml
Labels: >non-issue, v2.0.0, v2.1.0, v2.2.0, v2.3.0

#5735 Revert "Fix CVE-2015-5237 (#5645)"
  go.mod
  go.sum
Labels: >enhancement

#5739 [E2E] Kibana monitoring: fix index pattern
  test/e2e/test/kibana/builder.go
Labels: >flaky_test, v2.3.0

#5741 Change references to the master branch to main in the CONTRIBUTING guide.
  CONTRIBUTING.md
Labels: >docs

#5742 Updating versions to 2.3
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.3.0

#5743 Updating versions for 2.4.0 snapshot builds
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.4.0

#5744 Refactor long switch
  pkg/apis/elasticsearch/v1/elasticsearch_config.go
Labels: >refactoring, v2.4.0

#5738 Comment and tests for autoscaling memory, CPU, and storage ranges
  pkg/controller/autoscaling/elasticsearch/autoscaler/linear_scaler.go
  pkg/controller/autoscaling/elasticsearch/autoscaler/linear_scaler_test.go
Labels: >docs, >test, v2.4.0

#5750 [2.1] Undo accidentally committed file (#5731)
  index.yaml
Labels: backport, >non-issue

#5747 Check CSR signature on certificate creation
  pkg/controller/elasticsearch/certificates/transport/csr.go
Labels: >refactoring, v2.4.0

#5755 Refactor request body closing
  hack/operatorhub/main.go
  pkg/controller/association/secret.go
  pkg/controller/common/stackmon/config.go
  test/e2e/test/enterprisesearch/http_client.go
  test/e2e/test/kibana/http_client.go
  test/e2e/test/maps/http_client.go
Labels: >refactoring

#5763 Expose recipes in ECK product documentation
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/orchestrating-elastic-stack-applications/recipes.asciidoc
Labels: >docs

#5759 Refactor Kibana config settings setup
  pkg/controller/kibana/config_settings.go
Labels: >refactoring, v2.4.0

#5758 Check shard activity before removing a node
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/shard.go
  pkg/controller/elasticsearch/driver/downscale_test.go
  pkg/controller/elasticsearch/driver/upgrade_predicates.go
  pkg/controller/elasticsearch/migration/fixtures.go
  pkg/controller/elasticsearch/migration/migrate_data.go
Labels: >bug, v2.4.0

#5753 Fix minimum Helm supported version 3.2.0 in README
  deploy/eck-operator/README.md
Labels: >docs

#5770 Fix non closed http responses (#5755)
  hack/operatorhub/main.go
  pkg/controller/association/secret.go
  pkg/controller/common/stackmon/config.go
  test/e2e/test/enterprisesearch/http_client.go
  test/e2e/test/kibana/http_client.go
  test/e2e/test/maps/http_client.go
Labels: >bug, backport, v2.3.0

#5768 E2E: Do not leak continuous health check go routine
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#5771 [2.3] Update note about self stack-monitoring (#5769)
  docs/advanced-topics/stack-monitoring.asciidoc
Labels: >docs, backport, v2.3.0

#5772 Fix ubi8 suffix in operatorhub template
  Makefile
Labels: >bug, v2.3.0

#5774 [2.3] Fix ubi8 suffix in Makefile (#5772)
  Makefile
Labels: >bug, backport

#5775 E2E: make sure WithVersion is called in elasticsearch.Builder
  test/e2e/test/elasticsearch/builder.go
Labels: >test

#5757 Deployer: pick up cached vault auth token from env
  hack/deployer/cmd/create.go
  hack/deployer/runner/aks.go
  hack/deployer/runner/eks.go
  hack/deployer/runner/gcloud.go
  hack/deployer/runner/ocp.go
  hack/deployer/runner/ocp3.go
  hack/deployer/runner/settings.go
  hack/deployer/runner/tanzu.go
  hack/deployer/vault/vault.go
Labels: :ci, >test

#5785 [E2E] Upgrade Kind node versions
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  hack/deployer/config/plans.yml
Labels: :ci, >test

#5786 [E2E] Upgrade Kind node versions (#5785)
  .ci/packer_cache.sh
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  hack/deployer/config/plans.yml
Labels: :ci, >test, backport

#5787 E2E: update monitoring agent version to 8.2.3 (#5780)
  config/e2e/monitoring.yaml
Labels: :ci, >test, backport

#5766 Adding release notes, and highlights for 2.3.0 release
  docs/release-notes.asciidoc
  docs/release-notes/2.3.0.asciidoc
  docs/release-notes/highlights-2.3.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v2.3.0

#5790 Support RevisionHistoryLimit in Deployment and Daemonset for Elastic Agent
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/agent/controller_test.go
  pkg/controller/agent/reconcile.go
  pkg/controller/common/daemonset/reconcile.go
  pkg/controller/common/deployment/reconcile.go
Labels: >feature, v2.4.0

#5777 [DOC] Update Network Policies
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, v2.3.0

#5801 [2.3][DOC] Update Network Policies (#5777)
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, backport

#5802 [2.2][DOC] Update Network Policies (#5777)
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, backport

#5803 [2.1][DOC] Update Network Policies (#5777)
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, backport

#5805 [1.9][DOC] Update Network Policies (#5777)
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, backport

#5806 [1.8][DOC] Update Network Policies (#5777)
  docs/advanced-topics/network-policies.asciidoc
Labels: >docs, backport

#5799 Adding release notes, and highlights for 2.3.0 release (#5766)
  docs/release-notes.asciidoc
  docs/release-notes/2.3.0.asciidoc
  docs/release-notes/highlights-2.3.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport

#5793 Increase default Beats guaranteed memory to 300Mi
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  pkg/controller/beat/common/pod.go
Labels: >enhancement, v2.4.0

#5824 Upgrade test harness: fix CRDs first install
  hack/upgrade-test-harness/fixture/eck.go
  hack/upgrade-test-harness/main.go
Labels: >bug, exclude-from-release-notes

#5827 Add 2.2 known issue about service token migration
  docs/release-notes/highlights-2.2.0.asciidoc
Labels: >docs, v2.2.0

#5796 Stricter notion of esReacheable: require health response
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/driver_test.go
Labels: >enhancement, v2.4.0

#5830 Do not use service accounts until Elasticsearch nodes have been upgraded
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/association/reconciler.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/security.go
  pkg/controller/elasticsearch/client/security_test.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/driver_test.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/hints/hints.go
  pkg/controller/elasticsearch/user/reconcile.go
  pkg/controller/elasticsearch/user/service_account.go
  pkg/utils/optional/bool.go
  pkg/utils/optional/bool_test.go
Labels: >bug, v2.3.0

#5831 Do not use service accounts until Elasticsearch nodes have been upgraded
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/association/reconciler.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/security.go
  pkg/controller/elasticsearch/client/security_test.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/driver/driver_test.go
  pkg/controller/elasticsearch/driver/nodes.go
  pkg/controller/elasticsearch/hints/hints.go
  pkg/controller/elasticsearch/user/reconcile.go
  pkg/controller/elasticsearch/user/service_account.go
  pkg/utils/optional/bool.go
  pkg/utils/optional/bool_test.go
Labels: >bug, backport

#5826 E2E: Resize azure/aks vms from v3 -> v5
  hack/deployer/config/plans.yml
Labels: >test

#5837 Mention #5830 in 2.3 release notes
  docs/release-notes/2.3.0.asciidoc
Labels: >docs, v2.3.0

#5838 Mention #5830 in 2.3.0 release notes (#5837)
  docs/release-notes/2.3.0.asciidoc
Labels: >docs, backport

#5829 [2.2] Add 2.2 known issue about service token migration (#5827)
  docs/release-notes/highlights-2.2.0.asciidoc
Labels: >docs, backport

#5845 Revert indentation in testdata/stream.json to fix Test_helper_streamTestJobOutput_withError
  test/e2e/cmd/run/testdata/stream.json
Labels: >test
