Repository elastic/cloud-on-k8s, pull requests merged in 2022-01, with the labels that each got.

#5093 Improve documentation around cpu and memory resources
  docs/orchestrating-elastic-stack-applications/elasticsearch-specification.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/jvm-heap-size.asciidoc
  docs/orchestrating-elastic-stack-applications/images/cgroups-cfs-stats.png
  docs/orchestrating-elastic-stack-applications/images/metrics-explorer-cpu.png
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
Labels: >docs

#5215 Update NOTICE for new year 2022
  NOTICE.txt
Labels: >non-issue

#5216 Update dev documentation around Kind
  dev-setup.md
  hack/deployer/README.md
Labels: >docs

#5189 Add support for transport TLS certificate other/common name suffix
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/elasticsearch/certificates/transport/csr.go
  pkg/controller/elasticsearch/certificates/transport/csr_test.go
  pkg/controller/elasticsearch/certificates/transport/pod_secret.go
  pkg/controller/elasticsearch/certificates/transport/reconcile.go
Labels: >enhancement, v2.0.0

#5172 Elastic Maps Server: no Elasticsearch connection required since 7.14
  config/recipes/maps/01-ems-es.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/maps/02-kb.yaml
  config/recipes/maps/README.asciidoc
  docs/orchestrating-elastic-stack-applications/maps.asciidoc
  pkg/controller/maps/pod.go
Labels: >enhancement, v2.0.0

#5225 Elastic Maps Server: must not use standalone in combination with association mode as of 7.14
  pkg/controller/maps/pod.go
  test/e2e/ems/ems_test.go
Labels: >bug

#5227 [E2E][EMS] Enable E2E tests on EMS snapshot builds
  test/e2e/test/maps/builder.go
  test/e2e/test/version.go
  test/e2e/test/version_test.go
Labels: :ci, >test

#5221 Replace references to the master branch with main
  .ci/README.md
  .ci/jobs/build-nightly.yml
  .ci/jobs/e2e-cleanup-gke.yml
  .ci/jobs/e2e-tests-aks.yml
  .ci/jobs/e2e-tests-eks-arm.yml
  .ci/jobs/e2e-tests-eks.yml
  .ci/jobs/e2e-tests-gke-k8s-versions.yml
  .ci/jobs/e2e-tests-kind-k8s-versions.yml
  .ci/jobs/e2e-tests-main-gke.yml
  .ci/jobs/e2e-tests-ocp-all-but-latest.yaml
  .ci/jobs/e2e-tests-ocp.yaml
  .ci/jobs/e2e-tests-ocp3.yaml
  .ci/jobs/e2e-tests-resilience.yml
  .ci/jobs/e2e-tests-snapshot-versions-8x-gke.yml
  .ci/jobs/e2e-tests-snapshot-versions-gke.yml
  .ci/jobs/e2e-tests-stack-versions-gke.yml
  .ci/jobs/e2e-tests-tanzu.yml
  .ci/jobs/pr-gke-full.yml
  .ci/pipelines/e2e-tests-main-gke.Jenkinsfile
  .ci/setenvconfig
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/design/0002-global-operator/0002-global-operator.md
  docs/design/0005-configurable-operator.md
  docs/design/0006-certificate-management.md
  docs/design/0011-process-manager.md
Labels: >refactoring

#5226 E2E: add missing license for EMS test
  test/e2e/ems/ems_test.go
Labels: :ci, >test

#5175 Move config hash stored in pod labels to pod annotations
  pkg/apis/agent/v1alpha1/agent_types_test.go
  pkg/apis/common/v1/association.go
  pkg/controller/agent/driver.go
  pkg/controller/agent/pod.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/pod.go
  pkg/controller/beat/common/pod_test.go
  pkg/controller/common/association/association_test.go
  pkg/controller/common/hash/hash.go
  pkg/controller/common/stackmon/config.go
  pkg/controller/elasticsearch/label/label.go
  pkg/controller/elasticsearch/label/label_test.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/stackmon/sidecar.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/enterprisesearch/enterprisesearch_controller_test.go
  pkg/controller/enterprisesearch/pod.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/stackmon/sidecar.go
  pkg/controller/maps/controller.go
  pkg/controller/maps/controller_test.go
  pkg/controller/maps/pod.go
  test/e2e/naming_test.go
Labels: >enhancement, v2.0.0

#5232 Clearer description of the podMonitor.namespace variable
  deploy/eck-operator/values.yaml
Labels: >docs

#5185 Bump the operator memory limit to 1Gi for larger deployments
  deploy/eck-operator/values.yaml
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  hack/manifest-gen/testdata/kube116.yaml
  hack/manifest-gen/testdata/no_defaults.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >enhancement, v2.0.0

#5150 Add autodetect option to security context configuration
  cmd/manager/main.go
  cmd/manager/main_test.go
  deploy/eck-operator/values.yaml
Labels: >enhancement, v2.0.0

#5242 Do not delete last master-eligible node if other nodes are not up-to-date
  pkg/controller/elasticsearch/driver/fixtures.go
  pkg/controller/elasticsearch/driver/upgrade_predicates.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/driver/upgrade_test.go
  pkg/controller/elasticsearch/driver/upscale_test.go
Labels: >bug, v2.0.0

#5141 Bump Elastic Stack version to 7.16.1
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/journalbeat_hosts.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/apm/apmserver.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  index.yaml
  test/e2e/beat/config_test.go
  test/e2e/kb/testdata/kibana_standalone.yaml
  test/e2e/stack_test.go
  test/e2e/test/version.go
Labels: >non-issue

#5239 Update Kubernetes/OCP compatibility statements for ECK 2.0
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, v2.0.0

#5243 E2E: include license pub key in PR builds
  .ci/pipelines/pr-gke.Jenkinsfile
  .ci/setenvconfig
Labels: :ci, >test

#5247 E2E: update snapshot version under test and fix version check
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  pkg/controller/common/version/version.go
  test/e2e/test/version.go
  test/e2e/test/version_test.go
Labels: :ci, >test

#5112 Stop using deprecated xpack.fleet.agents.elasticsearch.host Kibana config
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  test/e2e/agent/config_test.go
  test/e2e/test/helper/yaml.go
Labels: >enhancement, v2.0.0

#5253 Adjust Agent startup command to Ubuntu base image
  pkg/controller/agent/pod.go
  pkg/controller/agent/pod_test.go
Labels: >bug, v2.0.0

#5256 Update versions for 2.0 release
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  docs/eck-attributes.asciidoc
Labels: >non-issue

#5255 Add AKS zone support to deployer
  hack/deployer/config/plans.yml
  hack/deployer/runner/aks.go
  hack/deployer/runner/settings.go
Labels: :ci, >test

#5257 Update versions for 2.1 snapshot builds
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
Labels: >non-issue

#5254 Document node labels propagation feature
  config/samples/elasticsearch/elasticsearch.yaml
  docs/operating-eck/operator-config.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
Labels: >docs, v2.0.0

#5267 Document node labels propagation feature (#5254)
  config/samples/elasticsearch/elasticsearch.yaml
  docs/operating-eck/operator-config.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc
Labels: >docs, backport

#5261 Change upgrade path validation for 8.0 to only allow 7.17
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/elasticsearch/version/supported_versions.go
  pkg/controller/elasticsearch/version/supported_versions_test.go
Labels: >bug, v2.0.0

#5211 Isolate operator from http service misconfiguration - Use internal service
  pkg/apis/elasticsearch/v1/name.go
  pkg/controller/autoscaling/elasticsearch/controller_test.go
  pkg/controller/autoscaling/elasticsearch/driver.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/services/services.go
  pkg/controller/elasticsearch/services/services_test.go
Labels: >enhancement

#5269 [2.0] Change upgrade path validation for 8.0 to only allow 7.17 (#5261)
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/elasticsearch/version/supported_versions.go
  pkg/controller/elasticsearch/version/supported_versions_test.go
Labels: >bug, backport

#5270 E2E: Do not use elastic superuser in Kibana standalone test
  test/e2e/kb/standalone_test.go
  test/e2e/kb/testdata/kibana_standalone.yaml
Labels: :ci, >test

#5268 Support new Agent base image as of 7.17
  pkg/controller/agent/pod.go
  pkg/controller/agent/pod_test.go
Labels: >bug, v2.0.0

#4961 Add 7.16.x to 8.x E2E tests
  test/e2e/agent/upgrade_test.go
  test/e2e/agent/webhook_test.go
  test/e2e/beat/upgrade_test.go
  test/e2e/beat/webhook_test.go
  test/e2e/cmd/run/command.go
  test/e2e/ems/ems_test.go
  test/e2e/ent/ent_test.go
  test/e2e/es/version_upgrade_test.go
  test/e2e/kb/version_upgrade_test.go
  test/e2e/test/context.go
  test/e2e/test/version.go
  test/e2e/test/version_test.go
Labels: :ci, >test

#5271 Move fully to golang 1.17
  go.mod
  hack/config-extractor/go.mod
  hack/manifest-gen/go.mod
  hack/manifest-gen/go.sum
  hack/operatorhub/go.mod
  hack/operatorhub/go.sum
  hack/release-notes/go.mod
  hack/upgrade-test-harness/go.mod
  hack/upgrade-test-harness/go.sum
Labels: >refactoring

#5279 E2E: adjust continuous health check for non-HA clusters
  test/e2e/test/elasticsearch/settings.go
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: :ci, >test

#5272 Allow users to disable version validation to downgrade clusters
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/validation/validations.go
Labels: >enhancement, v2.0.0

#5280 [2.0] Allow users to disable version validation to downgrade clusters (#5272)
  docs/operating-eck/troubleshooting/common-problems.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/validation/validations.go
Labels: >enhancement, backport

#5283 E2E: remove noop upgrade from EMS test
  test/e2e/ems/ems_test.go
Labels: :ci, >test

#5285 E2E: TestESSuspendPod handle conflicts with test.Eventually
  test/e2e/es/suspend_test.go
Labels: :ci, >test

#5286 [DOCS] Fix link to Stack upgrade guide
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, v1.5.0, v1.3.2, v1.4.1, v1.6.0, v1.8.0, v1.7.1, v1.9.1

#5297 [1.9] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5296 [1.8] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5295 [1.7] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5294 [1.6] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5293 [1.5] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5291 [1.3] [DOCS] Fix links to Stack upgrade version order (#5286)
  docs/release-notes/1.3.0.asciidoc
Labels: >docs, backport

#5298 Ent Search: avoid generating invalid config in the presence of user of user overrides
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/common/settings/canonical_config_test.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
Labels: >bug, v2.0.0

#5302 [2.0] Ent Search: avoid generating invalid config in the presence of user of user overrides (#5298)
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/common/settings/canonical_config_test.go
  pkg/controller/enterprisesearch/config.go
  pkg/controller/enterprisesearch/config_test.go
Labels: >bug, backport
