Repository elastic/cloud-on-k8s, pull requests merged in 2022-11, with the labels that each got.

#6095 Prepare docs attributes for 2.5
  docs/eck-attributes.asciidoc
Labels: >docs

#6128 Fix potential panic in Elasticsearch client equal function
  pkg/controller/elasticsearch/client/base.go
Labels: >bug, v2.6.0

#6143 Do not run multiple lint operations in parallel when releasing.
  .ci/pipelines/build.Jenkinsfile
Labels: >enhancement, :ci

#6137 Update test harness for 2.5.0
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v250/crds.yaml
  hack/upgrade-test-harness/testdata/v250/install.yaml
  hack/upgrade-test-harness/testdata/v250/stack.yaml
Labels: >test

#6139 Remove deprecated versions from tests, add new versions post 8.5 release
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
Labels: >test

#6149 Manifests uploads with FIPS mode
  .ci/Makefile
  .ci/pipelines/build.Jenkinsfile
  Makefile
Labels: >bug, :ci, exclude-from-release-notes

#5773 Buildkite
  .buildkite/pipeline-nightly-e2e-tests.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common/get-test-artifacts.sh
  .ci/Makefile
  .ci/pipelines/pr-gke.Jenkinsfile
  .ci/setenvconfig
  Makefile
  hack/deployer/runner/kind.go
  hack/manifest-gen/test.sh
Labels: :ci, >test

#6161 Attempting to fix ci pipeline
  .buildkite/pipeline.yml
  .ci/Makefile
  Makefile
Labels: >bug, :ci

#6162 echo username and details of .env file for debugging ci failures.
  .ci/pipelines/build.Jenkinsfile
Labels: >bug

#6157 Expose K8S client QPS as a flag
  cmd/manager/main.go
  deploy/eck-operator/templates/configmap.yaml
  docs/operating-eck/operator-config.asciidoc
  pkg/controller/common/operator/flags.go
Labels: >enhancement, v2.6.0

#6163 Fix .env permission in CI pipelines
  .buildkite/pipeline.yml
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/e2e-tests-main-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  Makefile
Labels: >bug, :ci, exclude-from-release-notes

#6164 Get license key to run ci-check
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/e2e-tests-main-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: >bug, :ci

#6169 Fix regression in cloud-on-k8s-e2e-tests-stack-versions job
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  .ci/setenvconfig
Labels: >bug, :ci

#6171 Fix regression in cloud-on-k8s-e2e-tests-snapshot-versions job
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: >bug, :ci, v2.6.0

#6170 Bump linter timeout from 5 mins to 6 mins.
  .golangci.yml
Labels: >enhancement, :ci, v2.6.0

#6147 Update agent docs to mention root user requirement
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
Labels: >docs, v2.4.0, v2.5.0

#6124 Remove vegeta use elasticseach-go for load test
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  test/e2e/es/mutation_test.go
  test/e2e/test/elasticsearch/load.go
  test/e2e/test/k8s_client.go
Labels: >test

#6179 Increment ECK-stack version to support addition of Agent/Fleet Server
  deploy/eck-stack/Chart.yaml
Labels: >enhancement, v2.5.0, v2.6.0

#6181 [2.5] Increment ECK-stack version to support addition of Agent/Fleet Server (#6179)
  deploy/eck-stack/Chart.yaml
Labels: >enhancement, backport

#6182 Minor doc update
  docs/orchestrating-elastic-stack-applications/elasticsearch/jvm-heap-dumps.asciidoc
Labels: >docs, v2.6.0

#6148 New CRD StackConfigPolicy to declaratively configure multiple Elasticsearch clusters
  cmd/manager/main.go
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/kustomization.yaml
  config/crds/v1/bases/stackconfigpolicy.k8s.elastic.co_stackconfigpolicies.yaml
  config/e2e/rbac.yaml
  config/webhook/manifests.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  deploy/eck-operator/templates/_helpers.tpl
  deploy/eck-operator/templates/cluster-roles.yaml
  deploy/eck-operator/templates/webhook.yaml
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
  hack/operatorhub/config.yaml
  pkg/apis/common/v1/common.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1/name.go
  pkg/apis/stackconfigpolicy/v1alpha1/doc.go
  pkg/apis/stackconfigpolicy/v1alpha1/groupversion_info.go
  pkg/apis/stackconfigpolicy/v1alpha1/stackconfigpolicy_types.go
  pkg/apis/stackconfigpolicy/v1alpha1/webhook.go
  pkg/apis/stackconfigpolicy/v1alpha1/webhook_test.go
  pkg/apis/stackconfigpolicy/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/autoscaling/elasticsearch/controller.go
  pkg/controller/common/esclient/esclient.go
  pkg/controller/common/keystore/resources.go
  pkg/controller/common/keystore/user_secret.go
  pkg/controller/common/keystore/user_secret_test.go
  pkg/controller/common/reconciler/secret.go
  pkg/controller/common/reconciler/secret_test.go
  pkg/controller/common/scheme/scheme.go
  pkg/controller/common/version/version.go
  pkg/controller/common/watches/secrets.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/client/v6.go
  pkg/controller/elasticsearch/client/v7.go
  pkg/controller/elasticsearch/client/v8.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/filesettings/file_settings.go
  pkg/controller/elasticsearch/filesettings/file_settings_test.go
  pkg/controller/elasticsearch/filesettings/reconciler.go
  pkg/controller/elasticsearch/filesettings/reconciler_test.go
  pkg/controller/elasticsearch/filesettings/secret.go
  pkg/controller/elasticsearch/filesettings/secret_test.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/volume/names.go
  pkg/controller/stackconfigpolicy/controller.go
  pkg/controller/stackconfigpolicy/controller_test.go
  pkg/telemetry/fixtures.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/e2e/es/stackconfigpolicy_test.go
Labels: >feature, v2.6.0

#5899 ECK resources Helm chart - Beats
  deploy/README.md
  deploy/eck-agent/Chart.yaml
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/.helmignore
  deploy/eck-beats/Chart.yaml
  deploy/eck-beats/LICENSE
  deploy/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-beats/templates/NOTES.txt
  deploy/eck-beats/templates/_helpers.tpl
  deploy/eck-beats/templates/beats.yaml
  deploy/eck-beats/templates/cluster-role-binding.yaml
  deploy/eck-beats/templates/cluster-role.yaml
  deploy/eck-beats/templates/service-account.yaml
  deploy/eck-beats/templates/tests/beats-auditbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats-filebeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats-heartbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats-packetbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-fleet-server/Chart.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/README.md
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/examples/fleet-agents.yaml
  deploy/eck-stack/examples/metricbeat_hosts.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  deploy/eck-stack/values.yaml
  hack/update-stack-version.sh
Labels: >enhancement, v2.6.0

#6190 Update Agent config in recipe and e2e test
  config/recipes/elastic-agent/multi-output.yaml
  test/e2e/agent/config.go
  test/e2e/agent/config_test.go
Labels: >test, v2.6.0

#6189 Bump versions to 2.7.0-SNAPSHOT
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.7.0

#6198 [docs] fix minor typo
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs, v2.7.0

#6201 [2.6] Update Agent config in recipe and e2e test (#6190)
  config/recipes/elastic-agent/multi-output.yaml
  test/e2e/agent/config.go
  test/e2e/agent/config_test.go
Labels: >test, backport

#6195 More APIs for StackConfigPolicy
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/stackconfigpolicy.k8s.elastic.co_stackconfigpolicies.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/stackconfigpolicy/v1alpha1/stackconfigpolicy_types.go
  pkg/apis/stackconfigpolicy/v1alpha1/webhook.go
  pkg/apis/stackconfigpolicy/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/elasticsearch/filesettings/file_settings.go
  pkg/controller/elasticsearch/filesettings/file_settings_test.go
  pkg/controller/elasticsearch/filesettings/reconciler.go
  pkg/controller/elasticsearch/filesettings/reconciler_test.go
  pkg/controller/stackconfigpolicy/controller_test.go
  pkg/telemetry/fixtures.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/e2e/es/fixtures/stackconfigpolicy_esConfig.yaml
  test/e2e/es/stackconfigpolicy_test.go
Labels: >enhancement, v2.6.0

#6191 Update eck-diagnostics documentation for filters.
  docs/operating-eck/troubleshooting/take-eck-dump.asciidoc
Labels: >docs, v2.6.0

#6180 E2E tests need to depend on the build steps in our BK pipeline.
  .buildkite/pipeline.yml
Labels: >bug
