Repository elastic/cloud-on-k8s, pull requests merged in 2022-07, with the labels that each got.

#5783 Move first ES cluster state observation out of go routine
  pkg/controller/elasticsearch/observer/manager_test.go
  pkg/controller/elasticsearch/observer/observer.go
  pkg/controller/elasticsearch/observer/observer_test.go
Labels: >bug, v2.4.0

#5859 Add v2.3.0 to upgrade harness
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v230/crds.yaml
  hack/upgrade-test-harness/testdata/v230/install.yaml
  hack/upgrade-test-harness/testdata/v230/stack.yaml
Labels: >non-issue

#5857 [2.3] Update 2.2 known service account issue doc (#5851)
  docs/release-notes/highlights-2.2.0.asciidoc
Labels: >docs, backport

#5844 Update stack versions
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  test/e2e/test/version.go
Labels: :ci, >test, v2.4.0

#5856 Update e2e monitoring operator version
  config/e2e/helm-monitoring-operator.yaml
Labels: :ci, >non-issue, exclude-from-release-notes, v2.4.0

#5818 Support RevisionHistoryLimit for all ECK-managed resources
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/v1/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/v1/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/v1/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/v1/bases/maps.k8s.elastic.co_elasticmapsservers.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/apm/v1/zz_generated.deepcopy.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/beat/v1beta1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/apis/enterprisesearch/v1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1/zz_generated.deepcopy.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/kibana/v1/zz_generated.deepcopy.go
  pkg/apis/maps/v1alpha1/maps_types.go
  pkg/apis/maps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/agent/controller_test.go
  pkg/controller/agent/reconcile.go
  pkg/controller/apmserver/deployment.go
  pkg/controller/beat/common/reconcile.go
  pkg/controller/common/daemonset/reconcile.go
  pkg/controller/common/deployment/reconcile.go
  pkg/controller/elasticsearch/nodespec/statefulset.go
  pkg/controller/enterprisesearch/deployment.go
  pkg/controller/kibana/driver.go
Labels: >feature, v2.4.0

#5852 Make xpack.security.http.ssl.client_authentication an unsupported setting
  docs/orchestrating-elastic-stack-applications/elasticsearch/reserved-settings.asciidoc
  pkg/apis/elasticsearch/v1/fields.go
Labels: >enhancement, v2.4.0

#5850 Use static transaction names for APM
  cmd/manager/main.go
  pkg/controller/agent/controller.go
  pkg/controller/apmserver/controller.go
  pkg/controller/association/reconciler.go
  pkg/controller/autoscaling/elasticsearch/controller.go
  pkg/controller/beat/controller.go
  pkg/controller/common/controller.go
  pkg/controller/common/logging.go
  pkg/controller/common/tracing/k8s.go
  pkg/controller/common/tracing/transaction.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/observer/observer.go
  pkg/controller/enterprisesearch/enterprisesearch_controller.go
  pkg/controller/kibana/controller.go
  pkg/controller/license/license_controller.go
  pkg/controller/maps/controller.go
  pkg/controller/remoteca/controller.go
  pkg/controller/webhook/webhook_certificates_controller.go
  pkg/license/reporter.go
  pkg/telemetry/telemetry.go
Labels: >enhancement, v2.4.0

#5871 Collect ES stack traces and report all health check errors
  pkg/controller/autoscaling/elasticsearch/controller.go
  pkg/controller/elasticsearch/client/base.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/client/model.go
  pkg/controller/elasticsearch/driver/driver.go
  test/e2e/test/elasticsearch/checks_http.go
  test/e2e/test/elasticsearch/http_client.go
  test/e2e/test/elasticsearch/steps_mutation.go
  test/e2e/test/elasticsearch/steps_mutation_test.go
Labels: >test

#5877 E2E: increase timeout for 8.3
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >test

#5861 Add new operator flag to control Elasticsearch health observation intervals
  cmd/manager/main.go
  pkg/controller/common/operator/flags.go
  pkg/controller/common/operator/parameters.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/observer/manager.go
  pkg/controller/elasticsearch/observer/manager_test.go
  pkg/controller/elasticsearch/observer/observer.go
  pkg/controller/elasticsearch/observer/observer_test.go
Labels: >enhancement, v2.4.0

#5881 Move kibana xpack kubernetes package back to latest in recipe
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
Labels: >non-issue

#5846 Create agent enrollment tokens in the operator
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/controller/agent/config.go
  pkg/controller/agent/config_test.go
  pkg/controller/agent/driver.go
  pkg/controller/agent/fleet.go
  pkg/controller/agent/fleet_test.go
  pkg/controller/agent/pod.go
  pkg/controller/agent/pod_test.go
  pkg/controller/agent/testdata/ca.crt
  pkg/controller/association/controller/agent_kibana.go
  pkg/controller/common/http/http_client.go
  pkg/controller/common/reconciler/results.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
  test/e2e/test/kibana/http_client.go
Labels: >enhancement, v2.4.0

#5885 Move ci tasks to europe-west6
  hack/deployer/config/plans.yml
Labels: >bug, :ci

#5781 ECK Resources Helm Chart
  .ci/Dockerfile
  .ci/pipelines/pr-gke.Jenkinsfile
  .gitignore
  Makefile
  deploy/README.md
  deploy/eck-elasticsearch/.helmignore
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-elasticsearch/examples/hot-warm-cold.yaml
  deploy/eck-elasticsearch/templates/NOTES.txt
  deploy/eck-elasticsearch/templates/_helpers.tpl
  deploy/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-kibana/.helmignore
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/NOTES.txt
  deploy/eck-kibana/templates/_helpers.tpl
  deploy/eck-kibana/templates/kibana.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-kibana/values.yaml
  deploy/eck-stack/.helmignore
  deploy/eck-stack/Chart.lock
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/README.md
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/templates/NOTES.txt
  deploy/eck-stack/templates/_helpers.tpl
  deploy/eck-stack/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  deploy/eck-stack/values.yaml
  dev-setup.md
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
  hack/helm/test.sh
Labels: >feature

#5836 Improve "Operator crashes on startup with `OOMKilled`" docs section
  docs/operating-eck/troubleshooting/common-problems.asciidoc
Labels: >docs, v2.4.0

#5893 Fully qualified Docker image name for golang
  .ci/Dockerfile
  Dockerfile
  Dockerfile.ubi
  hack/deployer/runner/client.go
  hack/manifest-gen/Dockerfile
  test/e2e/Dockerfile
Labels: :ci, >refactoring

#5891 E2E: Run ECK diagnostics for any failed step
  test/e2e/cmd/run/run.go
Labels: >test

#5892 Configurable Vault path for the deployer
  .ci/setenvconfig
  hack/deployer/runner/azure/azure.go
  hack/deployer/runner/eks.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/ocp.go
  hack/deployer/runner/tanzu.go
  hack/deployer/vault/vault.go
Labels: >enhancement, :ci

#5895 Fix Vault path handling on read
  hack/deployer/vault/vault.go
Labels: >bug, :ci

#5894 Remove experimental label from Elastic Agent docs
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
Labels: >docs, v2.4.0

#5890 Configure host path volume to point to correct path
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  pkg/controller/agent/controller_test.go
  pkg/controller/agent/pod.go
  test/e2e/agent/config.go
Labels: >bug, >breaking, v2.4.0

#5896 Reuse Fleet enrollment tokens where possible
  pkg/controller/agent/fleet.go
  pkg/controller/agent/fleet_test.go
  pkg/controller/common/http/http_client.go
  pkg/controller/common/tracing/http.go
  pkg/controller/common/tracing/http_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/enterprisesearch/version_upgrade.go
Labels: >bug, exclude-from-release-notes, v2.4.0
