Repository elastic/cloud-on-k8s, pull requests merged in 2023-03, with the labels that each got.

#6465 Fix CI failures with OCP nightly e2e tests
  .ci/Makefile
Labels: >bug, :ci

#6477 Fix operatorhub manifest generator
  hack/operatorhub/cmd/manifests/manifests.go
  hack/operatorhub/cmd/root.go
Labels: >bug, exclude-from-release-notes, v2.7.0

#6469 Upgrade k8s version and eksctl version (1.21 is now unsupported)
  .ci/Dockerfile
  hack/deployer/config/plans.yml
  hack/deployer/runner/eks.go
Labels: >bug, :ci

#6489 Add missing maps webhook, fix inconsistencies
  config/webhook/manifests.yaml
  deploy/eck-operator/templates/webhook.yaml
  pkg/apis/maps/v1alpha1/webhook.go
Labels: >bug, v2.7.0

#6482 Fix handling of unmanaged esRef in Beats stack monitoring
  pkg/controller/association/controller/agent_fleetserver.go
  pkg/controller/association/controller/apm_kibana.go
  pkg/controller/association/controller/kibana_ent.go
  pkg/controller/association/controller/kibana_es.go
  pkg/controller/association/reconciler_test.go
  pkg/controller/association/secret.go
  pkg/controller/beat/common/driver.go
  pkg/controller/beat/common/stackmon/stackmon.go
  pkg/controller/beat/common/stackmon/stackmon_test.go
  pkg/controller/kibana/stackmon/sidecar.go
Labels: >bug, v2.7.0

#6491 Fix dev license public key setup
  .ci/Makefile
Labels: >bug, :ci, v2.7.0

#6492 Expose all fields below spec in eck-elasticsearch Helm chart
  deploy/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
Labels: >enhancement, v2.7.0

#6475 Fix vault issues in Helm release tool
  hack/helm/release/cmd/root.go
  hack/helm/release/go.mod
  hack/helm/release/go.sum
Labels: >bug, exclude-from-release-notes, v2.7.0

#6496 [E2E] Disable TestFleetAgentWithoutTLS
  test/e2e/agent/tls_test.go
Labels: >test

#6502 Ignore dev license key to test non prod stack builds
  .gitignore
Labels: >bug, :ci

#6504 Use non latest tag for buildkite agent image version
  .buildkite/pipeline-nightly-e2e-tests.yml
  .buildkite/pipeline-release-operatorhub.yml
  .buildkite/pipeline.yml
Labels: >enhancement, :ci

#6503 vault login using approle method in publish-dockerhub job
  hack/publish-dockerhub.sh
Labels: >bug, :ci

#6443 Fix upgrade test harness
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/main.go
  hack/upgrade-test-harness/testdata/upcoming/stack.yml
  hack/upgrade-test-harness/testdata/v160/install.yaml
  hack/upgrade-test-harness/testdata/v261/stack.yaml
Labels: >bug, :ci

#6506 EKS e2e: Ensure unmanaged nodegroups have correct labels
  hack/deployer/runner/eks.go
Labels: >bug, :ci

#6508 Upgrade golangci-lint to 1.51.2. Update golang to 1.20.2
  .buildkite/pipeline.yml
  .ci/Dockerfile
Labels: >enhancement, :ci

#6514 Use vault to docker login for pushing client image
  hack/deployer/runner/client.go
  hack/deployer/runner/kind.go
  hack/deployer/runner/ocp.go
Labels: >bug, :ci

#6516 Make sure file exists before reading it
  .ci/Makefile
  hack/deployer/runner/client.go
Labels: >bug, :ci

#6517 [ci/jks] Move setenv in snapshot-versions Jenkins job
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: >bug, :ci

#6518 [ci/eks] Force the use of the e2e storage class when testing recipes
  test/e2e/test/helper/yaml.go
Labels: >bug, :ci

#6521 [ci/jks] Disable tags discovery in release job
  .ci/jobs/build-release.yml
Labels: :ci, >non-issue

#6522 Bump version for 2.7.0 release
  VERSION
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-kibana/values.yaml
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/examples/metricbeat_hosts.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.7.0

#6523 Bump SNAPSHOT versions for next 2.8 cycle
  VERSION
  deploy/eck-agent/Chart.yaml
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/Chart.yaml
  deploy/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-fleet-server/Chart.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-kibana/values.yaml
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/examples/metricbeat_hosts.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.8.0

#6524 [ci/jks] Fetch right creds in DRY_RUN mode in publish-dockerhub job
  hack/publish-dockerhub.sh
Labels: >bug, :ci

#6529 Use Docker run cache in dockerfile to speed up "go mod download" step
  Dockerfile
Labels: >enhancement, exclude-from-release-notes

#6527 [ci/bk] Support release for tags prefixed with 'v'
  .buildkite/pipeline.yml
  .buildkite/scripts/build/setenv_test.sh
  .buildkite/scripts/common/lib.sh
Labels: >bug, :ci, v2.7.0

#6538 Fix dry run Helm chart release
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
Labels: >bug, :ci

#6541 [ci] Run setenv_test.sh in a clean env
  .buildkite/pipeline.yml
Labels: >bug, :ci

#6540 [ci/bk] Give 4G memory to bk agent to run e2e-tests
  .buildkite/pipeline-nightly-e2e-tests.yml
Labels: >bug, :ci

#6535 Refactoring ubi/dockerhub images release
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-release.yml
  .buildkite/scripts/build/setenv.sh
  .ci/pipelines/build.Jenkinsfile
  .ci/setenvconfig
  Makefile
Labels: >enhancement, :ci

#6548 Backport CI fixes to 2.7
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-nightly-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/build/setenv.sh
  .buildkite/scripts/build/setenv_test.sh
  .buildkite/scripts/common/lib.sh
  .ci/pipelines/build.Jenkinsfile
  .ci/setenvconfig
  Makefile
  deploy/eck-stack/README.md
  hack/publish-dockerhub.sh
Labels: >bug, :ci, backport, v2.7.0

#6556 Fix publish dockerhub
  hack/publish-dockerhub.sh
Labels: >bug, :ci

#6544 Call _nodes/shutdown from pre-stop hook
  docs/operating-eck/upgrading-eck.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/prestop.asciidoc
  pkg/controller/elasticsearch/configmap/configmap.go
  pkg/controller/elasticsearch/driver/downscale.go
  pkg/controller/elasticsearch/driver/upgrade.go
  pkg/controller/elasticsearch/migration/migrate_data.go
  pkg/controller/elasticsearch/nodespec/defaults.go
  pkg/controller/elasticsearch/nodespec/lifecycle_hook.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/shutdown/interface.go
  pkg/controller/elasticsearch/shutdown/node.go
  pkg/controller/elasticsearch/shutdown/node_test.go
  pkg/controller/elasticsearch/user/predefined.go
  pkg/controller/elasticsearch/user/predefined_test.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
  pkg/controller/elasticsearch/volume/names.go
  pkg/utils/k8s/k8sutils.go
  test/e2e/test/elasticsearch/checks_k8s.go
Labels: >enhancement, v2.8.0

#6554 Fix Helm Release Tool: Missing parent helm charts.
  hack/helm/release/internal/helm/helm.go
  hack/helm/release/internal/helm/helm_test.go
Labels: >bug, :ci, v2.7.0

#6565 Backport tooling fixes in 2.7
  hack/helm/release/internal/helm/helm.go
  hack/helm/release/internal/helm/helm_test.go
  hack/operatorhub/internal/container/container.go
Labels: >bug, :ci, backport, v2.7.0

#6566 Add release notes and highlights for 2.7.0
  docs/release-notes.asciidoc
  docs/release-notes/2.7.0.asciidoc
  docs/release-notes/highlights-2.7.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v2.7.0

#6570 Remove v prefix from the tag
  .buildkite/scripts/build/setenv.sh
  .buildkite/scripts/build/setenv_test.sh
Labels: >bug, :ci, v2.7.0

#6573 Remove v prefix from the tag (#6570)
  .buildkite/scripts/build/setenv.sh
  .buildkite/scripts/build/setenv_test.sh
Labels: >bug, :ci, backport, v2.7.0

#6525 Generate e2e tests pipelines
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/pipeline-gen/README.md
  .buildkite/e2e/pipeline-gen/go.mod
  .buildkite/e2e/pipeline-gen/go.sum
  .buildkite/e2e/pipeline-gen/main.go
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-nightly-e2e-tests.yml
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/test/set-deployer-config.sh
  Makefile
  hack/deployer/config/plans.yml
  hack/deployer/runner/aks.go
  hack/deployer/runner/gke.go
Labels: >enhancement, :ci

#6580 Update the build badge status of the main README
  README.md
Labels: :ci, >non-issue

#6588 [ci/eks] Force the use of the e2e storage class when testing samples
  test/e2e/samples_test.go
Labels: >bug, :ci

#6586 Set kind gcp agents machine type to n1-standard-16
  .buildkite/e2e/pipeline-gen/main.go
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: >bug, :ci

#6578 Test k8s 1.25 1.26 on kind
  .buildkite/e2e/nightly-main-matrix.yaml
  hack/deployer/config/plans.yml
Labels: :ci, >test

#6590 [ci/pipeline-gen] Lookup test env vars not current env
  .buildkite/e2e/pipeline-gen/main.go
  .buildkite/pipeline-build.yml
Labels: >bug, :ci

#6579 Fix tanzu state persistence
  .buildkite/e2e/nightly-main-matrix.yaml
  hack/deployer/runner/azure/azure.go
  hack/deployer/runner/tanzu.go
Labels: >bug, :ci

#6572 Add release notes and highlights for 2.7.0 (#6566)
  docs/release-notes.asciidoc
  docs/release-notes/2.7.0.asciidoc
  docs/release-notes/highlights-2.7.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport, v2.7.0

#6592 Test OpenShift 4.12
  .buildkite/e2e/nightly-main-matrix.yaml
  hack/deployer/config/plans.yml
Labels: :ci, >test

#6594 [ci] Release Helm charts after operator build
  .buildkite/pipeline-release-helm.yml
Labels: :ci, >non-issue

#6593 Update k8s supported versions to 1.22-1.26
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, v2.7.0

#6595 Remove migrated Jenkins jobs
  .ci/Makefile
  .ci/README.md
  .ci/jobs/build-nightly.yml
  .ci/jobs/e2e-cleanup-gke.yml
  .ci/jobs/e2e-tests-eks-arm.yml
  .ci/jobs/e2e-tests-ocp-all-but-latest.yaml
  .ci/jobs/e2e-tests-ocp.yaml
  .ci/jobs/e2e-tests-snapshot-versions-gke.yml
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/cleanup-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-eks-arm.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp-all-but-latest.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp.Jenkinsfile
  .ci/pipelines/e2e-tests-snapshot-versions-gke.Jenkinsfile
Labels: :ci, >non-issue

#6587 [ci] Stop using .env file in set-deployer-script.sh script
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/scripts/test/set-deployer-config.sh
  Makefile
Labels: >bug, :ci

#6605 Add a new role for APM Server 8.7.0+
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/apm_es_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
Labels: >enhancement, v2.7.0

#6597 Update OpenShift supported versions to 4.8-4.12
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >docs, v2.7.0

#6601 Remove deprecation note for APM Server standalone
  docs/orchestrating-elastic-stack-applications/apm-server.asciidoc
  pkg/controller/apmserver/controller.go
Labels: >bug, exclude-from-release-notes, v2.7.0

#6608 Add a new role for APM Server 8.7.0+ (#6605)
  pkg/controller/association/controller/apm_es.go
  pkg/controller/association/controller/apm_es_test.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/user/reconcile_test.go
  pkg/controller/elasticsearch/user/roles.go
Labels: >enhancement, backport, v2.7.0

#6610 Remove deprecation note for APM Server standalone (#6601)
  docs/orchestrating-elastic-stack-applications/apm-server.asciidoc
  pkg/controller/apmserver/controller.go
Labels: >bug, backport, v2.7.0

#6609 Update OpenShift supported versions to 4.8-4.12 (#6597)
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport, v2.7.0

#6604 Use Buildkite agent image for ci container on gcp agent
  .buildkite/pipeline-build.yml
  .ci/Dockerfile
  .ci/Makefile
Labels: :ci, >refactoring

#6603 [ci] Add Backstage configuration to manage Buildkite pipelines
  catalog-info.yaml
Labels: >enhancement, :ci

#6363 Don't failfast on e2e tests
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/scripts/common/cp-diagnostics.sh
  .ci/setenvconfig
  .gitignore
  config/e2e/rbac.yaml
  hack/deployer/runner/gke.go
  hack/deployer/runner/ocp.go
  test/e2e/Dockerfile
  test/e2e/beat/config_test.go
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/run.sh
  test/e2e/test/context.go
  test/e2e/test/diagnostics.go
  test/e2e/test/step.go
  test/e2e/test/utils.go
Labels: >enhancement, >test

#6616 Update 2.7.0 release notes
  docs/release-notes/2.7.0.asciidoc
Labels: >docs, v2.7.0

#6611 [e2e] Remove disabling of Agent e2e tests because of 6331
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/agent/tls_test.go
  test/e2e/agent/upgrade_test.go
Labels: >test

#6607 Make sure e2e tests reports are uploaded on failure
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/scripts/test/generate-tests-reports.sh
  test/e2e/cmd/run/run.go
Labels: >bug, :ci

#6618 Do not skip CI for .asciidoc at the PR bot level
  .buildkite/pull-requests.json
Labels: :ci, >non-issue

#6619 Update 2.7.0 release notes (#6616)
  docs/release-notes/2.7.0.asciidoc
Labels: >docs, backport, v2.7.0

#6620 Adjust condition to trigger helm release
  .buildkite/pipeline-release-helm.yml
Labels: >enhancement, :ci

#6577 Bump current docs to 2.7
  docs/eck-attributes.asciidoc
Labels: >docs, v2.8.0

#6407 Create ES client for observer only if needed
  pkg/controller/elasticsearch/client/base.go
  pkg/controller/elasticsearch/client/client.go
  pkg/controller/elasticsearch/client/client_test.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/observer/manager.go
  pkg/controller/elasticsearch/observer/manager_test.go
Labels: >enhancement, v2.8.0
