Repository elastic/cloud-on-k8s, pull requests merged in 2023-09, with the labels that each got.

#7142 Bump indirect deps of helm release tool for compatibility issues
  hack/helm/release/go.mod
  hack/helm/release/go.sum
Labels: >bug, :ci, v2.10.0 (next)

#7129 1.28.0 kind image added to nightly test matrix
  .buildkite/e2e/nightly-main-matrix.yaml
  hack/deployer/config/plans.yml
Labels: >test, v2.10.0 (next)

#7144 Fixing indent on elasticsearch.yaml (helm)
  deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
Labels: >non-issue, v2.10.0 (next)

#7145 Always build helm release tool
  .buildkite/pipeline.yml
Labels: >enhancement, :ci

#7147 Kubernetes 1.28 added to supported versions in docs
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, v2.10.0 (next)

#7146 [2.9] 1.28.0 kind image added to nightly test matrix (#7129)
  .buildkite/e2e/nightly-main-matrix.yaml
  hack/deployer/config/plans.yml
Labels: >test, backport, v2.9.0

#7149 [2.9] Kubernetes 1.28 added to supported versions in docs (#7147)
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport, v2.9.0

#7150 Telemetry test cases support 8.10 and later Kibana versions
  test/e2e/beat/setup_test.go
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/kibana/checks_kb.go
  test/e2e/test/kibana/checks_telemetry.go
  test/e2e/test/kibana/http_client.go
Labels: >bug, >test, v2.10.0 (next)

#7161 Update beat/agent doc with missing RBAC rules required from 8.9.0
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
Labels: >docs, v2.10.0 (next)

#7171 [E2E]Kind: Remove duplicated test
  .buildkite/e2e/nightly-main-matrix.yaml
Labels: >test

#7174 use core-ubuntu-2004 image for gcp steps
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  hack/deployer/clients/kind/Dockerfile
  hack/deployer/config/plans.yml
Labels: >enhancement, :ci

#7179 Remove trailing whitespaces from operator's values.yaml file.
  deploy/eck-operator/values.yaml
Labels: >docs

#7181 doc: clarify how to reset the default user's password
  docs/orchestrating-elastic-stack-applications/security/users-and-roles.asciidoc
Labels: >docs, v2.10.0 (next)

#7184 Try to stabilise tests by checking for cluster health early
  test/e2e/es/forced_upgrade_test.go
  test/e2e/es/remote_cluster_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/steps_creation.go
  test/e2e/test/helper/yaml.go
Labels: :ci, >test

#7190 Revert "Try to stabilise tests by checking for cluster health early (…
  test/e2e/es/forced_upgrade_test.go
  test/e2e/es/remote_cluster_test.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/elasticsearch/steps_creation.go
  test/e2e/test/helper/yaml.go
Labels: :ci, >test

#7191 Add missing ReplicaSet RBAC for Fleet e2e test
  config/e2e/roles.yaml
Labels: :ci, >test

#7192 Try targeted health check before Agent creation
  test/e2e/test/agent/steps.go
Labels: :ci, >test
