Repository elastic/cloud-on-k8s, pull requests merged in 2023-05, with the labels that each got.

#6733 Do not set FLEET_CA for well-known CAs
  pkg/controller/agent/driver.go
  pkg/controller/agent/pod.go
  pkg/controller/agent/pod_test.go
  pkg/controller/common/certificates/http_reconcile.go
  pkg/controller/common/certificates/http_reconcile_test.go
  pkg/controller/common/certificates/reconcile.go
  pkg/controller/common/certificates/secret.go
Labels: >bug, v2.8.0 (next)

#6742 Fix doc attributes in stack-helm-chart.asciidoc
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
Labels: >bug, >docs, v2.8.0 (next)

#6755 Do not set capabilities for Elasticsearch < 8.x
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/securitycontext/securitycontext.go
  pkg/controller/elasticsearch/securitycontext/securitycontext_test.go
  test/e2e/test/elasticsearch/check_securitycontext.go
Labels: >bug

#6744 Contributing page updated with helm chart tests suit
  CONTRIBUTING.md
Labels: >docs, v2.8.0 (next)

#6727 Allow custom certificates on the transport layer
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/orchestrating-elastic-stack-applications/elasticsearch/remote-clusters.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/reserved-settings.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/common/v1/common.go
  pkg/apis/common/v1/zz_generated.deepcopy.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/elasticsearch/v1/fields.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/controller/common/watches/state.go
  pkg/controller/elasticsearch/certificates/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/public_secret.go
  pkg/controller/elasticsearch/certificates/transport/public_secret_test.go
  pkg/controller/elasticsearch/certificates/transport/reconcile.go
  pkg/controller/elasticsearch/certificates/transport/reconcile_test.go
  pkg/controller/elasticsearch/certificates/transport/testdata/ca.crt
  pkg/controller/elasticsearch/certificates/transport/transport_fixtures_test.go
  pkg/controller/elasticsearch/certificates/transport/trust.go
  pkg/controller/elasticsearch/certificates/transport/trust_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
Labels: >enhancement, v2.8.0 (next)

#6754 Remove `runAsNonRoot` for Beats.
  pkg/controller/elasticsearch/securitycontext/securitycontext.go
  pkg/controller/elasticsearch/stackmon/sidecar_test.go
  test/e2e/test/elasticsearch/check_securitycontext.go
Labels: >bug, exclude-from-release-notes, v2.8.0 (next)

#6757 Bump versions for 2.8.0 release
  VERSION
  deploy/eck-agent/Chart.yaml
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/Chart.yaml
  deploy/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-fleet-server/Chart.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-kibana/values.yaml
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/examples/beats/metricbeat_hosts.yaml
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
Labels: >non-issue, exclude-from-release-notes, v2.8.0

#6758 Bump SNAPSHOT versions for next 2.9 cycle
  VERSION
  deploy/eck-agent/Chart.yaml
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/examples/system-integration.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/Chart.yaml
  deploy/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-elasticsearch/Chart.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
  deploy/eck-fleet-server/Chart.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-kibana/Chart.yaml
  deploy/eck-kibana/examples/http-configuration.yaml
  deploy/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-kibana/values.yaml
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/examples/beats/metricbeat_hosts.yaml
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.9.0 (next)

#6747 Retry e2e Buildkite cleanup step.
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: >test

#6769 Fix incorrect auth secret_token key post 8.0
  pkg/controller/apmserver/config.go
  pkg/controller/apmserver/config_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/deployment.go
  pkg/controller/common/http/http_client.go
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/apmserver/http_client.go
Labels: >bug, >breaking, v2.8.0

#6774 Exit in error on e2e test job timeout
  test/e2e/cmd/run/job_manager.go
Labels: :ci, >test, v2.8.0

#6776 Exit in error on e2e test job timeout (#6774)
  test/e2e/cmd/run/job_manager.go
Labels: :ci, >test, backport, v2.8.0

#6778 [2.8] Fix incorrect auth secret_token key post 8.0 (#6769)
  pkg/controller/apmserver/config.go
  pkg/controller/apmserver/config_test.go
  pkg/controller/apmserver/controller.go
  pkg/controller/apmserver/deployment.go
  pkg/controller/common/http/http_client.go
  test/e2e/test/apmserver/checks_apm.go
  test/e2e/test/apmserver/http_client.go
Labels: >bug, backport

#6780 [E2E] Do not expect Capabilities before 8.x (#6772)
  test/e2e/test/elasticsearch/check_securitycontext.go
Labels: >test, backport, v2.8.0

#6743 User-facing documentation for Logstash on ECK
  config/recipes/logstash/README.asciidoc
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/logstash/logstash.yaml
  docs/advanced-topics/network-policies.asciidoc
  docs/advanced-topics/stack-monitoring.asciidoc
  docs/operating-eck/eck-permissions.asciidoc
  docs/orchestrating-elastic-stack-applications/logstash.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/quickstart.asciidoc
  docs/supported-versions.asciidoc
Labels: >docs, v2.8.0

#6783 Build operator dev image on tag
  .buildkite/pipeline-build.yml
Labels: :ci, >test, v2.8.0

#6785 [2.8] User-facing documentation for Logstash on ECK (#6743)
  config/recipes/logstash/README.asciidoc
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/logstash/logstash.yaml
  docs/advanced-topics/network-policies.asciidoc
  docs/advanced-topics/stack-monitoring.asciidoc
  docs/operating-eck/eck-permissions.asciidoc
  docs/orchestrating-elastic-stack-applications/logstash.asciidoc
  docs/orchestrating-elastic-stack-applications/managing-compute-resources.asciidoc
  docs/orchestrating-elastic-stack-applications/orchestrating-elastic-stack-applications.asciidoc
  docs/quickstart.asciidoc
  docs/supported-versions.asciidoc
Labels: >docs, backport

#6787 Build dev image on tag (#6783)
  .buildkite/pipeline-build.yml
Labels: :ci, >test, backport

#6786 [DOC] Add 2.6 and 2.7 to the triggered restart list
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs, v2.8.0

#6792 Allow to publish non SNAPSHOT Helm chart in dev Helm repo
  hack/helm/release/internal/helm/helm.go
Labels: >bug, :ci, v2.8.0

#6794 Allow to publish non SNAPSHOT Helm chart in dev Helm repo (#6792)
  hack/helm/release/internal/helm/helm.go
Labels: >bug, :ci, backport, v2.8.0

#6789 [DOC] Add 2.6 and 2.7 to the triggered restart list (#6786)
  docs/operating-eck/upgrading-eck.asciidoc
Labels: >docs, backport

#6798 Update disk-format init container base image to debian:stable-slim
  hack/deployer/config/local-disks/ssd-provisioner.yaml
Labels: :ci, >test, v2.8.0

#6806 Update disk-format init container base image to debian:stable-slim (#6798)
  hack/deployer/config/local-disks/ssd-provisioner.yaml
Labels: :ci, >test, backport, v2.8.0

#6788 Release notes and highlights for 2.8.0
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
  docs/release-notes.asciidoc
  docs/release-notes/2.8.0.asciidoc
  docs/release-notes/highlights-2.8.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v2.8.0

#6813 Release notes and highlights for 2.8.0 (#6788)
  docs/orchestrating-elastic-stack-applications/elasticsearch/transport-settings.asciidoc
  docs/release-notes.asciidoc
  docs/release-notes/2.8.0.asciidoc
  docs/release-notes/highlights-2.8.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport

#6814 Add script to call Buildkite API to trigger RedHat ECK release
  catalog-info.yaml
  hack/operatorhub/trigger-bk-release.sh
Labels: >enhancement, :ci, v2.9.0 (next)

#6816 Fix annotation label clash between monitoring and plugin elasticsearc…
  config/samples/logstash/logstash_stackmonitor.yaml
  pkg/apis/logstash/v1alpha1/logstash_types.go
  pkg/apis/logstash/v1alpha1/logstash_types_test.go
Labels: >bug, v2.8.0

#6819 [2.8] Fix annotation label clash between monitoring and plugin elasticsearchRefs (#6816)
  config/samples/logstash/logstash_stackmonitor.yaml
  pkg/apis/logstash/v1alpha1/logstash_types.go
  pkg/apis/logstash/v1alpha1/logstash_types_test.go
Labels: >bug, backport, v2.8.0

#6825 Adjust number of replicas for Logstash stack monitoring sample
  config/samples/logstash/logstash_stackmonitor.yaml
Labels: >test, v2.8.0

#6826 [2.8] Adjust number of replicas for Logstash stack monitoring sample (#6825)
  config/samples/logstash/logstash_stackmonitor.yaml
Labels: >test, backport

#6820 Use text/template instead of html/template
  cmd/license-initializer/main.go
  hack/deployer/runner/eks.go
  pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go
Labels: >refactoring, v2.9.0 (next)

#6836 [2.8] Logstash: Update OLM description and README (#6833)
  README.md
  docs/eck-attributes.asciidoc
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport

#6822 [buildkite] Limit notified failures to not exceed message longer than 3000 bytes
  .buildkite/e2e/reporter/go.mod
  .buildkite/e2e/reporter/go.sum
  .buildkite/e2e/reporter/main.go
  .buildkite/e2e/reporter/templates/annotate-failures.tpl.md
  .buildkite/e2e/reporter/templates/annotate-success.tpl.md
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
Labels: >bug, :ci

#6760 Initial version of GKE Autopilot documentation.
  config/recipes/autopilot/README.md
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  docs/advanced-topics/advanced-topics.asciidoc
  docs/advanced-topics/gke-autopilot.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/virtual-memory.asciidoc
  docs/orchestrating-elastic-stack-applications/recipes.asciidoc
Labels: >docs, v2.8.0

#6843 [2.8] Initial version of GKE Autopilot documentation. (#6760)
  config/recipes/autopilot/README.md
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  docs/advanced-topics/advanced-topics.asciidoc
  docs/advanced-topics/gke-autopilot.asciidoc
  docs/orchestrating-elastic-stack-applications/elasticsearch/virtual-memory.asciidoc
  docs/orchestrating-elastic-stack-applications/recipes.asciidoc
Labels: >docs, backport

#6849 Update k8s.io/client-go to v0.26.5
  NOTICE.txt
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/v1/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/v1/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/v1/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  config/crds/v1/bases/maps.k8s.elastic.co_elasticmapsservers.yaml
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
Labels: >non-issue, dependencies, v2.8.0

#6850 Update k8s.io/client-go to v0.26.5 (#6849)
  NOTICE.txt
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/v1/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/v1/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/v1/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  config/crds/v1/bases/maps.k8s.elastic.co_elasticmapsservers.yaml
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
Labels: backport, >non-issue

#6844 [DOC] Mention base_path change in 2.8.0 release notes
  docs/release-notes/2.8.0.asciidoc
  docs/release-notes/highlights-2.8.0.asciidoc
Labels: >docs, v2.8.0

#6856 Fix rendering of autopilot recipes README
  config/recipes/autopilot/README.asciidoc
  config/recipes/autopilot/README.md
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
Labels: >docs, v2.9.0 (next)

#6857 Fix preflight and dry-run mode in the operator hub pipeline
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/release/redhat-preflight.sh
Labels: >bug, :ci

#6858 Fix preflight and dry-run mode in the operator hub pipeline (#6857)
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/release/redhat-preflight.sh
Labels: >bug, :ci, backport

#6862 Add Logstash webhook clientConfig
  deploy/eck-operator/templates/webhook.yaml
Labels: >bug, v2.8.0

#6863 Add Logstash webhook clientConfig (#6862)
  deploy/eck-operator/templates/webhook.yaml
Labels: >bug, backport

#6854 Add Selector to LogstashStatus
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/logstash/v1alpha1/logstash_types.go
  pkg/controller/logstash/logstash_controller_test.go
  pkg/controller/logstash/reconcile.go
Labels: >bug, v2.9.0 (next)

#6864 Bump Stack version to 8.8.0 / 8.9.0-SNAPSHOT
  .buildkite/e2e/nightly-main-matrix.yaml
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  config/samples/logstash/logstash_es.yaml
  config/samples/logstash/logstash_stackmonitor.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  hack/update-stack-version.sh
  test/e2e/agent/recipes_test.go
  test/e2e/test/version.go
Labels: >docs, :ci, >test, v2.8.0
