Repository elastic/cloud-on-k8s, pull requests merged in 2023-02, with the labels that each got.

#6372 Skip TestAPMKibanaAssociation on 8.7.0-snapshot due to a known
  test/e2e/apm/association_test.go
Labels: >bug, >test, exclude-from-release-notes

#6370 Make TestRedClusterCanBeModifiedByDisablingPredicate more resilient with retries
  test/e2e/es/disable_predicates_test.go
Labels: >flaky_test

#6376 Skip Fleet tests until #6331 is resolved
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/agent/upgrade_test.go
  test/e2e/test/utils.go
Labels: >flaky_test

#6226 Helm Release Pipeline
  .buildkite/pipeline-helm-release-all.yml
  .buildkite/pipeline-helm-release-eck-operator.yml
  .buildkite/pipeline-helm-release-eck-resources.yml
  .buildkite/pipeline.yml
  hack/helm/release/Makefile
  hack/helm/release/cmd/root.go
  hack/helm/release/cmd/vault.go
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  hack/helm/release/internal/helm/helm.go
  hack/helm/release/internal/helm/helm_test.go
  hack/helm/release/internal/helm/types.go
  hack/helm/release/main.go
  hack/helm/release/readme.md
Labels: >enhancement, :ci

#6298 Changes required to prefix versions with 'v'.
  .ci/setenvconfig
  hack/manifest-gen/manifest-gen.sh
Labels: >enhancement, v2.7.0

#6336 Adding an exhaustive list of Helm chart values to eck-elasticsearch chart.
  deploy/eck-elasticsearch/values.yaml
Labels: >enhancement, >docs, v2.7.0

#6388 Update git config of ci container for recent git versions
  .ci/Dockerfile
Labels: :ci, >non-issue, v2.7.0

#6391 Minor documentation fixes
  deploy/README.md
  docs/operating-eck/operator-config.asciidoc
Labels: >docs, exclude-from-release-notes, v2.7.0

#6392 Delete migrated Jenkins jobs on Buildkite
  .ci/jobs/e2e-tests-custom.yml
  .ci/jobs/e2e-tests-main-gke.yml
  .ci/jobs/e2e-tests-ocp3.yaml
  .ci/jobs/pr-gke-e2e-tests.yml
  .ci/jobs/pr-gke.yml
  .ci/pipelines/e2e-tests-custom.Jenkinsfile
  .ci/pipelines/e2e-tests-main-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-ocp3.Jenkinsfile
  .ci/pipelines/pr-gke.Jenkinsfile
  CONTRIBUTING.md
Labels: :ci, >non-issue

#6393 Revert "Skip test on 8.7.0-snap due to known issue #6371"
  test/e2e/apm/association_test.go
Labels: >test, v2.7.0

#6420 Revert ci image to Docker v1.19.5
  .ci/Dockerfile
Labels: :ci, >non-issue

#6432 [2.6] Add release notes change for FIPS to 2.6.0 (#6429)
  docs/release-notes/2.6.0.asciidoc
Labels: >docs, backport, v2.6.0

#6437 Update EKS Kubernetes version to 1.21
  hack/deployer/config/plans.yml
Labels: :ci, >test

#6433 Make `E2E_JSON` and `E2E_TAGS` usable at runtime
  Makefile
  config/e2e/e2e_job.yaml
  test/e2e/Dockerfile
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/run.go
  test/e2e/test/context.go
Labels: :ci, >refactoring

#6445 Increase verbosity for .ci/setenvconfig and e2e-run target
  .ci/setenvconfig
  Makefile
Labels: :ci, >non-issue

#6434 Refactoring docker registry creds
  .ci/Makefile
  .ci/jobs/publish-dockerhub.yml
  .ci/pipelines/publish-dockerhub.Jenkinsfile
  .ci/setenvconfig
  Makefile
  hack/docker.sh
  hack/publish-dockerhub.sh
Labels: :ci, >refactoring

#6409 Allow setting of volumeClaimDeletePolicy for eck-elasticsearch Helm chart.
  deploy/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-elasticsearch/values.yaml
Labels: >enhancement, v2.7.0

#6440 Allow optional SSL client authentication setting
  docs/orchestrating-elastic-stack-applications/elasticsearch/reserved-settings.asciidoc
  pkg/apis/elasticsearch/v1/fields.go
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/common/settings/canonical_config_test.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/warnings.go
  pkg/controller/elasticsearch/validation/warnings_test.go
Labels: >enhancement, v2.7.0

#6452 Propate E2E_TAGS in e2e chaos job
  config/e2e/chaos_job.yaml
Labels: >bug, :ci, v2.7.0

#6450 Remove migrated jobs jenkins
  .ci/jobs/e2e-tests-aks.yml
  .ci/jobs/e2e-tests-eks.yml
  .ci/jobs/e2e-tests-gke-k8s-versions.yml
  .ci/jobs/e2e-tests-kind-k8s-versions.yml
  .ci/jobs/e2e-tests-resilience.yml
  .ci/jobs/e2e-tests-stack-versions-gke.yml
  .ci/jobs/e2e-tests-tanzu.yml
  .ci/jobs/publish-dockerhub.yml
  .ci/pipelines/build.Jenkinsfile
  .ci/pipelines/e2e-tests-aks.Jenkinsfile
  .ci/pipelines/e2e-tests-eks.Jenkinsfile
  .ci/pipelines/e2e-tests-gke-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-kind-k8s-versions.Jenkinsfile
  .ci/pipelines/e2e-tests-resilience.Jenkinsfile
  .ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
  .ci/pipelines/e2e-tests-tanzu.Jenkinsfile
  .ci/pipelines/publish-dockerhub.Jenkinsfile
Labels: :ci, >refactoring, v2.7.0

#6418 Refactoring build and test secrets setup
  .buildkite/pipeline-nightly-e2e-tests.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common/get-test-artifacts.sh
  .ci/Dockerfile
  .ci/Makefile
  .ci/setenvconfig
  .gitignore
  cmd/license-initializer/main.go
  cmd/license-initializer/main_test.go
  hack/deployer/runner/aks.go
  hack/deployer/runner/azure/azure.go
  hack/deployer/runner/eks.go
  hack/deployer/runner/gcloud.go
  hack/deployer/runner/gke.go
  hack/deployer/runner/ocp.go
  hack/deployer/runner/ocp3.go
  hack/deployer/runner/settings.go
  hack/deployer/runner/tanzu.go
  hack/deployer/vault/vault.go
  hack/helm/release/cmd/root.go
  hack/helm/release/cmd/vault.go
  pkg/utils/vault/client.go
  pkg/utils/vault/read.go
  pkg/utils/vault/read_test.go
  pkg/utils/vault/secret_file.go
  pkg/utils/vault/secret_file_test.go
  test/e2e/cmd/run/run.go
Labels: :ci, >refactoring, v2.7.0

#6214 Fix Elastic Agent Fleet Server without TLS e2e tests
  pkg/controller/agent/pod.go
  pkg/controller/agent/pod_test.go
  test/e2e/agent/tls_test.go
Labels: >test, v2.7.0

#6454 Remove reference to deleted script
  .buildkite/pipeline.yml
  Makefile
Labels: >bug, :ci

#6281 OperatorHub Release CLI / Moving OperatorHub release to Buildkite
  .buildkite/pipeline-release-operatorhub.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/operatorhub/operations.sh
  hack/operatorhub/Makefile
  hack/operatorhub/README.md
  hack/operatorhub/cmd/buildkite/buildkite.go
  hack/operatorhub/cmd/bundle/bundle.go
  hack/operatorhub/cmd/container/container.go
  hack/operatorhub/cmd/flags/flags.go
  hack/operatorhub/cmd/manifests/manifests.go
  hack/operatorhub/cmd/root.go
  hack/operatorhub/cmd/vault.go
  hack/operatorhub/config.yaml
  hack/operatorhub/go.mod
  hack/operatorhub/go.sum
  hack/operatorhub/internal/container/container.go
  hack/operatorhub/internal/container/types.go
  hack/operatorhub/internal/github/fork.go
  hack/operatorhub/internal/github/github.go
  hack/operatorhub/internal/operatorhub/operatorhub.go
  hack/operatorhub/internal/opm/opm.go
  hack/operatorhub/main.go
Labels: >enhancement, exclude-from-release-notes

#6462 Fix vault client being nil in Azure deployer.
  hack/deployer/runner/aks.go
Labels: >bug, :ci
