Repository elastic/cloud-on-k8s, pull requests merged in 2023-10, with the labels that each got.

#7196 Adjust e2e cleanup older-than duration to 24 hours.
  hack/deployer/cmd/cleanup.go
Labels: >test

#7197 Do not fail build on k8s cluster deletion failure
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: >enhancement, :ci

#7200 Move soft_fail directive
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: >bug, :ci

#7155 Fixes podDisruptionBudget description for Elasticsearch.spec
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  deploy/eck-stack/charts/eck-elasticsearch/values.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
Labels: >docs, v2.10.0 (next)

#7212 soft_fail on any status code on k8s cluster deletion
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: >enhancement, :ci

#7213 Adjust sample command outputs in the Agent Fleet documentation
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
Labels: >docs, v2.10.0 (next)

#7214 Adjust sample command outputs in the Agent Fleet documentation (#7213)
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
Labels: >docs, backport, v2.9.0

#7229 Bump golang.org/x/net to 0.17.0
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/config-extractor/go.mod
  hack/config-extractor/go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  hack/manifest-gen/go.mod
  hack/manifest-gen/go.sum
  hack/operatorhub/go.mod
  hack/operatorhub/go.sum
  hack/upgrade-test-harness/go.mod
  hack/upgrade-test-harness/go.sum
Labels: >renovate, dependencies, v2.10.0 (next)

#7228 Update ECK-Beats default values to not include ElasticsearchRef.
  deploy/eck-stack/charts/eck-beats/values.yaml
Labels: >bug, v2.10.0 (next)

#7143 Add logstash helm chart
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/README.md
  deploy/eck-stack/charts/eck-logstash/.helmignore
  deploy/eck-stack/charts/eck-logstash/Chart.yaml
  deploy/eck-stack/charts/eck-logstash/LICENSE
  deploy/eck-stack/charts/eck-logstash/examples/basic-eck.yaml
  deploy/eck-stack/charts/eck-logstash/examples/es-role.yaml
  deploy/eck-stack/charts/eck-logstash/examples/monitored.yaml
  deploy/eck-stack/charts/eck-logstash/examples/multi.yaml
  deploy/eck-stack/charts/eck-logstash/examples/volumes.yaml
  deploy/eck-stack/charts/eck-logstash/templates/NOTES.txt
  deploy/eck-stack/charts/eck-logstash/templates/_helpers.tpl
  deploy/eck-stack/charts/eck-logstash/templates/logstash.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
  deploy/eck-stack/charts/eck-logstash/values.yaml
  deploy/eck-stack/examples/logstash/basic-eck.yaml
  deploy/eck-stack/values.yaml
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
  hack/helm/release/README.md
Labels: >enhancement, :logstash, :helm-charts, v2.10.0

#7242 [2.10] Add logstash helm chart (#7143)
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/README.md
  deploy/eck-stack/charts/eck-logstash/.helmignore
  deploy/eck-stack/charts/eck-logstash/Chart.yaml
  deploy/eck-stack/charts/eck-logstash/LICENSE
  deploy/eck-stack/charts/eck-logstash/examples/basic-eck.yaml
  deploy/eck-stack/charts/eck-logstash/examples/es-role.yaml
  deploy/eck-stack/charts/eck-logstash/examples/monitored.yaml
  deploy/eck-stack/charts/eck-logstash/examples/multi.yaml
  deploy/eck-stack/charts/eck-logstash/examples/volumes.yaml
  deploy/eck-stack/charts/eck-logstash/templates/NOTES.txt
  deploy/eck-stack/charts/eck-logstash/templates/_helpers.tpl
  deploy/eck-stack/charts/eck-logstash/templates/logstash.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
  deploy/eck-stack/charts/eck-logstash/values.yaml
  deploy/eck-stack/examples/logstash/basic-eck.yaml
  deploy/eck-stack/values.yaml
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
  hack/helm/release/README.md
Labels: backport, triage, exclude-from-release-notes

#7230 [e2e] Log continuous health checks failures
  test/e2e/test/elasticsearch/steps_mutation.go
Labels: >flaky_test, :ci

#7240 Update versions for the 2.10 release
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/charts/eck-agent/Chart.yaml
  deploy/eck-stack/charts/eck-agent/examples/fleet-agents.yaml
  deploy/eck-stack/charts/eck-agent/examples/system-integration.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/charts/eck-agent/values.yaml
  deploy/eck-stack/charts/eck-beats/Chart.yaml
  deploy/eck-stack/charts/eck-beats/examples/auditbeat_hosts.yaml
  deploy/eck-stack/charts/eck-beats/examples/filebeat_no_autodiscover.yaml
  deploy/eck-stack/charts/eck-beats/examples/heartbeat_es_kb_health.yaml
  deploy/eck-stack/charts/eck-beats/examples/metricbeat_hosts.yaml
  deploy/eck-stack/charts/eck-beats/examples/packetbeat_dns_http.yaml
  deploy/eck-stack/charts/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-stack/charts/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-stack/charts/eck-beats/values.yaml
  deploy/eck-stack/charts/eck-elasticsearch/Chart.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/values.yaml
  deploy/eck-stack/charts/eck-fleet-server/Chart.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/values.yaml
  deploy/eck-stack/charts/eck-kibana/Chart.yaml
  deploy/eck-stack/charts/eck-kibana/examples/http-configuration.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/charts/eck-kibana/values.yaml
  deploy/eck-stack/charts/eck-logstash/Chart.yaml
  deploy/eck-stack/charts/eck-logstash/examples/basic-eck.yaml
  deploy/eck-stack/charts/eck-logstash/examples/es-role.yaml
  deploy/eck-stack/charts/eck-logstash/examples/monitored.yaml
  deploy/eck-stack/charts/eck-logstash/examples/multi.yaml
  deploy/eck-stack/charts/eck-logstash/examples/volumes.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
  deploy/eck-stack/charts/eck-logstash/values.yaml
  deploy/eck-stack/examples/beats/metricbeat_hosts.yaml
  deploy/eck-stack/examples/custom-elasticsearch-kibana.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/templates/tests/kibana_test.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
  hack/upgrade-test-harness/conf.yaml
Labels: >non-issue, exclude-from-release-notes, v2.10.0

#7243 Adds "ca-dir" settings to configMap for eck-operator
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, :helm-charts, v2.10.0, v2.11.0 (next)

#7239 Increase test timeout wait for Elasticsearch to be green for autopilot clusters
  Makefile
  test/e2e/test/agent/steps.go
Labels: >flaky_test, :ci, v2.11.0 (next)

#7235 Bump Stack version to 8.10.3
  .buildkite/e2e/nightly-main-matrix.yaml
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/logstash/logstash-volumes.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  config/samples/logstash/logstash.yaml
  config/samples/logstash/logstash_es.yaml
  config/samples/logstash/logstash_stackmonitor.yaml
  config/samples/logstash/logstash_svc.yaml
  hack/operatorhub/config.yaml
  test/e2e/test/version.go
Labels: >non-issue, v2.10.0, v2.11.0 (next)

#7255 Expose "ca-dir" setting for global CA in eck-operator Helm chart values
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, backport, :helm-charts, v2.10.0

#7257 Bump Stack version to 8.10.4 (#7235)
  .buildkite/e2e/nightly-main-matrix.yaml
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/logstash/logstash-volumes.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  config/samples/logstash/logstash.yaml
  config/samples/logstash/logstash_es.yaml
  config/samples/logstash/logstash_stackmonitor.yaml
  config/samples/logstash/logstash_svc.yaml
  hack/operatorhub/config.yaml
  test/e2e/test/version.go
Labels: backport, >non-issue, v2.10.0

#7252 Allow setting additional Operator flags.
  config/eck.yaml
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, :helm-charts

#7259 [2.10] Allow setting additional Operator flags. (#7252)
  config/eck.yaml
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, backport, :helm-charts, v2.10.0

#7244 Update oldest supported Openshift version
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >non-issue, exclude-from-release-notes, v2.10.0, v2.11.0 (next)

#7266 [2.10] Update oldest supported Openshift version (#7244)
  README.md
  docs/supported-versions.asciidoc
  hack/operatorhub/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport, exclude-from-release-notes

#7267 [e2e] Log test name on failure
  test/e2e/test/step.go
Labels: >flaky_test, :ci
