Repository elastic/cloud-on-k8s, pull requests merged in 2023-06, with the labels that each got.

#6869 Update Kubernetes API version used in docs
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs, v2.8.0

#6870 Update Kubernetes API version used in docs (#6869)
  docs/reference/api-docs.asciidoc
  hack/api-docs/config.yaml
Labels: >docs, backport, v2.8.0

#6874 Setup admission decoder in webhooks
  pkg/controller/autoscaling/elasticsearch/validation/webhook.go
  pkg/controller/common/webhook/webhook.go
  pkg/controller/elasticsearch/validation/webhook.go
Labels: >bug, >test, v2.9.0 (next)

#6877 Allow e2e job to delete collections
  config/e2e/rbac.yaml
Labels: >test, v2.9.0 (next)

#6882 Remove unnecessary println
  test/e2e/test/maps/checks.go
Labels: >refactoring, v2.9.0 (next)

#6883 Remove duplicate import
  test/e2e/test/k8s_client.go
Labels: >refactoring, exclude-from-release-notes, v2.9.0 (next)

#6889 Moving gke used for ci from europe to us
  hack/deployer/config/plans.yml
Labels: :ci, >non-issue

#6897 Revert "Skip upgrades to 8.9.0-SNAPSHOT (#6880)"
  test/e2e/test/version.go
Labels: >test

#6793 Add back runAsNonRoot=true to Beats >= 8.8.x
  pkg/controller/elasticsearch/securitycontext/securitycontext.go
  pkg/controller/elasticsearch/securitycontext/securitycontext_test.go
  pkg/controller/elasticsearch/stackmon/sidecar.go
  test/e2e/test/elasticsearch/check_securitycontext.go
Labels: >enhancement, v2.9.0 (next)

#6905 Revisit how to get e2e tests results
  config/e2e/e2e_job.yaml
  hack/helm/release/go.sum
  test/e2e/cmd/run/job.go
  test/e2e/cmd/run/job_manager.go
  test/e2e/cmd/run/run.go
  test/e2e/run.sh
  test/e2e/test/context.go
Labels: >bug, :ci

#6910 Remove last Jenkins bits
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/pipeline-build.yml
  .ci/Makefile
  .ci/README.md
  .ci/bin/check_paths_for_matches.py
  .ci/common/tests.groovy
  .ci/jobs/build-release.yml
  .ci/jobs/defaults.yml
  .ci/packer_cache.sh
  .ci/pipelines/build.Jenkinsfile
  .ci/setenvconfig
  .ci/views/views.yml
  .gitignore
  Makefile
  hack/docker.sh
  hack/pipeline-validator/main.go
Labels: :ci, >refactoring

#6917 Track job stops and file downloads
  test/e2e/cmd/run/job.go
  test/e2e/cmd/run/job_manager.go
Labels: >test

#6918 Do not close channels, rem errexit
  test/e2e/cmd/run/job.go
  test/e2e/cmd/run/job_manager.go
  test/e2e/run.sh
Labels: >test

#6920 [2.8] Update service-account.yaml (#6915)
  deploy/eck-stack/charts/eck-beats/templates/service-account.yaml
Labels: >bug, backport

#6922 Fix e2e tests fail fast deletion and jobs stop
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  test/e2e/cmd/run/job.go
  test/e2e/cmd/run/job_manager.go
  test/e2e/test/diagnostics.go
  test/e2e/test/utils.go
Labels: >bug, :ci

#6911 Release parent charts with lock file
  hack/helm/release/Makefile
  hack/helm/release/cmd/root.go
  hack/helm/release/internal/helm/helm.go
Labels: >bug, :ci, v2.9.0 (next)

#6923 Add pipeline to release Helm charts
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: >enhancement, :ci

#6919 Do not attempt annotation update when no failures occur.
  .buildkite/e2e/reporter/templates/annotate-failures.tpl.md
  .buildkite/e2e/reporter/templates/annotate-success.tpl.md
Labels: >test

#6932 [helm] Release parent charts with lock file (#6911)
  hack/helm/release/Makefile
  hack/helm/release/cmd/root.go
  hack/helm/release/internal/helm/helm.go
Labels: >bug, backport, v2.8.0, :helm-charts

#6931 Add pipeline to release Helm charts (#6923)
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: >enhancement, :ci, backport, v2.8.0, :helm-charts

#6926 [helm/eck-elasticsearch] Support disabling podDisruptionBudget
  deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/values.yaml
Labels: >bug, v2.8.0, :helm-charts

#6719 Support autopilot clusters in deployer.
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/scripts/test/set-deployer-config.sh
  config/e2e/e2e_job.yaml
  config/e2e/monitoring.yaml
  config/e2e/rbac.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  docs/advanced-topics/gke-autopilot.asciidoc
  hack/deployer/config/plans.yml
  hack/deployer/runner/gke.go
  hack/deployer/runner/kyverno/install/policies.yaml
  hack/deployer/runner/settings.go
  hack/deployer/runner/storage.go
  test/e2e/autopilot_test.go
  test/e2e/cmd/run/run.go
  test/e2e/test/context.go
  test/e2e/test/elasticsearch/builder.go
  test/e2e/test/helper/yaml.go
  test/e2e/test/k8s_client.go
Labels: >enhancement, :ci

#6937 [helm/eck-elasticsearch] Support disabling podDisruptionBudget #6926
  deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/values.yaml
Labels: >bug, backport, v2.8.0, :helm-charts

#6934 Update pipelines provider settings
  catalog-info.yaml
Labels: >enhancement, :ci

#6929 Remove dependency between operator-build and release-manifests
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-release.yml
  .buildkite/scripts/release/k8s-manifests.sh
  Makefile
Labels: :ci, >refactoring

#6927 Lazy vault client creation when reading vault file
  cmd/license-initializer/main.go
  hack/deployer/runner/gcloud.go
  hack/helm/release/cmd/root.go
  pkg/utils/vault/client.go
  pkg/utils/vault/read_test.go
  pkg/utils/vault/secret_file.go
  pkg/utils/vault/secret_file_test.go
  test/e2e/cmd/run/run.go
Labels: >enhancement, :ci, v2.9.0 (next)

#6930 Track in git the default eck config
  .gitignore
  config/eck.yaml
  hack/config-extractor/extract.sh
Labels: :ci, >refactoring, v2.9.0 (next)

#6936 Helm release pipeline
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  hack/helm/release/Makefile
  hack/helm/release/trigger-helm-release.sh
  hack/operatorhub/trigger-rh-release.sh
Labels: >bug, >enhancement, :ci, v2.8.0

#6945 Agent and trigger for Helm release pipeline (#6936)
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  hack/helm/release/Makefile
  hack/helm/release/trigger-helm-release.sh
Labels: >bug, >enhancement, :ci, backport, v2.8.0

#6943 Bump eck-stack SNAPSHOT versions for next cycle
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/charts/eck-agent/Chart.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/charts/eck-beats/Chart.yaml
  deploy/eck-stack/charts/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/Chart.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/Chart.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-stack/charts/eck-kibana/Chart.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
Labels: >non-issue, v2.9.0 (next), :helm-charts

#6895 Logstash connect to external Elasticsearch
  docs/orchestrating-elastic-stack-applications/logstash.asciidoc
Labels: >docs, v2.9.0 (next), logstash

#6938 Validating policy ID only when running in fleet mode for Elastic Agent
  pkg/apis/agent/v1alpha1/webhook.go
  pkg/controller/common/webhook/webhook_test.go
Labels: >bug, v2.9.0 (next)

#6951 Run only integration tests
  Makefile
Labels: >bug, :ci

#6949 Fix eck-diagnostics download run for each e2e test failure
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/scripts/common/cp-diagnostics.sh
  config/e2e/e2e_job.yaml
  test/e2e/Dockerfile
  test/e2e/cmd/run/command.go
  test/e2e/cmd/run/job.go
  test/e2e/cmd/run/job_manager.go
  test/e2e/cmd/run/run.go
  test/e2e/run.sh
  test/e2e/test/context.go
  test/e2e/test/diagnostics.go
Labels: >bug, :ci, v2.9.0 (next)

#6953 Fix variable name for dry run mode in helm release
  .buildkite/pipeline-release.yml
Labels: >bug, :ci

#6957 Disable test agent with fleet mode in 8.0.1
  test/e2e/agent/config_test.go
  test/e2e/agent/recipes_test.go
  test/e2e/agent/tls_test.go
  test/e2e/agent/upgrade_test.go
  test/e2e/test/agent/builder.go
Labels: >flaky_test, v2.9.0 (next)

#6958 Fix RBAC to run e2e tests with Filebeat autodiscover in 8.9.0
  config/e2e/roles.yaml
Labels: >test, v2.9.0 (next)

#6961 Skip APM Server tests without apm integration in 8.9.0-SNAPSHOT
  test/e2e/test/apmserver/builder.go
Labels: >test, v2.9.0 (next)

#6964 Generate the trigger step to remove v prefix from BUILDKITE_TAG
  .buildkite/pipeline-release.yml
Labels: >bug, :ci, v2.9.0 (next)

#6952 Run TestVersionUpgradeOrdering with/without Logstash
  pkg/controller/logstash/logstash_controller.go
  test/e2e/stack_test.go
Labels: >bug, >test, v2.9.0 (next), :logstash
