Repository elastic/cloud-on-k8s, pull requests merged in 2023-04, with the labels that each got.

#6640 Fix detecting multiarch image already pushed
  .buildkite/scripts/build/is_published.sh
  .buildkite/scripts/build/setenv.sh
  .buildkite/scripts/build/setenv_test.sh
  Makefile
Labels: >bug, :ci

#6639 Remove OCP3 support
  .ci/Makefile
  .ci/setenvconfig
  config/e2e/e2e_job.yaml
  hack/deployer/config/plans.yml
  hack/deployer/runner/settings.go
  test/e2e/agent/webhook_test.go
  test/e2e/beat/webhook_test.go
  test/e2e/cmd/run/run.go
  test/e2e/test/beat/builder.go
  test/e2e/test/context.go
Labels: :ci, >non-issue, v2.8.0

#6644 Better support dev operator build to test snapshot stack versions
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/pipeline-gen/main.go
  .buildkite/pipeline-build.yml
  .buildkite/scripts/build/setenv.sh
  .buildkite/scripts/build/setenv_test.sh
Labels: >enhancement, :ci, v2.8.0

#6638 Update upgrade-test-harness to ECK 2.7.0 / 2.8.0-SNAPSHOT
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/upcoming/stack.yml
  hack/upgrade-test-harness/testdata/v170/crds.yaml
  hack/upgrade-test-harness/testdata/v170/install.yaml
  hack/upgrade-test-harness/testdata/v170/stack.yaml
  hack/upgrade-test-harness/testdata/v171/crds.yaml
  hack/upgrade-test-harness/testdata/v171/install.yaml
  hack/upgrade-test-harness/testdata/v180/stack.yaml
  hack/upgrade-test-harness/testdata/v190/crds.yaml
  hack/upgrade-test-harness/testdata/v190/install.yaml
  hack/upgrade-test-harness/testdata/v190/stack.yaml
  hack/upgrade-test-harness/testdata/v191/stack.yaml
  hack/upgrade-test-harness/testdata/v200/stack.yaml
  hack/upgrade-test-harness/testdata/v210/stack.yaml
  hack/upgrade-test-harness/testdata/v220/stack.yaml
  hack/upgrade-test-harness/testdata/v230/stack.yaml
  hack/upgrade-test-harness/testdata/v240/stack.yaml
  hack/upgrade-test-harness/testdata/v250/stack.yaml
  hack/upgrade-test-harness/testdata/v261/stack.yaml
  hack/upgrade-test-harness/testdata/v270/crds.yaml
  hack/upgrade-test-harness/testdata/v270/operator.yaml
  hack/upgrade-test-harness/testdata/v270/stack.yaml
Labels: :ci, >test, v2.8.0

#6654 Update github.com/docker/docker
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  hack/manifest-gen/go.mod
  hack/manifest-gen/go.sum
  hack/operatorhub/go.mod
  hack/operatorhub/go.sum
Labels: >renovate, v2.8.0

#6637 Bump Stack version to 8.7.0 / 8.8.0-SNAPSHOT
  .buildkite/e2e/nightly-main-matrix.yaml
  Makefile
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  test/e2e/test/apmserver/builder.go
  test/e2e/test/version.go
Labels: >docs, :ci, >test, v2.7.0

#6656 [ci/agent] Update docker.io/library/golang Docker tag to v1.20.3
  .buildkite/pipeline.yml
  .ci/Makefile
Labels: :ci, >renovate

#6660 Separate pipeline to release ECK on RedHat channels
  .buildkite/pipeline-build.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  catalog-info.yaml
Labels: >enhancement, :ci

#6480 Logstash pipelines
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  config/samples/logstash/logstash.yaml
  config/webhook/manifests.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/api-docs.asciidoc
  pkg/apis/logstash/v1alpha1/logstash_types.go
  pkg/apis/logstash/v1alpha1/name.go
  pkg/apis/logstash/v1alpha1/validations.go
  pkg/apis/logstash/v1alpha1/validations_test.go
  pkg/apis/logstash/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/common/configref.go
  pkg/controller/logstash/driver.go
  pkg/controller/logstash/logstash_controller.go
  pkg/controller/logstash/pipeline.go
  pkg/controller/logstash/pipeline_test.go
  pkg/controller/logstash/pipelines/config.go
  pkg/controller/logstash/pipelines/config_test.go
  pkg/controller/logstash/pipelines/ref.go
  pkg/controller/logstash/pipelines/ref_test.go
  pkg/controller/logstash/pod.go
  test/e2e/logstash/logstash_test.go
  test/e2e/logstash/pipeline_test.go
  test/e2e/test/k8s_client.go
  test/e2e/test/logstash/builder.go
  test/e2e/test/logstash/checks.go
Labels: >enhancement

#6621 Remove default for daemonset/deployment in eck-beats & eck-agent Helm Charts
  deploy/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-beats/values.yaml
  deploy/eck-stack/examples/beats/metricbeat_hosts.yaml
  deploy/eck-stack/templates/tests/beats_test.yaml
  deploy/eck-stack/templates/tests/elastic-agent_test.yaml
  hack/helm/test.sh
Labels: >bug, v2.8.0 (next)

#6677 Bump supported aks version in both CI and Dev for Deployer.
  hack/deployer/config/plans.yml
Labels: :ci, >test

#6658 Improve operatorhub release
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/scripts/release/operatorhub.sh
  .buildkite/scripts/release/redhat-preflight.sh
  catalog-info.yaml
  hack/operatorhub/Makefile
  hack/operatorhub/README.md
  hack/operatorhub/cmd/bundle/bundle.go
  hack/operatorhub/internal/github/fork.go
  hack/operatorhub/internal/github/github.go
  hack/operatorhub/internal/operatorhub/operatorhub.go
Labels: >bug, :ci, v2.8.0 (next)

#6671 Add PDB for eck-operator helm chart
  deploy/eck-operator/templates/pdb.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, v2.8.0 (next)

#6636 Enable hostNetwork support in eck-operator Helm chart
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/values.yaml
Labels: >feature, v2.8.0 (next)

#6680 Disable build trigger for PR and branches for redhat release pipeline
  catalog-info.yaml
Labels: :ci, >non-issue

#6685 Remove trailing dot in 'gsutil rm' command
  .buildkite/scripts/common/cp-diagnostics.sh
Labels: :ci, >refactoring

#6681 ES: Use full certificate chain in the trusted certificates slice.
  pkg/controller/elasticsearch/certificates/reconcile.go
Labels: >enhancement, v2.8.0 (next)

#6699 Prevent Buildkite job annotation to be larger than 1MB
  .buildkite/e2e/reporter/main.go
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
Labels: :ci, >test, v2.8.0 (next)

#6689 Use provided base path for stackconfigpolicy's snapshot repository
  docs/orchestrating-elastic-stack-applications/stack-config-policy.asciidoc
  pkg/controller/elasticsearch/filesettings/file_settings.go
  pkg/controller/elasticsearch/filesettings/file_settings_test.go
Labels: >bug, v2.8.0 (next)

#6706 Remove Journalbeat recipe
  config/recipes/beats/README.asciidoc
  config/recipes/beats/journalbeat_hosts.yaml
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
  test/e2e/beat/recipes_test.go
Labels: :ci, >test

#6711 Conditionally set container-suffix in ECK config
  deploy/eck-operator/templates/configmap.yaml
Labels: >bug

#6704 Helm Release: Fail to write files to bucket in some scenarios
  hack/helm/release/internal/helm/helm.go
Labels: >bug, :ci

#6674 Logstash - add ability to reload pipeline(s) without triggering full pod restart
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  config/samples/logstash/logstash_svc.yaml
  pkg/controller/common/reconciler/secret.go
  pkg/controller/logstash/config.go
  pkg/controller/logstash/config_test.go
  pkg/controller/logstash/driver.go
  pkg/controller/logstash/initcontainer.go
  pkg/controller/logstash/labels.go
  pkg/controller/logstash/pipeline.go
  pkg/controller/logstash/pod.go
  pkg/controller/logstash/pod_test.go
  test/e2e/logstash/pipeline_test.go
  test/e2e/test/logstash/steps.go
Labels: >enhancement

#6717 Operator leader election: use Leases only
  cmd/manager/main.go
Labels: >enhancement, >refactoring, v2.8.0 (next)

#6723 Add script to check generated release notes
  hack/release-notes/check.sh
Labels: >enhancement, :ci, v2.8.0 (next)

#6721 [6716] Helm chart refactoring
  config/e2e/e2e_job.yaml
  deploy/eck-agent/templates/cluster-role-binding.yaml
  deploy/eck-agent/templates/cluster-role.yaml
  deploy/eck-agent/templates/elastic-agent.yaml
  deploy/eck-agent/templates/service-account.yaml
  deploy/eck-beats/templates/beats.yaml
  deploy/eck-beats/templates/cluster-role-binding.yaml
  deploy/eck-beats/templates/cluster-role.yaml
  deploy/eck-beats/templates/service-account.yaml
  deploy/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-fleet-server/templates/cluster-role-binding.yaml
  deploy/eck-fleet-server/templates/cluster-role.yaml
  deploy/eck-fleet-server/templates/fleet-server.yaml
  deploy/eck-fleet-server/templates/service-account.yaml
  deploy/eck-kibana/templates/kibana.yaml
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/templates/podMonitor.yaml
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/templates/webhook.yaml
Labels: >refactoring

#6703 Copy Elasticsearch configuration files before creating links
  pkg/controller/beat/common/stackmon/stackmon_test.go
  pkg/controller/common/defaults/pod_template.go
  pkg/controller/common/keystore/initcontainer.go
  pkg/controller/common/stackmon/sidecar.go
  pkg/controller/elasticsearch/driver/driver.go
  pkg/controller/elasticsearch/initcontainer/prepare_fs.go
  pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go
  pkg/controller/elasticsearch/nodespec/podspec.go
  pkg/controller/elasticsearch/nodespec/podspec_test.go
  pkg/controller/elasticsearch/nodespec/volumes.go
  pkg/controller/elasticsearch/securitycontext/securitycontext.go
  pkg/controller/elasticsearch/stackmon/sidecar.go
  pkg/controller/elasticsearch/stackmon/sidecar_test.go
  pkg/controller/elasticsearch/volume/names.go
  pkg/controller/kibana/stackmon/sidecar_test.go
  test/e2e/test/elasticsearch/check_securitycontext.go
  test/e2e/test/elasticsearch/checks_k8s.go
Labels: >enhancement, v2.8.0 (next)

#6731 Fix the sample tests for logstash service and stack monitoring
  config/samples/logstash/logstash_svc.yaml
  test/e2e/logstash/stack_monitoring_test.go
  test/e2e/samples_test.go
  test/e2e/test/logstash/builder.go
  test/e2e/test/logstash/checks.go
Labels: >test

#6724 [Fleet] Deprecate is_default and is_default_fleet_server flags
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  deploy/eck-agent/examples/fleet-agents.yaml
  deploy/eck-agent/values.yaml
  deploy/eck-fleet-server/values.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  deploy/eck-stack/examples/agent/fleet-agents.yaml
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/agent/v1alpha1/validations.go
  pkg/apis/agent/v1alpha1/validations_test.go
  pkg/apis/agent/v1alpha1/webhook.go
  pkg/controller/agent/fleet.go
  pkg/controller/agent/fleet_test.go
  pkg/controller/common/webhook/warnings.go
  pkg/controller/common/webhook/webhook.go
  pkg/controller/common/webhook/webhook_test.go
  pkg/utils/test/events.go
Labels: >enhancement, v2.8.0 (next)
