Repository elastic/cloud-on-k8s, pull requests merged in 2024-03, with the labels that each got.

#7587 Ensure statefulset name label is set for Logstash pods
  pkg/controller/logstash/driver.go
Labels: >bug, :logstash, v2.12.0 (❅)

#7588 Ensure statefulset name label is set for Logstash pods (#7587)
  pkg/controller/logstash/driver.go
Labels: >bug, backport, exclude-from-release-notes, v2.12.0 (❅)

#7589 Adjusting the version check to disable fleet e2e test validation
  test/e2e/test/agent/builder.go
Labels: >flaky_test, :ci, >test

#7567 Add RBAC authentication option for the ECK metrics endpoint.
  cmd/manager/main.go
  deploy/eck-operator/templates/_helpers.tpl
  deploy/eck-operator/templates/auth-proxy-service.yaml
  deploy/eck-operator/templates/cluster-roles.yaml
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/templates/operator-network-policy.yaml
  deploy/eck-operator/templates/podMonitor.yaml
  deploy/eck-operator/templates/role-bindings.yaml
  deploy/eck-operator/templates/serviceMonitor.yaml
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/values.yaml
  docs/operating-eck/configure-operator-metrics.asciidoc
  docs/operating-eck/operating-eck.asciidoc
  pkg/controller/common/operator/flags.go
Labels: >enhancement, v2.12.0

#7601 Fix jq query to filter by date to delete EKS clusters
  hack/deployer/runner/eks.go
Labels: >bug, :ci

#7605 Add RBAC authentication option for the ECK metrics endpoint (#7567)
  cmd/manager/main.go
  deploy/eck-operator/templates/_helpers.tpl
  deploy/eck-operator/templates/auth-proxy-service.yaml
  deploy/eck-operator/templates/cluster-roles.yaml
  deploy/eck-operator/templates/configmap.yaml
  deploy/eck-operator/templates/operator-network-policy.yaml
  deploy/eck-operator/templates/podMonitor.yaml
  deploy/eck-operator/templates/role-bindings.yaml
  deploy/eck-operator/templates/serviceMonitor.yaml
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/values.yaml
  docs/operating-eck/configure-operator-metrics.asciidoc
  docs/operating-eck/operating-eck.asciidoc
  pkg/controller/common/operator/flags.go
Labels: >enhancement, backport, v2.12.0

#7607 Edit Makefile Target
  Makefile
Labels: >bug, :ci

#7614 Restrict PR builds only to buildkite-pr-bot
  catalog-info.yaml
Labels: >enhancement, :ci

#7621 Update ECK Stack Helm charts
  deploy/README.md
  deploy/eck-stack/charts/eck-agent/templates/elastic-agent.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/charts/eck-apm-server/templates/apmserver.yaml
  deploy/eck-stack/charts/eck-apm-server/templates/tests/apmserver_test.yaml
  deploy/eck-stack/charts/eck-beats/templates/beats.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/fleet-server.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-stack/charts/eck-kibana/templates/kibana.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/charts/eck-logstash/templates/logstash.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
Labels: >enhancement, exclude-from-release-notes, v2.12.0

#7623 Small docs update
  deploy/README.md
Labels: >docs, v2.12.0

#7599 Release notes and highlights for v2.12.0
  docs/release-notes.asciidoc
  docs/release-notes/2.12.0.asciidoc
  docs/release-notes/highlights-2.12.0.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v2.12.0

#7628 Version gate for deprecated `node_version` in desired nodes requests in +8.13
  pkg/controller/elasticsearch/client/desired_nodes.go
  pkg/controller/elasticsearch/driver/desired_nodes.go
  pkg/controller/elasticsearch/nodespec/desired_nodes.go
Labels: >refactoring, v2.12.0

#7629 Version gate to deprecate node_version using update desired nodes API (7628)
  pkg/controller/elasticsearch/client/desired_nodes.go
  pkg/controller/elasticsearch/driver/desired_nodes.go
  pkg/controller/elasticsearch/nodespec/desired_nodes.go
Labels: backport, >refactoring, v2.12.0

#7622 Update eck-stack Helm charts (#7621)
  deploy/README.md
  deploy/eck-stack/charts/eck-agent/templates/elastic-agent.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/charts/eck-apm-server/templates/apmserver.yaml
  deploy/eck-stack/charts/eck-apm-server/templates/tests/apmserver_test.yaml
  deploy/eck-stack/charts/eck-beats/templates/beats.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/fleet-server.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-stack/charts/eck-kibana/templates/kibana.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/charts/eck-logstash/templates/logstash.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
Labels: >enhancement, backport, v2.12.0

#7630 Fix cluster name label of es scripts config map
  pkg/controller/elasticsearch/configmap/configmap.go
  pkg/controller/elasticsearch/configmap/configmap_test.go
Labels: >bug, v2.13.0 (next)

#7640 Fix namespace logged twice
  pkg/controller/association/resources.go
Labels: >bug, v2.13.0 (next)

#7652 Update stack version in recipes (#7651)
  config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml
  config/recipes/elastic-agent/ksm-sharding.yaml
Labels: >docs, backport

#7642 Fix Logstash keystore performance
  docs/orchestrating-elastic-stack-applications/logstash.asciidoc
  pkg/controller/common/keystore/initcontainer.go
  pkg/controller/common/keystore/resources_test.go
  pkg/controller/logstash/keystore.go
  test/e2e/logstash/keystore_test.go
Labels: >enhancement, :logstash, v2.13.0 (next)

#7650 Update docs attributes for 2.12
  docs/eck-attributes.asciidoc
Labels: >docs, exclude-from-release-notes

#7657 Update buildkite agent image (openshift-preflight v1.9.1)
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
Labels: :ci, >non-issue

#7658 [2.12] Update buildkite agent image (openshift-preflight v1.9.1)
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
  .golangci.yml
  docs/reference/api-docs.asciidoc
  hack/api-docs/build.sh
  hack/api-docs/config.yaml
Labels: :ci, >non-issue, v2.12.0

#7660 Update upgrade test harness after ECK 2.12.0
  hack/upgrade-test-harness/conf.yaml
  hack/upgrade-test-harness/testdata/v180/crds.yaml
  hack/upgrade-test-harness/testdata/v180/install.yaml
  hack/upgrade-test-harness/testdata/v2111/crds.yaml
  hack/upgrade-test-harness/testdata/v2111/install.yaml
  hack/upgrade-test-harness/testdata/v2111/stack.yaml
  hack/upgrade-test-harness/testdata/v2120/crds.yaml
  hack/upgrade-test-harness/testdata/v2120/install.yaml
  hack/upgrade-test-harness/testdata/v2120/stack.yaml
Labels: >non-issue

#7662 Update operator used to monitor e2e tests to 2.12.0
  config/e2e/helm-monitoring-operator.yaml
  config/e2e/monitoring.yaml
Labels: >non-issue, v2.13.0 (next)

#7666 Update versions for 2.12.1 release
  VERSION
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
Labels: >non-issue, v2.12.1

#7665 Document known issue for 2.12.0
  docs/release-notes/highlights-2.12.0.asciidoc
Labels: >docs, v2.12.0

#7668 Document known issue for 2.12.0 (#7665)
  docs/release-notes/highlights-2.12.0.asciidoc
Labels: >docs, backport, v2.12.0

#7663 Move desired nodes version gate in the client
  pkg/controller/elasticsearch/client/desired_nodes.go
  pkg/controller/elasticsearch/driver/desired_nodes.go
  pkg/controller/elasticsearch/nodespec/desired_nodes.go
Labels: >bug, v2.12.1

#7669 Move desired nodes version gate in the client (#7663)
  pkg/controller/elasticsearch/client/desired_nodes.go
  pkg/controller/elasticsearch/driver/desired_nodes.go
  pkg/controller/elasticsearch/nodespec/desired_nodes.go
Labels: >bug, backport, v2.12.1

#7667 2.12.1 release notes and highlights
  docs/release-notes.asciidoc
  docs/release-notes/2.12.1.asciidoc
  docs/release-notes/highlights-2.12.1.asciidoc
  docs/release-notes/highlights.asciidoc
Labels: >docs, v2.12.1

#7678 [Autoscaling] Do not delete existing resources
  docs/orchestrating-elastic-stack-applications/elasticsearch/autoscaling.asciidoc
  pkg/apis/common/v1alpha1/resources.go
  pkg/apis/common/v1alpha1/resources_test.go
Labels: >bug, autoscaling, v2.13.0 (next)

#7598 Support api_key authentication for agent-elasticsearch association
  config/crds/v1/all-crds.yaml
  config/crds/v1/bases/agent.k8s.elastic.co_agents.yaml
  config/crds/v1/bases/apm.k8s.elastic.co_apmservers.yaml
  config/crds/v1/bases/beat.k8s.elastic.co_beats.yaml
  config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1/bases/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/v1/bases/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
  config/crds/v1/bases/maps.k8s.elastic.co_elasticmapsservers.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc
  docs/orchestrating-elastic-stack-applications/beat.asciidoc
  docs/reference/api-docs.asciidoc
  pkg/apis/agent/v1alpha1/agent_types.go
  pkg/apis/apm/v1/apmserver_types.go
  pkg/apis/beat/v1beta1/beat_types.go
  pkg/apis/common/v1/association.go
  pkg/apis/common/v1/common.go
  pkg/apis/elasticsearch/v1/elasticsearch_types.go
  pkg/apis/enterprisesearch/v1/enterprisesearch_types.go
  pkg/apis/enterprisesearch/v1beta1/enterprisesearch_types.go
  pkg/apis/kibana/v1/kibana_types.go
  pkg/apis/logstash/v1alpha1/logstash_types.go
  pkg/apis/maps/v1alpha1/maps_types.go
  pkg/controller/agent/config.go
  pkg/controller/association/conf.go
  pkg/controller/association/controller/agent_fleetserver.go
  pkg/controller/association/controller/apm_kibana.go
  pkg/controller/association/controller/beat_es.go
  pkg/controller/association/controller/kibana_ent.go
  pkg/controller/association/controller/kibana_es.go
  pkg/controller/association/reconciler.go
  pkg/controller/association/reconciler_test.go
  pkg/controller/association/secret.go
  pkg/controller/association/secret_test.go
  pkg/controller/beat/common/config.go
  pkg/controller/beat/common/stackmon/stackmon.go
  pkg/controller/common/association/association.go
  pkg/controller/kibana/stackmon/sidecar.go
Labels: >enhancement, v2.13.0 (next)

#7680 Update saml-authentication.asciidoc
  docs/orchestrating-elastic-stack-applications/security/saml-authentication.asciidoc
Labels: >docs, v2.13.0 (next)
