Repository elastic/cloud-on-k8s, pull requests merged in 2025-03, with the labels that each got.

#8500 Migrate dependency reference to markdown
  docs/reference/dependencies.asciidoc
  docs/reference/third-party-dependencies.md
  hack/licence-detector/generate-notice.sh
  hack/licence-detector/templates/dependencies.asciidoc.tmpl
  hack/licence-detector/templates/dependencies.md.tmpl
Labels: >docs

#8503 Log resourceVersion on Create and Update
  pkg/controller/common/reconciler/reconciler.go
Labels: >enhancement, v3.0.0 (next)

#8501 Migrate API reference to markdown
  docs/docset.yml
  docs/reference/api-docs.asciidoc
  docs/reference/api-docs.md
  docs/reference/index.md
  docs/reference/toc.yml
  hack/api-docs/build.sh
  hack/api-docs/templates/gv_details.tpl
  hack/api-docs/templates/gv_list.tpl
  hack/api-docs/templates/type.tpl
  hack/api-docs/templates/type_members.tpl
Labels: >docs

#8497 Update 2.16 breaking changes documentation for Kibana init container renaming
  docs/release-notes/2.16.0.asciidoc
Labels: >docs

#8506 [2.16] Update 2.16 breaking changes documentation for Kibana init container renaming (#8497)
  docs/release-notes/2.16.0.asciidoc
Labels: >docs, backport

#8476 Updates for Istio 1.24
  config/recipes/istio-gateway/README.asciidoc
  docs/advanced-topics/service-meshes.asciidoc
Labels: >docs

#8512 Config: Allow escaping dots in keys via '[unsplit.key]' syntax
  NOTICE.txt
  docs/reference/third-party-dependencies.md
  go.mod
  go.sum
  pkg/controller/common/settings/canonical_config.go
  pkg/controller/common/settings/canonical_config_test.go
Labels: >enhancement, v3.0.0 (next)

#8509 Remove ubi suffix for 9.x images
  cmd/manager/main.go
  pkg/controller/common/container/container.go
  pkg/controller/common/container/container_test.go
Labels: >enhancement, v3.0.0 (next)

#8507 Remove support for 6.x stack version
  .buildkite/e2e/release-branch-matrix.yaml
  README.md
  hack/operatorhub/templates/csv.tpl
  pkg/apis/agent/v1alpha1/validations.go
  pkg/apis/agent/v1alpha1/validations_test.go
  pkg/apis/agent/v1alpha1/webhook.go
  pkg/apis/apm/v1/webhook.go
  pkg/apis/apm/v1/webhook_test.go
  pkg/apis/apm/v1beta1/webhook.go
  pkg/apis/apm/v1beta1/webhook_test.go
  pkg/apis/beat/v1beta1/validations.go
  pkg/apis/beat/v1beta1/validations_test.go
  pkg/apis/beat/v1beta1/webhook.go
  pkg/apis/common/v1/validations.go
  pkg/apis/elasticsearch/v1beta1/validations_test.go
  pkg/apis/enterprisesearch/v1/webhook.go
  pkg/apis/enterprisesearch/v1/webhook_test.go
  pkg/apis/enterprisesearch/v1beta1/webhook.go
  pkg/apis/enterprisesearch/v1beta1/webhook_test.go
  pkg/apis/kibana/v1/webhook.go
  pkg/apis/kibana/v1/webhook_test.go
  pkg/apis/kibana/v1beta1/webhook.go
  pkg/apis/kibana/v1beta1/webhook_test.go
  pkg/apis/maps/v1alpha1/webhook.go
  pkg/apis/maps/v1alpha1/webhook_test.go
  pkg/controller/common/version/version.go
  pkg/controller/common/webhook/webhook_test.go
  pkg/controller/elasticsearch/driver/upgrade_predicates_test.go
  pkg/controller/elasticsearch/elasticsearch_controller.go
  pkg/controller/elasticsearch/license/apply_test.go
  pkg/controller/elasticsearch/observer/observer_test.go
  pkg/controller/elasticsearch/settings/merged_config_test.go
  pkg/controller/elasticsearch/validation/validations.go
  pkg/controller/elasticsearch/validation/validations_test.go
  pkg/controller/elasticsearch/validation/warnings.go
  pkg/controller/elasticsearch/validation/webhook.go
  pkg/controller/elasticsearch/validation/webhook_test.go
  pkg/controller/elasticsearch/version/supported_versions.go
  pkg/controller/elasticsearch/version/supported_versions_test.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/utils/test/webhook.go
  test/e2e/es/version_upgrade_test.go
  test/e2e/test/version.go
Labels: >enhancement, v3.0.0 (next)

#8518 Support new agent image path as of 9.0
  pkg/controller/agent/pod.go
  pkg/controller/common/container/container.go
  pkg/controller/common/container/container_test.go
Labels: >enhancement, v3.0.0 (next)

#8521 update the net package
  NOTICE.txt
  docs/reference/third-party-dependencies.md
  go.mod
  go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  hack/operatorhub/go.mod
  hack/operatorhub/go.sum
Labels: >enhancement, >renovate, dependencies, v3.0.0 (next)

#8530 update ci agent image
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
Labels: >test, exclude-from-release-notes, v3.0.0 (next)

#8534 Bump e2e test memory to 5G
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
Labels: :ci, >test

#8535 Remove unused MandatoryPolicyIDVersion const
  pkg/apis/agent/v1alpha1/agent_types.go
Labels: >refactoring, exclude-from-release-notes

#8551 Fix resource version key (#8550)
  pkg/controller/common/reconciler/reconciler.go
Labels: backport, triage

#8542 Fix enterprise search version in chart and other stack versions in readme and operator hub
  README.md
  deploy/eck-stack/charts/eck-enterprise-search/templates/tests/entsearch_test.yaml
  deploy/eck-stack/charts/eck-enterprise-search/values.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >bug, exclude-from-release-notes, v3.0.0 (next)

#8552 Re-enable 4.12 while Red Hat provides long term support
  hack/operatorhub/config.yaml
Labels: >non-issue, exclude-from-release-notes, v3.0.0 (next)

#8541 add a beats configuration pre 8.10 tests
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/beat/setup_test.go
  test/e2e/stack_test.go
Labels: >test, exclude-from-release-notes, v3.0.0 (next)

#8555 [3.0] add a beats configuration for pre 8.10 tests (#8541)
  test/e2e/beat/config.go
  test/e2e/beat/config_test.go
  test/e2e/beat/setup_test.go
  test/e2e/stack_test.go
Labels: backport, triage, exclude-from-release-notes

#8554 [3.0] Re-enable 4.12 while Red Hat provides long term support (#8552)
  hack/operatorhub/config.yaml
Labels: backport, >non-issue, exclude-from-release-notes

#8562 [3.0] Validate updates to 9.0 go through 8.18 (#8559)
  pkg/controller/elasticsearch/validation/webhook_test.go
  pkg/controller/elasticsearch/version/supported_versions.go
Labels: >enhancement, backport, v3.0.0

#8574 chore(deps): update registry.access.redhat.com/ubi9/ubi-minimal docker tag to v9.5-1741850109 (#8544)
  build/Dockerfile-ubi
  hack/deployer/clients/ocp/Dockerfile
Labels: backport, >renovate

#8558 [docs] Miscellaneous docs clean up
  docs/docset.yml
Labels: >docs

#8583 Update 2.x docs about support policy for ingress - 2nd try
  docs/advanced-topics/traffic-splitting.asciidoc
  docs/orchestrating-elastic-stack-applications/maps.asciidoc
  docs/orchestrating-elastic-stack-applications/recipes.asciidoc
  docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc
Labels: >docs, backport, v2.16.0

#8568 [CI][GKE] Increase disk size from 40 to 50
  hack/deployer/runner/gke.go
Labels: >flaky_test, >test

#8581 [2.14] Fix x-link to elasticsearch current docs
  NOTICE.txt
  docs/orchestrating-elastic-stack-applications/elasticsearch/readiness.asciidoc
  docs/release-notes/highlights-2.14.0.asciidoc
Labels: >docs, backport, v2.14.0

#7999 Add support for defining dnsPolicy and dnsConfig options for ECK operator statefulset
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/templates/tests/statefulset_test.yaml
  deploy/eck-operator/values.yaml
Labels: >feature, :helm-charts, v3.0.0

#8586 [3.0] Add support for defining dnsPolicy and dnsConfig options for ECK operator statefulset (#7999)
  deploy/eck-operator/templates/statefulset.yaml
  deploy/eck-operator/templates/tests/statefulset_test.yaml
  deploy/eck-operator/values.yaml
Labels: >enhancement, backport, v3.0.0

#8587 Update aks cluster
  hack/deployer/config/plans.yml
  hack/deployer/runner/aks.go
Labels: :ci, >test

#8588 GKE: Update K8s version to 1.31
  hack/deployer/config/plans.yml
Labels: :ci, >test
