Repository elastic/cloud-on-k8s, pull requests merged in 2025-01, with the labels that each got.

#8387 Update copyright notice for 2025
  NOTICE.txt
Labels: >non-issue, exclude-from-release-notes

#8384 Fix indentation in example with a Dead Letter Queue setup on the main…
  docs/orchestrating-elastic-stack-applications/logstash.asciidoc
Labels: >docs

#8390 [DOCS] Fix typos in stack policy documentation
  docs/orchestrating-elastic-stack-applications/stack-config-policy.asciidoc
Labels: >docs, exclude-from-release-notes

#8392 [E2E] Fix deleteTestResources
  test/e2e/test/utils.go
Labels: :ci, >test

#8374 feat(apm-server): use default image for ubi
  pkg/controller/common/container/container.go
  pkg/controller/common/container/container_test.go
Labels: >enhancement, v3.0.0 (next)

#8269 Publish stable alias tag for snapshot images
  .buildkite/pipeline.yml
  .buildkite/scripts/build/pre-build-operator.sh
  .buildkite/scripts/common/operator-image.sh
  .buildkite/scripts/common/trigger.sh
  build/gen-drivah.toml.sh
Labels: >enhancement, :ci

#8385 [Docs] Add synthetic monitoring example
  config/recipes/elastic-agent/README.asciidoc
  config/recipes/elastic-agent/synthetic-monitoring.yaml
  docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc
Labels: >docs, v3.0.0 (next)

#8403 [CI] Update Kind to 1.32
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/release-branch-matrix.yaml
  README.md
  hack/deployer/config/plans.yml
Labels: :ci, >test, v3.0.0 (next)

#8389 Init container updates for persisting kibana plugins.
  .golangci.yml
  docs/release-notes/highlights-2.16.0.asciidoc
  pkg/apis/kibana/v1/name.go
  pkg/apis/kibana/v1/name_test.go
  pkg/controller/kibana/config_reconcile.go
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/init_configuration.go
  pkg/controller/kibana/initcontainer/configmap.go
  pkg/controller/kibana/initcontainer/configmap_test.go
  pkg/controller/kibana/initcontainer/fs_scripts.go
  pkg/controller/kibana/initcontainer/fs_scripts_test.go
  pkg/controller/kibana/initcontainer/keystore.go
  pkg/controller/kibana/initcontainer/prepare_fs.go
  pkg/controller/kibana/initcontainer/prepare_fs_test.go
  pkg/controller/kibana/pod.go
  pkg/controller/kibana/pod_test.go
  pkg/controller/kibana/volume/volume.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/e2e/kb/telemetry_test.go
Labels: >enhancement

#8404 [2.16][CI] Update Kind to 1.32 (#8403)
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/release-branch-matrix.yaml
  NOTICE.txt
  hack/deployer/config/plans.yml
Labels: :ci, >test, backport

#8409 [2.16.1] Bump versions of helm charts
  deploy/eck-operator/Chart.yaml
  deploy/eck-operator/charts/eck-operator-crds/Chart.yaml
  deploy/eck-operator/templates/tests/statefulset_test.yaml
Labels: >non-issue, exclude-from-release-notes

#8408 [2.16.1-wip] Add additional volume for Kibana logs when hardened security context is enabled (#8380)
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/pod.go
  pkg/controller/kibana/pod_test.go
Labels: >bug, backport

#8410 [2.16.1-wip] Update golang.org/x/* (#8372)
  NOTICE.txt
  docs/reference/dependencies.asciidoc
  go.mod
  go.sum
  hack/config-extractor/go.mod
  hack/config-extractor/go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  hack/release-notes/go.mod
  hack/release-notes/go.sum
  hack/upgrade-test-harness/go.mod
  hack/upgrade-test-harness/go.sum
Labels: backport, >non-issue, dependencies

#8411 [2.16.1-wip] Init container updates for persisting kibana plugins. (#8389)
  .golangci.yml
  docs/release-notes/highlights-2.16.0.asciidoc
  pkg/apis/kibana/v1/name.go
  pkg/apis/kibana/v1/name_test.go
  pkg/controller/kibana/config_reconcile.go
  pkg/controller/kibana/config_settings.go
  pkg/controller/kibana/config_settings_test.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibana/driver.go
  pkg/controller/kibana/driver_test.go
  pkg/controller/kibana/init_configuration.go
  pkg/controller/kibana/initcontainer/configmap.go
  pkg/controller/kibana/initcontainer/configmap_test.go
  pkg/controller/kibana/initcontainer/fs_scripts.go
  pkg/controller/kibana/initcontainer/fs_scripts_test.go
  pkg/controller/kibana/initcontainer/keystore.go
  pkg/controller/kibana/initcontainer/prepare_fs.go
  pkg/controller/kibana/initcontainer/prepare_fs_test.go
  pkg/controller/kibana/pod.go
  pkg/controller/kibana/pod_test.go
  pkg/controller/kibana/volume/volume.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/e2e/kb/telemetry_test.go
Labels: >bug, backport

#8413 Fix Kibana hardened security context version gate.
  pkg/controller/kibana/initcontainer/configmap.go
Labels: >bug

#8414 [2.16.1-wip] Fix kibana Hardened Security Context version gate. (#8413)
  pkg/controller/kibana/initcontainer/configmap.go
Labels: triage

#8416 k8s 1.32 documentation updates.
  docs/reference/api-docs.asciidoc
  docs/supported-versions.asciidoc
  hack/api-docs/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >docs

#8417 [2.16.1-wip] [CI] Update Kind to 1.32 (#8403) | k8s 1.32 documentation updates. (#8416)
  README.md
  docs/reference/api-docs.asciidoc
  docs/supported-versions.asciidoc
  hack/api-docs/config.yaml
  hack/operatorhub/templates/csv.tpl
Labels: >docs, backport

#8412 [2.16.1] Release notes, highlights, known issues
  docs/release-notes/2.16.1.asciidoc
  docs/release-notes/highlights-2.16.0.asciidoc
  docs/release-notes/highlights-2.16.1.asciidoc
Labels: >docs

#8418 [2.16.1-wip] [2.16.1] Release notes, highlights, known issues (#8412)
  docs/release-notes/2.16.1.asciidoc
  docs/release-notes/highlights-2.16.0.asciidoc
  docs/release-notes/highlights-2.16.1.asciidoc
Labels: >docs, backport

#8419 Add 2.16.1 release notes/highlights to index.
  docs/release-notes/highlights.asciidoc
Labels: >docs

#8420 [2.16.1-wip] Add 2.16.1 release notes/highlights to index. (#8419)
  docs/release-notes/highlights.asciidoc
Labels: >docs, backport

#8422 Update to use new buildkite image with preflight 1.11.1
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
Labels: :ci, >non-issue

#8423 Add missing release-notes, not only highlights.
  docs/release-notes.asciidoc
Labels: triage

#8424 [2.16] Add missing release-notes, not only highlights. (#8423)
  docs/release-notes.asciidoc
Labels: >bug, >docs

#8425 Increment helm version for 2.16.1 release.
  deploy/eck-stack/Chart.yaml
  deploy/eck-stack/charts/eck-agent/Chart.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent-service-account_test.yaml
  deploy/eck-stack/charts/eck-agent/templates/tests/elastic-agent_test.yaml
  deploy/eck-stack/charts/eck-apm-server/Chart.yaml
  deploy/eck-stack/charts/eck-apm-server/templates/tests/apmserver_test.yaml
  deploy/eck-stack/charts/eck-beats/Chart.yaml
  deploy/eck-stack/charts/eck-beats/templates/tests/beats-metricbeat-example_test.yaml
  deploy/eck-stack/charts/eck-beats/templates/tests/beats_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/Chart.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/elasticsearch_test.yaml
  deploy/eck-stack/charts/eck-elasticsearch/templates/tests/ingress_test.yaml
  deploy/eck-stack/charts/eck-enterprise-search/Chart.yaml
  deploy/eck-stack/charts/eck-enterprise-search/templates/tests/entsearch_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/Chart.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role-binding_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-cluster-role_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server-service-account_test.yaml
  deploy/eck-stack/charts/eck-fleet-server/templates/tests/fleet-server_test.yaml
  deploy/eck-stack/charts/eck-kibana/Chart.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/ingress_test.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/charts/eck-logstash/Chart.yaml
  deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml
Labels: >non-issue, :helm-charts

#8427 Enable copying of ECK images to Amazon ECR
  .buildkite/pipeline-release.yml
Labels: >enhancement

#8421 Increment versions in main for 2.16.1 release.
  deploy/eck-operator/templates/tests/statefulset_test.yaml
  docs/eck-attributes.asciidoc
  hack/operatorhub/config.yaml
Labels: >docs

#8428 [2.16] Update to use new buildkite image with preflight 1.11.1 (#8422)
  .buildkite/Makefile
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  .buildkite/e2e/reporter/templates/notify-failures.tpl.yml
  .buildkite/pipeline-e2e-clusters-cleanup.yml
  .buildkite/pipeline-e2e-tests.yml
  .buildkite/pipeline-release-helm.yml
  .buildkite/pipeline-release-redhat.yml
  .buildkite/pipeline-release.yml
  .buildkite/pipeline.yml
Labels: triage

#8432 Fix unresolved attribute in ECK Quickstart
  docs/quickstart.asciidoc
Labels: >docs, v3.0.0 (next)

#8433 Tolerate mutation checks failures in TestMutationResizeMemory* tests
  test/e2e/es/mutation_test.go
Labels: >test

#8370 Update stack versions in recipes/samples and e2e matrix.
  .buildkite/e2e/nightly-main-matrix.yaml
  .buildkite/e2e/pipeline-gen/pipeline.tpl.yaml
  Makefile
  config/e2e/helm-monitoring-operator.yaml
  config/e2e/monitoring.yaml
  config/recipes/apm-server-jaeger/apm-server-jaeger.yaml
  config/recipes/associations-rbac/apm_es_kibana_rbac.yaml
  config/recipes/autopilot/elasticsearch.yaml
  config/recipes/autopilot/fleet-kubernetes-integration.yaml
  config/recipes/autopilot/kubernetes-integration.yaml
  config/recipes/autopilot/metricbeat_hosts.yaml
  config/recipes/autoscaling/elasticsearch.yaml
  config/recipes/beats/auditbeat_hosts.yaml
  config/recipes/beats/filebeat_autodiscover.yaml
  config/recipes/beats/filebeat_autodiscover_by_metadata.yaml
  config/recipes/beats/filebeat_no_autodiscover.yaml
  config/recipes/beats/heartbeat_es_kb_health.yaml
  config/recipes/beats/metricbeat_hosts.yaml
  config/recipes/beats/openshift_monitoring.yaml
  config/recipes/beats/packetbeat_dns_http.yaml
  config/recipes/beats/stack_monitoring.yaml
  config/recipes/elastic-agent/fleet-apm-integration.yaml
  config/recipes/elastic-agent/fleet-custom-logs-integration.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml
  config/recipes/elastic-agent/fleet-kubernetes-integration.yaml
  config/recipes/elastic-agent/ksm-sharding.yaml
  config/recipes/elastic-agent/kubernetes-integration.yaml
  config/recipes/elastic-agent/multi-output.yaml
  config/recipes/elastic-agent/system-integration.yaml
  config/recipes/gclb/01-elastic-stack.yaml
  config/recipes/gclb/99-kibana-path.yaml
  config/recipes/istio-gateway/03-elasticsearch-kibana.yaml
  config/recipes/logstash/logstash-eck.yaml
  config/recipes/logstash/logstash-es-role.yaml
  config/recipes/logstash/logstash-monitored.yaml
  config/recipes/logstash/logstash-multi.yaml
  config/recipes/logstash/logstash-pipeline-as-secret.yaml
  config/recipes/logstash/logstash-pipeline-as-volume.yaml
  config/recipes/logstash/logstash-volumes.yaml
  config/recipes/maps/01-ems.yaml
  config/recipes/maps/02-es-kb.yaml
  config/recipes/remoteclusters/elasticsearch.yaml
  config/recipes/traefik/02-elastic-stack.yaml
  config/samples/apm/apm_es_kibana.yaml
  config/samples/elasticsearch/elasticsearch.yaml
  config/samples/enterprisesearch/ent_es.yaml
  config/samples/kibana/kibana_es.yaml
  config/samples/logstash/logstash.yaml
  config/samples/logstash/logstash_es.yaml
  config/samples/logstash/logstash_pv.yaml
  config/samples/logstash/logstash_stackmonitor.yaml
  config/samples/logstash/logstash_svc.yaml
Labels: >test, exclude-from-release-notes

#8443 Update e2e tests to use ECK 2.16.1
  config/e2e/helm-monitoring-operator.yaml
Labels: >test

#8449 Remove policyID validation
  pkg/apis/agent/v1alpha1/validations.go
  pkg/apis/agent/v1alpha1/validations_test.go
Labels: >enhancement, v3.0.0 (next)
