Repository elastic/cloud-on-k8s, pull requests merged in 2025-09, with the labels that each got.

#8806 Upgrade k8s libraries
  NOTICE.txt
  config/crds/v1/all-crds.yaml
  config/crds/v1/resources/agent.k8s.elastic.co_agents.yaml
  config/crds/v1/resources/apm.k8s.elastic.co_apmservers.yaml
  config/crds/v1/resources/beat.k8s.elastic.co_beats.yaml
  config/crds/v1/resources/elasticsearch.k8s.elastic.co_elasticsearches.yaml
  config/crds/v1/resources/enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
  config/crds/v1/resources/kibana.k8s.elastic.co_kibanas.yaml
  config/crds/v1/resources/logstash.k8s.elastic.co_logstashes.yaml
  config/crds/v1/resources/maps.k8s.elastic.co_elasticmapsservers.yaml
  deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  docs/reference/third-party-dependencies/main.md
  go.mod
  go.sum
  hack/helm/release/go.mod
  hack/helm/release/go.sum
  pkg/controller/autoscaling/elasticsearch/validation/webhook_test.go
  pkg/controller/common/volume/pvc_expansion.go
  pkg/controller/common/volume/pvc_expansion_test.go
  pkg/controller/elasticsearch/driver/pvc_expansion.go
  pkg/controller/elasticsearch/driver/upscale_test.go
  pkg/controller/elasticsearch/nodespec/__snapshots__/podspec_test.snap
  pkg/controller/elasticsearch/stackmon/__snapshots__/sidecar_test.snap
  pkg/controller/kibana/stackmon/__snapshots__/sidecar_test.snap
  pkg/controller/logstash/stackmon/__snapshots__/sidecar_test.snap
  pkg/controller/logstash/volume/pvc_expansion.go
  pkg/utils/k8s/fake.go
Labels: >renovate, v3.2.0 (next)

#8822 Allow elasticsearchRef.secretName for eck-stack/Kibana
  deploy/eck-stack/charts/eck-agent/values.yaml
  deploy/eck-stack/charts/eck-apm-server/values.yaml
  deploy/eck-stack/charts/eck-beats/values.yaml
  deploy/eck-stack/charts/eck-enterprise-search/values.yaml
  deploy/eck-stack/charts/eck-fleet-server/values.yaml
  deploy/eck-stack/charts/eck-kibana/templates/kibana.yaml
  deploy/eck-stack/charts/eck-kibana/templates/tests/kibana_test.yaml
  deploy/eck-stack/charts/eck-kibana/values.yaml
Labels: >bug, :helm-charts, v3.2.0 (next)

#8832 Add missing RBAC for eck-diagnostics in e2e tests
  config/e2e/rbac.yaml
Labels: :ci, >test
